### ISSUE TITLE
Interactive map for resources

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#100]
# Done criteria
- [ ] Show's map of the UK
- [ ] 15 (?) Research centres appears as pins on the map
- [ ] What happens when you click on a pin? 

---

Arseni has produced two examples that we could do in Drupal. 
- http://bgs-dev.mrmdev.co.uk/custom-google-map
- http://bgs-dev.mrmdev.co.uk/map (not sure if we have budgeted for Cat to produce this graphic)

**Comment by angievanhegan** [comment]
Copied from SLACK

**Angie**:  I’m just going through our documentation and I can’t find any reference to the interactive map (for the research section) in the ITT or our proposal. I’ve asked Dave to send me the latest version of the contract. Steve suggested I contact Arseni to find out what we could do. Perhaps there’s time allocated for migration we could use on this? He also mentioned that when they’ve built maps like this in the past people have ended up abandoning them as users have preferred a list!


13 replies
Steph Slack [1 day ago] 
In the ITT there was a line under the functionality heading - Facility for creating, embedding and sharing interactive infographics/maps. This could be within the CMS or a plugin.


angie [1 day ago] 
That sounds to me like the iframe functionality you used for the map. That’s the facility for adding them.


angie
[1 day ago] 
I’m just talking to Arseni though to see what we could do.


Steph Slack [1 day ago] 
I wouldn’t really call embedding the google map interactive, and the hot spot graphics that were discussed yesterday also fell within this requirement. Let me know what Arseni has to say

angie
[1 day ago] 
The requirement seems to be asking for the ‘facility’ to incorporate these things, which we should definitely be able do (in the same way that you incorporated a Google map

angie [1 day ago] 
Look what Arseni has just sent me! http://bgs-dev.mrmdev.co.uk/map-0 (edited)

angie
[1 day ago] 
Do you think there’s some mileage in that? It looks good to me!

angie [1 day ago] 
Not least, because it’ll enable us to locate all the centres without creating a lot of design and content work.

Steph Slack [1 day ago] 
Hi Angie - I keep getting a page not found error

angie [1 day ago] 
hang on…

angie
[4 minutes ago] 
So, here’s two options. A google map with multiple points. Which is my favourite because it’s so clear, will be easy to maintain and not much work to setup (ideal if it doesn’t get much use!) http://bgs-dev.mrmdev.co.uk/custom-google-map

angie [3 minutes ago] 
second option, is this map. I’m not sure where it’s come from! I think it’s what you’re imagining, but it’s a lot more work to create and style this map to suit BGS then put the points on. It’s the creation of the graphic that I suspect is out of scope. http://bgs-dev.mrmdev.co.uk/map

angie
[3 minutes ago] 
Let me know what you think.

**Comment by angievanhegan** [comment]
@StephMSlack Let me know what you think of these two options.

**Comment by StephMSlack** [comment]
Thanks @angievanhegan I've sent this on to Recia for feedback and comments

**Comment by StephMSlack** [comment]
Hi @angievanhegan Recia is preferring the Google Map. I'll need to have a look at it in a bit more detail to make sure it will meet our needs (in terms of showing the correct information in the format requested). I shall look into this next week.

**Comment by angievanhegan** [comment]
Steph confirmed on Slack that the Google map will be fine.

**Comment by angievanhegan** [comment]
see #166
