### ISSUE TITLE
Resource series

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#102]
# Done criteria
- [x] **ISSUE 6** [Display card summary text on hover](http://bgs-dev.mrmdev.co.uk/resources/resource-series) (the same as the Resources, Policy & Media and Blog landing pages)
- [x] **ISSUE 5** Remove the right hand side download link from the [series page](http://bgs-dev.mrmdev.co.uk/angies-first-test-series) and the [series landing page](http://bgs-dev.mrmdev.co.uk/series-landing-page) so that the content is full width and the box links are the same width as on the resource page
- [x] **ISSUE 4**: Promo not appearing
- [x] **ISSUE 3**: @meldera Add a file field for resource series
- [x] **ISSUE 2**: @meldera There's two links to download the series file
- [x] **ISSUE 1**: @pipe-manta to style the [series page](http://bgs-dev.mrmdev.co.uk/angies-first-test-series) and the [series landing page](http://bgs-dev.mrmdev.co.uk/series-landing-page) page so that the resources appear as cards (like the search results page)
- [x] The resource series has it's own page (full width) which can also show a promo
- [x] Resource series landing page to show all series (full width) 
  - [x] which can also show a promo
  - [x] includes intro text at the top (which can include heading and link text)
- [x] A set of resources can be connected as a series (they may be from the same publication or may be linked by a campaign theme)
- [x] Resources that are in a series should be labelled when they appear in the search results page (the label should not appear when the card is displayed in the 'other resources in this series nugget' is displayed on the resource page)
- [x] If a user is viewing a resource that is part of a series, then the 'other resources in this series' appears on the resource page (and the 'related links' nugget does not appear)
- [x] The 'see all resources in this series' link on the resource page shows a search results page showing only the resources in this series

# Designs & Drupal links
- Wireframes on RT board: https://realtimeboard.com/app/board/o9J_k0NkHnc=/?moveToWidget=3074457345944839528
- Design: https://invis.io/DQEPLPAY4
- Drupal - [series](http://bgs-dev.mrmdev.co.uk/angies-first-test-series)
- Drupal - [series landing page](http://bgs-dev.mrmdev.co.uk/series-landing-page)

**Comment by meldera** [comment]
Current wireframes do not take into account the fact that nothing prevents a resource to be assigned to multiple series. Nor does a series filter exist on the resources search page, so the bottom link that "shows a search results page showing only the resources in this series" is invalid.

**Comment by angievanhegan** [comment]
@russ-manta what do we do here? A resource can only be in one series, but that's not enough to solve this problem. Thanks

**Comment by russ-manta** [comment]
@meldera can we add a resource series filter to the resources search page that enables us to filter resources by a series?  Apparently resources will only ever be a part of one series - can we restrict the ability to add resources to more than 1 series?

**Comment by meldera** [comment]
@russ if, as previously agreed, there is not need to have a series page/node, this might as well be a term instead.

**Comment by russ-manta** [comment]
@meldera BGS have confirmed that they do want a resource series node with all related resources shown and also some kind of resource series landing page which lists all resource series.  Awaiting for @angievanhegan to provide a wireframe for these pages still I think

**Comment by angievanhegan** [comment]
@meldera @russ-manta there are two wireframes on the realtime board, both have been approved by Steph:

- Resource series landing page
- Resource series node page

(thanks for the nudge to make the wireframes - we got some useful detail out of it)

**Comment by angievanhegan** [comment]
@meldera Can you add a link to the top where I can see this? I think I may have deleted your example.

**Comment by angievanhegan** [comment]
@meldera 

1. How do I add the link to the PDF doc which has all the files in the series?
2. How do I see the page that lists all the series? Can you add a link to the navigation please?

Also, there are some issues listed above. Thanks very much.

**Comment by meldera** [comment]
@angievanhegan do we generate a cover image for uploaded series pdf?

**Comment by angievanhegan** [comment]
@meldera no, there's no cover image for the series page.

**Comment by StephMSlack** [comment]
@ican-icant - the box links for the series and related resources links and on the series landing page are all smaller than those on the resource landing page. It makes it harder for the user to read the card content. Should they all be the same size?

**Comment by dilwarhussain** [comment]
@StephMSlack Are the boxes for related and series links the correct size now? I think fixing ISSUE 5 may have fixed this problem too.

http://bgs-dev.mrmdev.co.uk/resource-0
http://bgs-dev.mrmdev.co.uk/series

**Comment by angievanhegan** [comment]
@StephMSlack this is ready for you to review.

**Comment by StephMSlack** [comment]
@angievanhegan @dilwarhussain I'm still seeing different size boxes on the series landing page and then the series page. Might be linked to the work being done at the moment though.
![screen shot 2018-02-22 at 14 35 18](https://user-images.githubusercontent.com/32127102/36544291-0d1b3f22-17de-11e8-981b-0af8446d4a10.png)
![screen shot 2018-02-22 at 14 35 06](https://user-images.githubusercontent.com/32127102/36544307-14fce9e8-17de-11e8-9de8-365daae52cd9.png)

**Comment by angievanhegan** [comment]
@StephMSlack the resource series landing page is using the standard size for those images for that type of layout. The resources cards on the series page are the same size as the landing page now.

**Comment by StephMSlack** [comment]
@angievanhegan the card content is now visible on the series landing page - is it supposed to be this way? The impact is that the cards are now all different sizes
![screen shot 2018-03-08 at 16 05 31](https://user-images.githubusercontent.com/32127102/37161439-99bf04e2-22ea-11e8-9f8d-45ebc9a9b303.png)

**Comment by angievanhegan** [comment]
@StephMSlack This is so easily solved! You just don't put any text into the card summary field! :D

**Comment by StephMSlack** [comment]
@angievanhegan -re: last comment - but we do want to tell people what the series is about, so card content is very helpful to have. Not sure why this page is working one way and the rest of the site differently?

**Comment by angievanhegan** [comment]
@dilwarhussain See issue 6 about displaying summary text on hover.

**Comment by pipe-manta** [comment]
@angievanhegan Issue 6 done

**Comment by angievanhegan** [comment]
@StephMSlack This is ready for you to sign off now.

**Comment by angievanhegan** [comment]
@StephMSlack  you just need to check issue 6

**Comment by StephMSlack** [comment]
@angievanhegan @dilwarhussain thanks for the change, signed off.
