### ISSUE TITLE
Tags/topics on resource page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#104]
# Done criteria
- [x] Resources can be tagged with any topic from the taxonomy (none, one or many)
- [x] When a resource is tagged as being in a topic, a link to that topic appears on the resource page (see design)
- [x] ISSUE: When a user clicks the link to a topic, the search results page is displayed showing all the resources tagged with that topic (not sure how they should be sorted)
- [x] ISSUE: the tags I select are replaced with 'yet another tag' and 'another tag' when I press save. These tags don't exist anymore as I've renamed them. NOTE - Issue still occurring 05/02/18
- [x] ISSUE: We may need to amend the styling so that each topic appears more distinct (they appear to run into each other. 
- [x] ISSUE: When an author is not included on the page, the topics should move left but the date published & date updated should both still stay on the next line down
- [x] **ISSUE**: Author field should be mandatory and topics field should appear on the right hand side

# Designs & Drupal links
- Design: https://invis.io/DQEPLPAY4
- Drupal: http://bgs-dev.mrmdev.co.uk/peri-operative-care-for-older-patients-undergoing-surgery

Structure > Taxonomy > Topics

**Comment by angievanhegan** [comment]
@cat-manta @ican-icant Have a look at the Drupal page to see how it appear when there are a few topics listed together. I'm not sure it's really clear they're all different tags, it just looks like a messed up sentence to me. Issue added at the top.

@russ-manta @meldera I've added some proper topics (I renamed the test one), but when I save it deletes them and adds the old test ones. Also, when I click on the tag, I see the search page, but I don't get any results. I should at least see the resource page I've just come from, right? Issues highlighted/added above

Thanks

**Comment by meldera** [comment]
New revisions need to be published for changes to be applied to the current page.

**Comment by angievanhegan** [comment]
@meldera I had published them. Most worked, the ones I mentioned don't.

**Comment by cat-manta** [comment]
@angievanhegan I've added underlines to each topic, do you think this makes enough difference?

**Comment by angievanhegan** [comment]
@cat-manta It works for me. Do you think it's ok that some links are underlined and others aren't? Also, did you get @ican-icant to have a quick look? Thanks

**Comment by ican-icant** [comment]
@angievanhegan @cat-manta Loving the tags but think we need a little more space at the top of the page. Have added my thoughts to the design. Very minor additions to excellent workings.

**Comment by angievanhegan** [comment]
@ican-icant I love the tags too. The question here though was about the topics! In the first version, they were just link text (with no underline) but I was worried they just looked like an odd sentence and not like separate things. @cat-manta put the underline on them to make them each look more distinct. Do you think that's working? What should we do? Thanks.

**Comment by angievanhegan** [comment]
@cat-manta Steve things we should lose the underline on the topics. Also, he put a request to add some more space in in Invision. Thanks

**Comment by cat-manta** [comment]
@angievanhegan Done both of those.

**Comment by StephMSlack** [comment]
@angievanhegan @ican-icant 
The tag "deconditioning" changes to "another tag" when used.
What is the default view when an author is not included on the page. The topics should move left but the date published & date updated should both still stay on the next line down 
![screen shot 2018-02-05 at 15 03 53](https://user-images.githubusercontent.com/32127102/35811214-d33ad4e4-0a85-11e8-8f2e-8dc29ecbe023.png)

**Comment by pipe-manta** [comment]
Hi @StephMSlack , I have fixed both issues with the Deconditioning and the dates position, now both are displaying always in the same line.

**Comment by StephMSlack** [comment]
Thanks @pipe-manta I've edited the dysphasia tag (changed from lowercase to upper case D) in structure/taxonomy/topics but the change has not been reflected on the resource page.

![screen shot 2018-02-14 at 12 33 29](https://user-images.githubusercontent.com/32127102/36205038-3df64588-1185-11e8-8200-f036a8ffc884.png)
![screen shot 2018-02-14 at 12 35 28](https://user-images.githubusercontent.com/32127102/36205047-43e7603a-1185-11e8-8c28-90e17bee08be.png)

**Comment by angievanhegan** [comment]
@pipe-manta I've added another issue to the done criteria. Topics should always appear on the right and author should be mandatory. Thanks

**Comment by pipe-manta** [comment]
@angievanhegan Authors are already required, that mean that when they include the information Topic will be displayed on the right

**Comment by angievanhegan** [comment]
@pipe-manta Can you make it a mandatory field in Drupal please so that they have to add at least one? Thanks

**Comment by pipe-manta** [comment]
@angievanhegan The Authors field is mandatory, you can't save any resource without an author  

![image.png](https://images.zenhubusercontent.com/59ef62dca468affe6df7f840/1860a8a7-9bbf-44c8-968c-28f56c9e74ef)

**Comment by angievanhegan** [comment]
@pipe-manta did you just add this or was it there before? There were published pages without authors - honestly! I'll put this over for sign off. Thanks

**Comment by angievanhegan** [comment]
@StephMSlack Are you happy to sign this one off?

**Comment by StephMSlack** [comment]
@pipe-manta @angievanhegan - re: authors being mandatory, I do not seem to have access to the full functionality, as I cannot add a new author. All I can do is add an existing author (different to Pipe's screen shot above) Could this be updated please?
Screen shot in the resource page
![screen shot 2018-02-28 at 10 33 25](https://user-images.githubusercontent.com/32127102/36783094-ee471104-1c72-11e8-918f-3f5e1a678e56.png)
screen shot of the author page
![screen shot 2018-02-28 at 10 34 32](https://user-images.githubusercontent.com/32127102/36783148-1633f2e0-1c73-11e8-9ef2-8d3cbe3c8e29.png)

**Comment by pipe-manta** [comment]
Hi @StephMSlack this has been fixed, you are able now to add new and existing authors.

**Comment by StephMSlack** [comment]
thanks @pipe-manta

**Comment by StephMSlack** [comment]
@angievanhegan is there anyway that for topics you can only choose from the topics taxonomy? I just added new topics in the content page which ended up replicating one topic and creating another (with a spelling mistake :) ) 

I think it might be wise to lock things down a little so people don't accidentally add new topics or replicate them as I assume these are the fields we are using for the topics mega menu? Which could become very messy if people can accidentally add topics within the page.

What would your thoughts be?
<img width="964" alt="screen shot 2018-03-01 at 21 04 24" src="https://user-images.githubusercontent.com/32127102/36869650-698ee342-1d94-11e8-814f-9633f6cc5059.png">

**Comment by angievanhegan** [comment]
@meldera At the moment, people can add a topic by adding a word into the 'topics' field on the content page. Are we able to prevent people from doing this and make sure they can only be added via Structure > Taxonomy > Topics in the Drupal Nav? Thanks

**Comment by angievanhegan** [comment]
@meldera that isn't a good solution as there's going to be a hundred or so topics.

**Comment by angievanhegan** [comment]
@meldera That is perfect. Thanks. Can you confirm the places it's been added, or do you need me to list where it needs to go?

**Comment by meldera** [comment]
Added everywhere.

**Comment by angievanhegan** [comment]
@StephMSlack This is ready for you to sign off.

**Comment by StephMSlack** [comment]
@angievanhegan - this is now working & good to go. 
Re:  "ISSUE: When a user clicks the link to a topic, the search results page is displayed showing all the resources tagged with that topic (not sure how they should be sorted)" they should default sort to the most recently published.

**Comment by angievanhegan** [comment]
@StephMSlack I just tried to log the issue and tested it to confirm and it seems to already do what you want already. See POPS for example

http://bgs-dev.mrmdev.co.uk/resources?tag=788
