### ISSUE TITLE
Capture email address for users requesting specific resources

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#107]
# Done criteria
- [x] **ISSUE 9** Opening in two tabs (see comment below)
- [x] **ISSUE 8** Update header text: Header text - Please help us evaluate this resource
Text below - If you are happy to be contacted for feedback on this resource, probably in 6-12 months' time, please submit your name and email address.
- [x] **BLOCKER** Steph to send text to update the form with 
- [x] **ISSUE 7** Once you have submitted your email, you see thank you and then have the option to go back to the form - could this option close the form instead? Otherwise people may submit multiple times
- [x] **ISSUE 6** Could the download open in a new tab
- [x] **ISSUE 5** Confirm that this information is being emailed to s.slack@bgs.org.uk so that we can check it's received (new issue created for this)
- [x] **ISSUE 4** This should work whether or not users are logged in or not
- [x] **ISSUE 3** Needs styling
- [x] **ISSUE 2** Needs text adding so that it makes sense for the user!
- [x] **ISSUE 1** Submit the information as an email to an address to be provided by @StephMSlack 
- [x] Enable the editor to select this option for specific resources
- [x] This alert appears when the user clicks to downloads the resource file from the right hand nugget
- [x] Enable user to enter their email address (or not) - not mandatory to complete the form to download the file
- [x] Validate email to check it's correctly formed - use a webfomr block for this?

![screen shot 2017-12-15 at 12 08 26](https://user-images.githubusercontent.com/3796718/34052508-b7bf9ccc-e190-11e7-949e-4bda93821393.png)

  # Designs and Drupal links
- no design needed
- Drupal link: http://bgs-dev.mrmdev.co.uk/resource-0 (Need to be logged out, then click on the download resource link on the right hand side)

**Comment by angievanhegan** [comment]
@russ-manta Please can you estimate this before we confirm if it's in scope or not. Thanks

**Comment by meldera** [comment]
Should this be a modal form dialog or appear in the sidebar?

**Comment by angievanhegan** [comment]
@meldera I'd say whichever is easier to build (as either would be fine). @russ-manta Do you agree?

**Comment by angievanhegan** [comment]
@meldera I need to know how to add a download to the right hand side so that I can test this. Can you add one please so I can see. http://bgs-dev.mrmdev.co.uk/resource

**Comment by angievanhegan** [comment]
@meldera I'm checking it on this page but it doesn't appear to be happening: 
http://bgs-dev.mrmdev.co.uk/boxni

**Comment by angievanhegan** [comment]
@pipe-manta Arseni has built this, please can you style it? Obviously, it shouldn't be full width, it should just appear more like a window with very minimal formatting. It also needs to have the text as shown in the screen grab at the top. Thank you!

**Comment by ican-icant** [comment]
There's nothing I can test @pipe-manta

**Comment by dilwarhussain** [comment]
@ican-icant Here's the link: http://bgs-dev.mrmdev.co.uk/resource-0 
You need to be logged out for the popup box to work.

**Comment by angievanhegan** [comment]
@StephMSlack Are you happy to sign this off? It looks like this: 

<img width="873" alt="screen shot 2018-02-20 at 08 29 59" src="https://user-images.githubusercontent.com/3796718/36429458-65451a46-1618-11e8-87e2-07c3da65258f.png">

**Comment by StephMSlack** [comment]
Hi @angievanhegan - Reading the text above, you need to be logged out to see this pop-up. Including this function is to help us when evaluating the resource. Is there a way to track users who are logged in who also download this resource?

**Comment by angievanhegan** [comment]
@StephMSlack Sorry, communication mix up - I've added issue 4 above to request that this functionality works whether or not people are logged in. 

Also, did you test the form and receive an email. ?

**Comment by angievanhegan** [comment]
@StephMSlack This is ready for you to sign off now.

**Comment by StephMSlack** [comment]
@angievanhegan I was looking at this and now I cannot seem to get it working (whether logged in or logged out)

**Comment by StephMSlack** [comment]
@angievanhegan also, I did add my email address and press send, but no email has arrived (not sure where it was set to go though!)

**Comment by angievanhegan** [comment]
@meldera The requirement was for the information in this form to be emailed. See issue 5 above to confirm the email address. Thanks

**Comment by dilwarhussain** [comment]
@angievanhegan I've added your email address as the destination for the emails. If you're having trouble seeing the popup again try using incognito mode on browser.

**Comment by StephMSlack** [comment]
@angievanhegan 
should it grab your email automatically if you are logged in? 
could I update the thank you message?
once the user has entered their email (or not) the download opens in the current tab - could it open in a new tab?
destination emails - not sure how long they should take to come through, but at this point they don't seem to be arriving
Once you have submitted your email, you see thank you and then have the option to go back to the form - could this option close the form instead? Otherwise people may submit multiple times
<img width="748" alt="screen shot 2018-03-01 at 23 09 53" src="https://user-images.githubusercontent.com/32127102/36875305-5d077dd8-1da7-11e8-955e-e66403875971.png">
I'm getting an error message post form submission

**Comment by angievanhegan** [comment]
@StephMSlack 

1. Can we let people provide their own email? Just to keep it simple
2. Please can you provide new thank you text?

**Comment by StephMSlack** [comment]
@angievanhegan Colin would like a small text change. I've managed to change the title, but need to update the text below. Can you/one of the devs show me how?
Yes, can provide own email
Have updated the thank you text in the form.
Just need the other issues resolved now (5-7)

**Comment by angievanhegan** [comment]
@dilwarhussain There's still some outstanding issues for this one. Thanks

**Comment by dilwarhussain** [comment]
Hey @StephMSlack 
ISSUE 5 - I'll need @russ-manta to see if you can receive the emails while the site is in development.
ISSUE 6 - Downloads are opening in a new tab now
ISSUE 7 - I’ve removed the back to form button and placed a close button in its place
ISSUE 8 - The text above the form is embedded in a template, this means we need to make and text changes for this particular text, if you could send what you’d like changed I can get that done for you. thanks.

**Comment by angievanhegan** [comment]
@StephMSlack Can you send over the text for the form please? Thanks

**Comment by StephMSlack** [comment]
@angievanhegan sorry for the delay
Header text - Please help us evaluate this resource
Text below - If you are happy to be contacted for feedback on this resource, probably in 6-12 months' time, please submit your name and email address.

**Comment by angievanhegan** [comment]
@dilwarhussain Please see issue 8.

**Comment by dilwarhussain** [comment]
@StephMSlack I've changed the text for the form 👍

**Comment by StephMSlack** [comment]
thanks @dilwarhussain 
@angievanhegan this is good to go

**Comment by StephMSlack** [comment]
@dilwarhussain the PDF is opening in a new tab, but it is also opening in the same tab (so it is open twice). Is there anyway to stop this happening?

**Comment by StephMSlack** [comment]
thanks @dilwarhussain @meldera
