### ISSUE TITLE
Design my account page 

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#112]
# Done criteria for Manta Ray and BGS
- [x] **ISSUE 5**: Move Age and Ageing RHS to above BGS groups and add an image
- [x] **ISSUE 4**: Create a version of the design without the members directory(
- [x] **ISSUE 3** try reducing the size of the person image
- [x] **ISSUE 2** try putting the BGS groups underneath the biog in three columns, instead of on the rhs. 
- [x] **ISSUE 1** Add a show more button to the biog so that only two lines are showing
- [x] Members info area for the top of the page (which looks ok with 'blank' for image and biog)
- [ ] Members area design works on member page too
- [x] My membership (right hand nugget)
- [x] My BGS groups
- [x] Member alerts
- [x] Members directory
- [x] Events

# Wireframes and Designs
- [Wireframe on the RT board](https://realtimeboard.com/app/board/o9J_k0NkHnc=/?moveToWidget=3074457345962285201)
- [Design with events ](https://invis.io/RMFLIHCTECD) 
- [Design with membership directory](https://invis.io/WSFH05EPFA6)

**Comment by angievanhegan** [comment]
@cat-manta @ican-icant now that I look at it, I'm not sure about having so much content for the members directory and the events at the bottom of the page. It's not actually 'your' information. Do you think it'd be be better if we reduced these two items to something much simpler?

**Comment by cat-manta** [comment]
@angievanhegan I have updated this page with the membership promo.
I think I agree about simplifying the page as well, what do you think about getting rid of Age and Ageing on the RHS?

**Comment by angievanhegan** [comment]
@cat-manta Age and Ageing is a a key part of the membership. People pay extra for it, so it needs to be there.

**Comment by angievanhegan** [comment]
@cat-manta I think the events and members areas should probably be on a white background though.

**Comment by angievanhegan** [comment]
@StephMSlack This is now ready for you to review. Cat and I think that the members and event content is making the page looks very busy, and it's not completely content that relates to you. I think we're recommending we remove this. Your call.

**Comment by StephMSlack** [comment]
@cat-manta @angievanhegan could we move the Age & Ageing RHS nugget above the BGS Groups. It is a major membership benefit so we do want people to use this. Ideally it should also have an image to ensure people see it.

My events & Certificates, whilst in pink seems to get lost. Could we be showing any upcoming event (if they have registered) or the most recent event they attended? 

I know the page is very busy, but I am also concerned that we are in danger of the RHS column being a lot longer than the body - especially if people do not complete a biography. Would it be worth adding the events attended/registered to the main body above the recommended events?

Steph

**Comment by angievanhegan** [comment]
@cat-manta I've distilled this down to issues at the top. Thanks

**Comment by cat-manta** [comment]
@angievanhegan Have updated the original design, and added a new design without the members' directory

**Comment by angievanhegan** [comment]
@StephMSlack This is ready for you to review (see the links at the top). What would you think about having 2 promos (one for age and ageing and one for membership)? or, removing the BGS groups summary on the RHS?

**Comment by StephMSlack** [comment]
Hi @angievanhegan @cat-manta 
Feedback from Geraint referencing both sample pages:
The biography has too much emphasis. 
As this is the users account landing page, they don't need to see the entirety of their biography every time they login. They just need to be reminded that they can add one and that they can edit their current one. 
The image seems very large

The priority for this page is that:
- users can see a quick overview of the information we have on our systems
- Members can see their membership information & are prompted to renew if required
- non-members are prompted to join 
- all users can see the events they have registered for/attended
- members can SSO to A&A
- members can see the membership directory

Steph

**Comment by StephMSlack** [comment]
@cat-manta @angievanhegan 
RE: events on the page, greater emphasis needs to be on the events people have registered for. This information is lost on the page.

**Comment by StephMSlack** [comment]
@angievanhegan re: 2 promos, Non-members should have a membership promo and members can have a A&A promo. Just concerned that for members the promos tend to sit at the bottom of the page and we want them to easily access A&A as it is one of their main benefits so replacing the RHS link might mean that they miss the option.
re: removing BGS groups - both members and non-members can be part of a SIG, so its useful to have on this page. It doesn't need to be a RHS nugget, it could be in the main body instead.

**Comment by angievanhegan** [comment]
There's lots to sort through here! 


1. Do you want just a couple of lines of the biog with an elipsis? I think if we don't add a note on specifically how to edit it it might be a bit annoying. And if we add a button to edit it, it'd be more clutter. What do you want us to do?
2. We can try reducing the image size
3. I don't think this is necessarily the best place to show people the events they have registered for, as then we get into the realms of all the extra content on the my events and CPD points page. I think it's better to have all that information together, rather than divide it over two pages. And it'd be too much to put it all here. I think this page was trying to get people to be aware of other events they may not know about, but there's so much going on here. I recommend that we remove them from this page. In trying to make the page do so much, I think we'll achieve less. Perhaps we remove all the box links with the events and instead try to do more to highlight the link to the 'my events and CPD point's page. 
3. I take your points about the promo at the bottom of the page, but the page already has to provide a lot of information before it tries to get them to do something they didn't know they wanted. Let's go with this option of different promos for different audiences. Also, surely people who want to access age and ageing are much more likely to go to the age and ageing site anyway?

**Comment by cat-manta** [comment]
@StephMSlack I have updated the design that doesn't have the members directory to reflect the changes asked for.

**Comment by cat-manta** [comment]
@StephMSlack I have updated the design again, moving the 'manage my account' and 'my events & certificates' buttons to the top of the column.

**Comment by StephMSlack** [comment]
thanks @cat-manta I really like that. I have a meeting with my web group tomorrow so should hopefully be able to sign this off then

**Comment by angievanhegan** [comment]
@cat-manta the design with all the latest changes look great.  

Please can you just do a version of this page with the members directory in it instead of the events (and delete any old versions in invision)? 

Thanks

**Comment by angievanhegan** [comment]
@StephMSlack Things for you to decide:

1. Are you happy to have the BGS groups under the member's alert? I think it's better here
2. Is the 'show more' ok for the biog 
3. Is the picture size ok?

[FOR MEMBERS](https://invis.io/WSFH05EPFA6)
4. Are you happy to have the Age and Ageing link on the right hand side? It makes the right hand column longer, but If you keep it on the right, you can have a promo for something else (or nothing) at the bottom.
5. Are you happy to just have the members directory on here (and not the related events) to keep the page to a manageable size so that people don't get overloaded with information. 

[FOR NON-MEMBERS](https://invis.io/RMFLIHCTECD) 
6. Are you happy to just have the related events here?

**Comment by StephMSlack** [comment]
@angievanhegan Sorry, I missed this last week.
1) yes happy with groups under member alert (though for some people this may be quite sparse). This should show when we members and site registrants who are a member of a SIG are logged in. It shouldn't show for anyone else
2) show more is fine for bio
3) picture size is better
4) A&A is fine on the RHS - this should only be visible for members who have permission to view the journal. 
5) We need to have related events on the members page - they are our main event attendees so need to know about events as well. 
6) related events should show on the non-member page 

Also, to add promos to this page, can we make them conditional? Ie show a join the BGS for non-members and a different one for members?

**Comment by angievanhegan** [comment]
@StephMSlack 

4. Wouldn't it be worth keeping the link to A&A as a trigger to people who don't have it? The link will prompt them to log in anyway
5. If you're not worried that the directory and events together will overwhelm the page?
6. I suspect this may be quite a bit of work but I'll ask
6.

**Comment by StephMSlack** [comment]
@angievanhegan 
4 - OK
5 - we don't have a version with both, so its hard to tell if it will be overwhelming. But from a business point of view, we need members to be reminded to book on events, so at this point, yes they need to be there.
6 - this can just be a listing of events - but wouldnt it be the same function as what is on the members page? Or it could default to showing the next 4 events we are running or something like that. 
Or for 6 did you mean the promo query?

**Comment by angievanhegan** [comment]
@StephMSlack I don't think we should create another design for the events cards. Let's go with it all as is and see how it works when people start using it.
