### ISSUE TITLE
Design members directory page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#113]
# Done criteria
- [x] Search area
- [x] Results icons
- [x] Pagination

# Wireframes and Designs
- [Wireframe on the RT board](https://realtimeboard.com/app/board/o9J_k0NkHnc=/?moveToWidget=3074457345962285201)
- [Design in invison](link here)

**Comment by cat-manta** [comment]
@angievanhegan I don't think this page needs designing anymore, as everything has already been designed on the Resources page (apart from the reset button). What do you think?

**Comment by angievanhegan** [comment]
@cat-manta I agree.
