### ISSUE TITLE
Design manage my account page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#114]
NOTE: Would like to group into FAQ style concertinas if possible

# Done criteria
- [x] Design for table (with very minimal formatting)
- [x] 'appear in members directory' link

# Wireframes and Designs
- [Wireframe on the RT board](https://realtimeboard.com/app/board/o9J_k0NkHnc=/?moveToWidget=3074457345962285201)
- [Design in invison](https://invis.io/4EDQ458R5#/274219385_Manage-My-Account)

**Comment by angievanhegan** [comment]
@cat-manta I love the style of this. Some comments:

1. The membership details in the fields at the top are not editable. Please can you make sure the design shows that?
2. I think that people should be able to to control whether or not they're going to appear in the members directory from here. Please can you add that in where you think it fits best? Please can you remove the option to to this from the 'My account' page - it makes more sense to make all those changes from here. 

Thanks

**Comment by cat-manta** [comment]
@angievanhegan Done both of these. I've also added titles to separate the forms into sections, which I think helps, and changed the heading style of the textbox titles.

**Comment by angievanhegan** [comment]
@cat-manta. I really like the pink lines and the non editable text at the top. 

I think that having the 'apear in members directory' on the blue bit makes it look like your membership details are going to be displayed in the directory (rather than your person details - listed below). Perhaps we should move this down?

Other than that, all good! Ta

**Comment by cat-manta** [comment]
@angievanhegan Have moved this down, do you think it makes sense just above personal information? I've also edited the design a bit, right aligning the titles of the text boxes, and moving these titles and textboxes more to the left.

**Comment by angievanhegan** [comment]
@cat-manta I really like this page. I think the location of the 'be in the directory' checkbox works well here. Thank you!

**Comment by angievanhegan** [comment]
@StephMSlack Are you happy with this design? Thanks

**Comment by StephMSlack** [comment]
@angievanhegan @cat-manta this is looking great. My concern is that the page is very long, and people wont necessarily scroll all the way down to the bottom. Would it work to add accordions/FAQ nugget styling - one for each heading? 
- Personal information
- career information
- contact details (include Social media in this)
- interests (I need to check, but this may be a pre-populated list linking to Civi and in the interests of consistent data I'd prefer it not to be a free text field)
- My BGS groups (Member focused groups and regions cannot be edited, so should they be in a blue field as above - not sure how this would look though)
- Keeping up to date.

We may need to re-order the fields. I need to double check, but with GDPR coming in we may need to make communications preferences more prominent and have them sitting under contact details.

**Comment by angievanhegan** [comment]
@russ-manta How much work will it be to add the FAQ layout to this page?

**Comment by angievanhegan** [comment]
@StephMSlack The reason the design is so simple is that this one is supposed to be on Veda's list to do. If we end up building it then we'll see if we can add them. It will add more time. I just noticed that the Airbnb update your details page is very similar, and if it's good enough for them...!

**Comment by StephMSlack** [comment]
@angievanhegan @cat-manta - the design doesn't seem to use the full width of the page. Could it? And possibly then use 2 columns of data to shorten the page?

**Comment by cat-manta** [comment]
@StephMSlack @angievanhegan There seemed to be far too much space when it was full width with one textbox on each line. I have quickly done another version with some boxes on the right which makes the page a fair bit shorter, however there are a few different ways the content could be laid out to make the page shorter.

https://invis.io/4EDQ458R5#/276292235_Manage-My-Account-V0-2

**Comment by StephMSlack** [comment]
Thanks @cat-manta I definitely prefer the shorter version. 
@angievanhegan I have realised that we are missing some information on this page - some extra fields within a couple of sections. I'm not sure if you will need to update the designs to ensure the devs know what fields to use? 
Missing fields:
- update password
- address information (street, city, postcode, country)
- membership information - this is the info users can edit (Are you Retired? Are you currently on maternity leave? Are you working or training Less Than Full Time?)

I've attached the current display on the myBGS page using CiviForms as well 
[Sample user update page CiviCRM.pdf](https://github.com/MantaRayMedia/bgs/files/1678318/Sample.user.update.page.CiviCRM.pdf)

**Comment by angievanhegan** [comment]
@StephMSlack Yes, I noticed I'd missed those things off too! I'd made notes on the RT board and will transfer them all to GitHub when I'm creating the build tasks. 

Are you happy to sign this off now? Thanks

**Comment by StephMSlack** [comment]
@angievanhegan just getting final sign-off from the web group. Have stressed the need for speed!

**Comment by StephMSlack** [comment]
@angievanhegan Sorry, I'd ticked the boxes but not written anything. Yes, good to go
