### ISSUE TITLE
Archive BGS Active Collab project

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#12]
- [x] Check Cat's ok with it

So that people don't put stuff in the wrong place accidentally, please can you either archive this AC project, or remove edit rights and add a note directing people to:

What goes where? (on the Realtime board)
https://realtimeboard.com/app/board/o9J_k0NkHnc=/?moveToWidget=3074457345903003498

Thanks

**Comment by angievanhegan** [comment]
@dave-manta Would you mind archiving the AC project for BGS so that people don't use it accidentally? Thanks

**Comment by angievanhegan** [comment]
@cat-manta Are you ok with having no AC for this project? If you are, can you tick the box above and move this task into 'Done this sprint'. Thanks

**Comment by cat-manta** [comment]
@angievanhegan Yep that's fine!
