### ISSUE TITLE
Login page

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/bgs#121]
# Done criteria
- [ ] ~Build login page with all relevant fields & buttons~
- [ ] ~Style login page to match design~
- [ ] ~Login functionality works and are redirected to My account page after login~
- [ ] ~Link login button (in header) to login page~
- [x] Test request new password, create an account, become a member buttons 

# Designs & Docs
- see wireframes

**Comment by dilwarhussain** [comment]
@russ-manta "Test request new password, create an account, become a member buttons" - Does this need to be done anymore. I think these were just in the old versions of the design?

**Comment by russ-manta** [comment]
@StephMSlack here is the URL to the login page to check: http://bgs-dev.mrmdev.co.uk/user

**Comment by angievanhegan** [comment]
This is a dupe of #136
