### ISSUE TITLE
Member alert (my account page)

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#122]
# Done criteria for BGS and Manta Ray

- [x] TWEAK Member alert giving error message
- [ ] ~TWEAK - message can be everyone on Civi or members only (people with a BGS membership)~
- [x] Web admin can add a small amount of text (roughly 1 para)
- [x] Web admin can add a link to the text (may be a link to another page on the site)

# Drupal link
-

**Comment by StephMSlack** [comment]
@angievanhegan - I'll need to speak to Geraint about this one, as he requested the feature. Will confirm

**Comment by angievanhegan** [comment]
@StephMSlack Can you confirm you're happy with this done criteria? Thanks

**Comment by dilwarhussain** [comment]
@StephMSlack As web admin you now have the ability to edit user accounts and change the member alert field for users. List of users here: http://bgs-dev.mrmdev.co.uk/admin/people
So you can edit this per user or you can use the 'Operations' dropdown on the People page to update multiple user accounts at once. Do this by selecting/filtering and then selecting the user accounts with checkboxes then choose 'Change value' from the dropdown and click 'Execute'. You then choose the 'Member alert' checkbox and enter the new alert.

**Comment by StephMSlack** [comment]
thanks @dilwarhussain I also need to use this function to add an alert to the my account page of all BGS members within Civi and ideally (if this is not additional work out of scope) differentiate between member roles (eg create an alert that only shows on the my account pages of members who are in Category A with journal). Does that make sense?

**Comment by angievanhegan** [comment]
@StephMSlack That's definitely out of scope. Sorry. Do you want me to get a quote for doing that? And, can this one be signed off?

**Comment by angievanhegan** [comment]
@dilwarhussain We're discussed this with Steph and we think the tweak listed above is the simplest solution that meets their needs. Let me know if this is more than an hours work. Thanks

**Comment by dilwarhussain** [comment]
@StephMSlack As a web admin you can now filter users for roles here: http://bgs-staging.mrmdev2.co.uk/admin/people

Once users are filtered (for members/directory members etc) you can use the Operations dropdown to change value. Here you select the member alert field and put in what you would like the alert to say. This will change it for all the users selected.

**Comment by StephMSlack** [comment]
![screen shot 2018-07-03 at 13 52 17](https://user-images.githubusercontent.com/32127102/42220956-581efd00-7ec8-11e8-90f7-2187a8b46987.png)
 @dilwarhussain I just tried to add a member alert and received the above error message

**Comment by StephMSlack** [comment]
@dilwarhussain also - this way of adding an alert doesn't include a title for the alert (as it does in the SIGS). is it possible to include a title?

**Comment by angievanhegan** [comment]
@russ-manta One for you. I've added a tweak above.

**Comment by russ-manta** [comment]
@StephMSlack this should work now - let me know if not

**Comment by russ-manta** [comment]
@StephMSlack same method as before:  http://bgs-staging.mrmdev2.co.uk/admin/people Once users are filtered (for members/directory members etc) you can use the Operations dropdown to change value. Here you select the member alert field and remove what you put in before. This will change it for all the users selected.

**Comment by StephMSlack** [comment]
@russ-manta it is coming up blank then I get an error on submission

![screen shot 2018-07-10 at 16 34 29](https://user-images.githubusercontent.com/32127102/42520814-299ae6c8-845f-11e8-80e3-fbcfe15650d2.png)

**Comment by russ-manta** [comment]
@StephMSlack which people/members were you trying to set this for?

**Comment by StephMSlack** [comment]
@russ-manta all active members in drupal
![screen shot 2018-07-11 at 11 34 24](https://user-images.githubusercontent.com/32127102/42566416-68f63ca6-84fe-11e8-89fe-9e0a947ec0b7.png)

**Comment by russ-manta** [comment]
@StephMSlack the error message problem should now be sorted. You won't see the previous message when doing this, it will just appear blank. That is normal. If you go and look at your profile edit page you should be able to see any previous message there: http://bgs-staging.mrmdev2.co.uk/user/259/edit

**Comment by StephMSlack** [comment]
OK thanks @russ-manta 
@angievanhegan this is fixed and good to close
