### ISSUE TITLE
My account page

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/bgs#123]
NOTE: Members directory is part of a future sprint goal and can be ignore for now

# Done criteria
- [ ] ~Summary/card details~
- [ ] ~Member alert space (see #122)~
- [ ] ~Membership promo block at bottom of page (only show to non members)~
- [ ] ~Style my account page~
- [ ] ~My BGS Groups (from Civi)~
- [ ] ~My Membership section (from Civi)~
   - [ ] ~Become a member button only if not a member already~
   - [ ] ~Renew membership button only visible when membership is due (may be Civi rules for this)~
- [x] My events and CPD points (from Civi) - My events lik needs to go to correct page
- [x] Age and Ageing block (single sign on link)
- [x] CPD points - custom data - field 26 - check 19251 user for cpd certificate

# Designs & Docs
- See #112
- [Link goes here](http://)

**Comment by angievanhegan** [comment]
@StephMSlack can you confirm whether or not we're going to have the events on this page, it feels like it already has a LOT of content on here. Thanks

**Comment by dilwarhussain** [comment]
@angievanhegan @russ-manta Not sure where 'BGS roles' are being pulled in from. Can't see anything on CIVI. Is this a new field on Drupal user maybe?

**Comment by russ-manta** [comment]
@daniellaveda this issue is for displaying CPD points and My events on pages linked form the user profile

**Comment by daniellaveda** [comment]
@russ-manta Im unclear on what the request is here?

**Comment by StephMSlack** [comment]
@russ-manta @angievanhegan Some things that I have noticed when working through the site

- the membership details profile should only show if you are a BGS member. It should not show for web account holders.

- Payment history - @russ-manta you enabled this, but I am only seeing it on my admin view, not when logged in as other users (who have made payments)

- My BGS Groups - Special interest groups - the list of groups you are a member of does not seem to be reliably updating after changes have been made in civi (ie if you have joined a new SIG it is showing in Civi but not on the web page)

- BGS Roles - is it possible to add the relationship 'member of' (and the relevant organisation they are related to) to this view?

**Comment by StephMSlack** [comment]
@russ-manta @angievanhegan This still has the following outstanding:

the membership details profile should only show if you are a BGS member. It should not show for web account holders.
enabling payment history for non-admin users

**Comment by dilwarhussain** [comment]
@StephMSlack The 'My details' tab should be hidden for non members now.

**Comment by StephMSlack** [comment]
thanks @dilwarhussain I have made a comment on #299. The change to showing the membership details tab can be added to live. 

Note: the RHS nugget below that in staging has somehow gone missing when moving the site to the live environment.

staging
![screen shot 2018-08-14 at 10 50 35](https://user-images.githubusercontent.com/32127102/44085449-84ddf62a-9fb1-11e8-8ca9-98ab302a5fc6.png)

live
![screen shot 2018-08-14 at 10 55 02](https://user-images.githubusercontent.com/32127102/44085461-8ca45ba6-9fb1-11e8-8a6b-37c7962ffcb3.png)

**Comment by StephMSlack** [comment]
@angievanhegan I can no-longer see the my membership details tab in staging. I cannot see any of the content of the profile tabs... but I think this might just be a staging issue...

**Comment by StephMSlack** [comment]
@russ-manta No - there was a mention of CPD points in the done criteria, but that should be showing on the My events and CPD page, not the my account page. Everything else is done
