### ISSUE TITLE
My Certificates and CPD points[BGS: P1]

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#127]
Need to see what Veda have built

- - -
**parents:**

1. https://trello.com/c/Y2JG3a8R

**Comment by angievanhegan** [comment]
@russ-manta Should this still be in the sprint backlog

**Comment by russ-manta** [comment]
@angievanhegan My events is covered under the My account card. I've renamed this card to My Certificates and CPD points and moved it to the backlog

**Comment by angievanhegan** [comment]
@russ-manta Has the CPD elements been setup/tested yet? Thanks

**Comment by russ-manta** [comment]
This is on the my events viewbut may be worth waiting until the final events card is done before reviewing

**Comment by StephMSlack** [comment]
@russ-manta would it be best to close this then and ensure it is reviewed again with #282?

**Comment by angievanhegan** [comment]
@conferences-BGS  can you add a comment here to explain why this is assigned back to Russ and me? Otherwise I'm not totally sure what to do with it. Thanks

**Comment by conferences-BGS** [comment]
@angievanhegan @russ-manta Not sure why my comment didn't save

Currently no CPD certificates are visible

**Comment by russ-manta** [comment]
await more testing from BGS

**Comment by conferences-BGS** [comment]
CPD and invoices available to view in test cases
Completed
