### ISSUE TITLE
Design My events and CPD points page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#128]
- [x] Search area
- [x] Event name
- [x] Event type
- [x] Past event (if appropriate)
- [x] Invoice/receipt links
- [x] 'Pay' button
- [x] Download certificate
- [x] View past event content

# Designs
- [Design](https://invis.io/4EDQ458R5#/275309606_My_Events)
- [Wireframes](https://realtimeboard.com/app/board/o9J_k0NkHnc=/?moveToWidget=3074457345962285201)

**Comment by cat-manta** [comment]
@angievanhegan I have added a link for this design.

**Comment by angievanhegan** [comment]
thanks @cat-manta - this totally works for me.

**Comment by StephMSlack** [comment]
Hi @angievanhegan @cat-manta I've sent the event pages off to Geraint and Julie (events team) for comment. I will be going through these as well and consolidate any comments and get back to you.
Steph

**Comment by StephMSlack** [comment]
@cat-manta Is there a reason this is only 3/4 of the page? Will we be able to add something to the RHS? It feels a little off centre.
Will the title of the event also be a link to the events page on the site? If not, do we need a way for users to see more about the event?

**Comment by cat-manta** [comment]
@StephMSlack It looks a bit odd full width, mainly because the CPD points and buttons are at the far right of the boxes, maybe instead we could have two events across rather than one?

They are basically the same as the event boxes on the Events page, so the titles will link to the event page.

**Comment by StephMSlack** [comment]
Thanks @cat-manta, yes, could we try 2 across. 

Also my colleague just pointed out that we might need a 'back to my account' button towards the top of the page content. Some of the users may not be as comfortable as others to follow the breadcrumb trail back or to use the MyAccount button at the top. What do you think? Will it be overkill to add this?

**Comment by cat-manta** [comment]
@StephMSlack I have updated the design with 2 across

I've added a more subtle link back to my account as I think a button would be too much, although I'm not sure that I like it, as it looks a bit odd saying 'My account' directly below the same link in the crumb, what do you think @angievanhegan ?

**Comment by StephMSlack** [comment]
thanks @cat-manta 
I like the 2 across
Agree that the my account link looks a little odd just below the crumb. They do have 2 options on the page to get back and they can use the back button, so let lose that (if angie agrees)

**Comment by angievanhegan** [comment]
@cat-manta @StephMSlack Yes - I agree! We already have a breadcrumb and a back button. I like this two column layout too. It was intentionally simple so that Veda can build it, but let's see what can be done. 

@StephMSlack Are you happy to tick the boxes and sign this off?

**Comment by StephMSlack** [comment]
Thanks @angievanhegan All signed off
