### ISSUE TITLE
Pagination on resource landing page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#129]
# Done criteria - Manta Ray and BGS
- [x] Numbers appear and work as expected
- [x] Navigation appears and works as expected

# Designs and Drupal links
- [Design in invision](https://invis.io/NAF7LMUMY)
- [Druapal page](http://bgs-dev.mrmdev.co.uk/resources)

**Comment by pipe-manta** [comment]
Hi @angievanhegan, I have changed the view to display just 1 item, that will helps to display the pager and test it. Let me know when you finish to revert the changes on the view and display again 12 items per pager.

**Comment by angievanhegan** [comment]
@pipe-manta I still see 6 results and no pagination :o(

**Comment by angievanhegan** [comment]
@pipe-manta Beautiful! Thanks
