### ISSUE TITLE
Agree where designs and wireframes will go

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#13]
- [x]  Invision
- [x] [Update RT board](https://realtimeboard.com/app/board/o9J_k0NkHnc=/?moveToWidget=3074457345903003498)

**Comment by angievanhegan** [comment]
@cat-manta Would it be ok for you if we put the designs and wireframes for this project into the Google Drive folders? It’d be great to use as few tools as possible. I’d like to avoid using the discussions in Invision and try to keep all detailed discussions in ZenHub so that all feedback and actions are in one place. What do you think?

**Comment by cat-manta** [comment]
I'm not sure we could use only Google Drive, as the devs use InVision to get information from the designs e.g. fonts, sizes, colours. Happy for feedback to stay in ZenHub though.

**Comment by angievanhegan** [comment]
@cat-manta I didn't know that! if your'e creating a style guide for the developers to use, won't they take the information from that?

**Comment by cat-manta** [comment]
@angievanhegan Yes but they can't get specific information from it, if you scroll down to 'A magical new design to development workflow' on [this page](https://www.invisionapp.com/) you can see the sort of information they can get from invision, which we couldn't do without invision unless I put all the information onto the designs, which would be **way** more work. There is now a plugin for Sketch to connect to Realtime Board though, so I could export the designs there as well for the BGS to see?

**Comment by angievanhegan** [comment]
@dave-manta @russ-manta @StephMSlack @cat-manta We're going to keep putting the wireframes in invision. I've updated the RT board to show this.

**Comment by cat-manta** [comment]
@angievanhegan Yep that's fine!
