### ISSUE TITLE
Design for BGS Group page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#132]
We only need a design for the very top part of this page: 

- [x] Title (Aims and objectives)
- [x] Intro text with show more
- [x] Label for group type
- [x] Topics labels

**Design**
[Invision link](https://invis.io/4EDQ458R5#/276637857_BGS_Group_Page)

**Comment by cat-manta** [comment]
@angievanhegan I have updated the description with a link to the design.

**Comment by angievanhegan** [comment]
@StephMSlack this is ready for you to sign off. Thnks

**Comment by StephMSlack** [comment]
All good
