### ISSUE TITLE
Enable resources, events and news content to be 'tagged' by group

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#135]
- [x] **ISSUE 1** Ensure multiple groups can be added to News and Policy, Resources, Events and Blog items  
- [x] Use taxonomy for Group names in the same way we did for Events etc with organisations on ALNAP
- [x] Rule to create taxonomy terms based on the group name

You can see this working here: 
http://bgs-dev.mrmdev.co.uk/proactive-care-of-older-people-undergoing-surgery

**Comment by angievanhegan** [comment]
@StephMSlack This issue is just about the ability to tag resources, events, news and blogs with a group so that they appear in this page. 

If you create a 'group' type page, then it creates a taxonomy item. If you cant tag a resource, event, news item with that group, you choose the 'related content' tab on the left hand side, then search for the group under the 'group' heading. Easy. 

**Can you confirm if we can have news, policy and blog items appearing in the same group or if you need them to be separate here?** Thanks

**Comment by StephMSlack** [comment]
@angievanhegan - what order do the items appear in? Do I select what appears on the page or is it automatic? If automatic, there is the possibility that blog overwhelms any policy information relevant to the group, even though the policy information is older. If the editor can choose the content displayed & in what order, then combining is fine, but if automatic, then we might need to keep the blog separate or think about other ways that important content could be displayed

**Comment by angievanhegan** [comment]
@StephMSlack This issue is about enabling tagging by group. Let's discuss this issue in the group pages issue #134. Are you happy to sign this issue off?

**Comment by StephMSlack** [comment]
@angievanhegan can Policy & Media be combined with blog being that they sit in different parts of the site? It will look better if they are combined, but then we will need to show a combined 'see more' page. Is that possible?

**Comment by angievanhegan** [comment]
@StephMSlack You're absolutely right. They're going to need to be separate. I'll create a new issue.

**Comment by StephMSlack** [comment]
@angievanhegan I cannot seem to add more than one group to a news page. eg if the NW thames group want the article on their feed and the Falls & bones group want it on theirs, I'd need to add both groups to the News page for it to show up in their feed. Is that correct?

**Comment by angievanhegan** [comment]
@StephMSlack Yes, that's right, you'd need to add both groups to the news page. Is that ok?

**Comment by StephMSlack** [comment]
Hi @angievanhegan - at the moment I can only add 1 group on the news page. I've tried to add a second group to the article but the system will not let me add the second group.
<img width="1440" alt="screen shot 2018-03-13 at 17 23 55" src="https://user-images.githubusercontent.com/32127102/37358629-79e45b84-26e3-11e8-8e98-747334774f91.png">

**Comment by angievanhegan** [comment]
@StephMSlack I've checked this and it works. It's ready for you to sign off.

**Comment by StephMSlack** [comment]
@angievanhegan @dilwarhussain thanks for this
Just using the function at the moment - the blogs and news/policy are repeating on the new group  page I'm creating
http://bgs-dev.mrmdev.co.uk/bgs-scotland
![screen shot 2018-03-15 at 11 03 51 2](https://user-images.githubusercontent.com/32127102/37459739-f24d825e-2840-11e8-98c0-133a8f8515ef.png)

**Comment by dilwarhussain** [comment]
@StephMSlack Duplication issue should be fixed for latest and curated feeds now.
