### ISSUE TITLE
Members updates on BGS group page

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/bgs#137]
This is a ['member update' type](http://bgs-dev.mrmdev.co.uk/member-update) and can be set to appear on whatever group page you specify. Good eh?

# Done criteria
- [x] **ISSUE 3** Please could this also link to an internal page
- [x] **ISSUE 2** Give Web Admin role permission to create and publish member updates
- [x] **ISSUE 1**  Make Angie, Steph and Recia Web Admin
- [x] Build content type with a single wysiwyg field and an entity reference (multi value) field to the group content type
- [x] The content is to be displayed as a member update on the relevant group(s) as shown in the Group page wireframe

# Designs
- [Design duplicated from my account page](https://invis.io/WSFH05EPFA6)

**Comment by ican-icant** [comment]
@cutlern @russ-manta - how do I sign this off?

**Comment by angievanhegan** [comment]
@cutlern can you show me how I can add/edit this field on the members page please? I can't work it out.  Thanks

**Comment by angievanhegan** [comment]
@cutlern I can't edit the one you made (I'm not an admin) but actually, can you make me, Steph and Recia web admins). Please can you give Web Admins access to create and publish these notices. I created issues in the done criteria at the top. Ta.

**Comment by dilwarhussain** [comment]
@StephMSlack Could I get Recia's email address so I can create a web admin account please, thanks.

**Comment by angievanhegan** [comment]
@dilwarhussain Recia uses editor@bgs.org.uk

**Comment by dilwarhussain** [comment]
@StephMSlack Oh cool, in that case you all have editor accounts and permissions to create/edit/delete member updates.

**Comment by angievanhegan** [comment]
@dilwarhussain Could this also link to an internal page? Sorry if it can already do that and I'm just missing it. It's most likely to link to a news item or an event.

**Comment by angievanhegan** [comment]
@dilwarhussain would you be able to do this one this week, or should I assign it to Pipe? Thanks very much

**Comment by dilwarhussain** [comment]
@angievanhegan Would you like the whole box to be a link? Because currently you can have the option to add a link in the wysiwyg. http://bgs-dev.mrmdev.co.uk/proactive-care-of-older-people-undergoing-surgery

**Comment by angievanhegan** [comment]
@dilwarhussain Got it! I'll put this for Steph to sign off. Thank you.

**Comment by angievanhegan** [comment]
@dilwarhussain I forgot to mention, it's just right how you did it. Thanks

**Comment by StephMSlack** [comment]
@dilwarhussain @angievanhegan Sorry, I just tried to add a member update and don't seem to be able to find where to add it to the page

**Comment by angievanhegan** [comment]
@StephMSlack I put a note at the top, but with hindsight it's not very clear! If you search for the content type 'member update' you see it (there's only one). If you edit that you'll see the fields to add it to a group:
![screen shot 2018-03-02 at 08 34 34](https://user-images.githubusercontent.com/3796718/36901344-d7072a8c-1df4-11e8-8e1c-8b1153013342.png)

**Comment by StephMSlack** [comment]
@angievanhegan we need to be able to add an email address link to the member update

**Comment by StephMSlack** [comment]
@angievanhegan I just need Recia to have a look at this and confirm she is happy with the functionality. As soon as I have that it will be all good to go

**Comment by angievanhegan** [comment]
@StephMSlack Great. There appears to be two on there just now. It's only designed to show one.

**Comment by StephMSlack** [comment]
@angievanhegan I know, but you can add two accidentally :) I was experimenting with how they look and the potential length of these. The expectation is that you would only ever have 1 alert per group. 

Recia was asking if it is possible to add an image to the alert?

**Comment by StephMSlack** [comment]
@angievanhegan I've discussed the comments from you and Steve with Recia and she has agreed to go without the image.
this is fine to go

**Comment by angievanhegan** [comment]
@StephMSlack thanks. I'm assuming it's signed off then - I'll move it to closed. One down...
