### ISSUE TITLE
Build and theme blog content type (issues with comments)

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/bgs#140]
See wireframes, more details to follow
- [x] TWEAK All comments to require approval
- [ ] ~**ISSUE 13** Send editor message when new comment is posted, to be approved~
- [ ] ~**ISSUE 12** Add notification message on screen when comment posted~
- [ ] ~**ISSUE 11** Change 'Comments' to 'Add and view comments'~
- [ ] ~**ISSUE 10** Put 'Add comment' within expand box~
- [ ] ~**ISSUE 9** Comments behaving inconsistently (see comments from Steph below)~
- [x] ~~**ISSUE 8** Slightly more padding around the image.~~
- [x] ~~**ISSUE 7** Comments should appear within a show/hide (the same as the feedback on the resources page) and should be closed by default - Cat to confirm which heading styles should be used (h1 looks a bit big)~~
- [x] ~~**ISSUE 6** Please rename the save button to 'submit your comments'~~
- [x] ~~**ISSUE 5** Right hand nugget should say Author~~
- [x] ~~**ISSUE 4** Ensure full width image can be added and has rounded corners. [Design](https://invis.io/YSH2SH3546G)~~
- [x] ~~**ISSUE 3** All right hand modules should be enabled for the right hand side (text, text with image, box link)~~
- [x] ~~**ISSUE 2** Related content not showing on the right hand side~~
- [x] ~**ISSUE 1** The author heading does not need to be sticky~
- [x] ~Needs sidebar, additional and postscript regions~
- [x] ~Same nuggets as standard page (hide some later)~
- [x] ~Clone News content type display~
- [x] ~Enable Drupal commenting~
- [x] ~Images can be added inline~
- [x] ~Tables can be added~

http://bgs-dev.mrmdev.co.uk/the-other-%E2%80%9Cf%E2%80%9D-word

**Comment by angievanhegan** [comment]
@pipe-manta I don't seem to be able to edit the blog to see if I can add inline images. What am I doing wrong? Thanks

**Comment by pipe-manta** [comment]
@angievanhegan Permissions, fixed! :)

**Comment by angievanhegan** [comment]
@pipe-manta See issue 1 (please) thank you

**Comment by angievanhegan** [comment]
@ican-icant are you happy with this presentation of the [topics links](http://bgs-dev.mrmdev.co.uk/the-other-%E2%80%9Cf%E2%80%9D-word)?  We tried to make it like the [resources page](http://bgs-dev.mrmdev.co.uk/dysphagia-management-for-older-people-towards-the-end-of-life), but it doesn't look quite right

**Comment by ican-icant** [comment]
@angievanhegan     @pipe-manta @cat-manta                                                                

 I agree it doesn't look right and I suggest removing it as it's obvious they are tagged. The only way this will be OK is to add, like resources, a Date published title too and display the date under it

**Comment by angievanhegan** [comment]
@pipe-manta Sorry about this, please can you remove the topic heading from the Blog page, the news page and the policy update page (so that they look like they did before. Sorry.

**Comment by pipe-manta** [comment]
@angievanhegan ISSUE 1 and Topic label done

**Comment by angievanhegan** [comment]
@pipe-manta Thank you so much! @StephMSlack this is ready for you to sign off.

**Comment by StephMSlack** [comment]
@angievanhegan Sorry, a couple of things

**Comments**
the comment function is not working from a visual point of view. 
Comments (I assume this is for comments that have been posted and approved) should only show if there has been a comment on this post. Otherwise it should not be visible. 

The Title Comments / Add a new comment are very large and seem to be out of context with the rest of the page. 

The Comments button below the author on the right is missing and add new comment is always open (and overwhelming the rest of the page as it is so large). It should only open if you want to add a comment (more in line with the feedback on this resource function).
The save button needs to be renamed to Submit your comment

**Author**
The authors name should be larger and in the Purple (as per design) 
The RHS nugget should say Author, not Authors

**Text**
The first line of the text I'm adding doesn't seem to automatically resize (slightly larger) as it has done on other standard pages. I've tried using headers instead, but I don't think it works quite as well.

**Comment by StephMSlack** [comment]
@angievanhegan Also, when I use a full width image, it isnt stretching across the width of the site and the rounded corners of the image are missing on the RHS. 
http://bgs-dev.mrmdev.co.uk/blog/creating-a-%E2%80%98frail-friendly%E2%80%99-acute-medical-unit-not-rocket-science

**Comment by StephMSlack** [comment]
@angievanhegan - should I be using the body field in the overview section for blogs, or should all content go in a content block in the main content section? 
Currently there is very little space between the text added in the overview section and then the text in the main content section
An example is here http://bgs-dev.mrmdev.co.uk/blog/spring-speakers-series-developing-an-intervention-for-falls-in-dementia

**Comment by StephMSlack** [comment]
@angievanhegan Does the related content function work for blogs? Or should we be using the RHS nuggets?

**Comment by StephMSlack** [comment]
@angievanhegan the blog and other pages are also going to need the scheduling function. Currently this has only been enabled on the resources.

**Comment by angievanhegan** [comment]
If you're not having an image, you can put the content into the Overview section in the body field, and use the 'larger text' formatting for the first paragraph. If you want to include images, then you can use content blocks in the main content section.

**Comment by dilwarhussain** [comment]
@StephMSlack Issue 6 and 7 are ready to look at, thanks.

**Comment by angievanhegan** [comment]
@dilwarhussain I think the image should probably have more space around it? See issue 8.

@cat-manta design-wise is it ok for us to have full width images do you think? We hadn't originally built them for this, but could we? Thanks

**Comment by cat-manta** [comment]
@angievanhegan Yeah I think that's fine

**Comment by angievanhegan** [comment]
@dilwarhussain Issue 4 is good to go. Thanks

**Comment by angievanhegan** [comment]
@pipe-manta I've just found an example of how this should look in invision (on the blog page)

![screen shot 2018-04-18 at 09 15 13](https://user-images.githubusercontent.com/3796718/38937590-27a2a1a6-42e9-11e8-9900-6dae80bf4fb2.png)

**Comment by pipe-manta** [comment]
@angievanhegan you can find all the examples on http://bgs-dev.mrmdev.co.uk/pipe-test-page

The way to use the full width image is with the nugget Photo gallery and including only one image with Free crop.

**Comment by angievanhegan** [comment]
@StephMSlack this is ready for you to review.

**Comment by StephMSlack** [comment]
@angievanhegan @pipe-manta 
1) happy with the images options
2) comments function is behaving erratically. When logged out the comments option is not showing at all (on Safari and Chrome). When logged in, the comments are open, and appearing in different places. Screen shots below. All are for blogs with comments turned on.

Blog imported from WP site, logged in
![screen shot 2018-04-25 at 14 40 11](https://user-images.githubusercontent.com/32127102/39249459-a085e95e-4896-11e8-8b11-21c100ef9f77.png)

Blog imported from WP site - logged out
<img width="1232" alt="screen shot 2018-04-25 at 14 41 08" src="https://user-images.githubusercontent.com/32127102/39249520-bb9bafe4-4896-11e8-9f36-15bfeb7bba87.png">

Blog created on the website, logged in
![screen shot 2018-04-25 at 14 42 25](https://user-images.githubusercontent.com/32127102/39249606-e9a80d74-4896-11e8-98ba-e5e6ccf63405.png)

Blog created on website, logged out
<img width="1241" alt="screen shot 2018-04-25 at 14 43 35" src="https://user-images.githubusercontent.com/32127102/39249681-1b749d86-4897-11e8-8470-f65f682da11d.png">

**Comment by dilwarhussain** [comment]
@StephMSlack When logged out, the comments section will only show for blogs that have comments on them. Test comment on this blog: http://bgs-dev.mrmdev.co.uk/blog/asking-the-big-questions-in-dublin%E2%80%99s-fair-city-%E2%80%93-part-2

**Comment by StephMSlack** [comment]
@dilwarhussain Sorry - when I looked at your test blog I got this
![screen shot 2018-05-01 at 09 46 54](https://user-images.githubusercontent.com/32127102/39467217-cbae0d18-4d24-11e8-894e-9f5fe604d0eb.png)
All users should be able to comment on a blog (logged in or not)

This blog has comments on but they are not appearing when logged out
http://bgs-dev.mrmdev.co.uk/blog/the-lonely-brain
![screen shot 2018-05-01 at 09 49 32](https://user-images.githubusercontent.com/32127102/39467253-0db5efa0-4d25-11e8-9f71-6c1e5819cd56.png)

And this is what it looks like when logged in
![screen shot 2018-05-01 at 09 51 53](https://user-images.githubusercontent.com/32127102/39467318-5a67eace-4d25-11e8-95e0-2747d31b7d4f.png)
![screen shot 2018-05-01 at 09 52 02](https://user-images.githubusercontent.com/32127102/39467321-5c36f674-4d25-11e8-891c-30b892b3803b.png)

Is there a step we are missing?

Also, how the comments are displaying for me when logged in is not correct

**Comment by StephMSlack** [comment]
thanks @dilwarhussain 
When a comment has been posted, have you set who the message goes to? If its an email, for testing purposes could you set it to go to me? 

The comments all in the box is great and the submission message is fine.

**Comment by dilwarhussain** [comment]
@StephMSlack I've changed the email to go out to you. Let me know if any of the text needs to be changed. Did you say you want all comments to require approval? Including editors?

**Comment by StephMSlack** [comment]
@dilwarhussain thanks, this is great

Yes all comments should require approval, even editors...

**Comment by angievanhegan** [comment]
@dilwarhussain Is there any chance you can do this tweak today so we can mark this epic as DONE for the demo tomorrow?

**Comment by dilwarhussain** [comment]
@angievanhegan This is already done 🥇

**Comment by StephMSlack** [comment]
thanks @dilwarhussain @angievanhegan. Superstars!
