### ISSUE TITLE
Build and theme blogs landing page

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/bgs#142]
See wireframes, design to follow resources landing page
# Done criteria
- [x] **ISSUE 1** Please put 20 Blog items on a page. Thanks
- [x] **ISSUE 2** All <a> links in .view-card-default-palette have the same background and color attributes
- [x] Add a 'submit a blog' link (top right)
- [x] confirm pagination added

# Wireframe, design, Drupal
- Drupal link http://bgs-dev.mrmdev.co.uk/blog
- Wireframe on RT board
-

**Comment by angievanhegan** [comment]
@cat-manta Please can you create a design to show how the author and topic details will appear on these cards? Sorry, I missed this one in the design list. Thanks

**Comment by angievanhegan** [comment]
@pipe-manta A little bit more for you

**Comment by angievanhegan** [comment]
@StephMSlack This is ready for you to sign off.

**Comment by StephMSlack** [comment]
@angievanhegan we will need more than 4 blogs on the landing page before pagination. Ideally at least 12, preferably 16...

**Comment by angievanhegan** [comment]
@StephMSlack there are now 20 blogs on a page. Are you happy to sign this off?

**Comment by StephMSlack** [comment]
@angievanhegan Just edited the Blog intro - the in-page link styling is off
![screen shot 2018-03-14 at 09 52 45](https://user-images.githubusercontent.com/32127102/37395170-8191d52a-276d-11e8-9627-223dd8d2347c.png)

**Comment by dilwarhussain** [comment]
Thanks @StephMSlack we'll take a look at this.

**Comment by StephMSlack** [comment]
@angievanhegan @pipe-manta - Also, I'm not sure how the sort function works on this page and if its enabled yet? The sort options dont seem that suitable at the moment

**Comment by angievanhegan** [comment]
@StephMSlack At the moment we have latest, relevant (only useful when you've done a search as it will refer back to the search criteria and override the date sort) and popularity (based on hits to the page, which will make more sense once we're not on a dev site). 

These are the standard ones we use and work in most scenarios. Is there any key search missing?

**Comment by StephMSlack** [comment]
@angievanhegan I was having fun creating blogs to make sure the pagination worked...

When I didn't add a pic in the card content for a couple of blogs, the boxes resized and the roll over content didn't fully show. Screen shot below

Also, the submit a blog button currently goes to a blank page (when logged out) or a CMS page (when logged in). Will this go to a form in the future?

![screen shot 2018-03-22 at 14 55 27](https://user-images.githubusercontent.com/32127102/37778372-b97e6b0e-2de1-11e8-9bd3-cca94565b812.png)

**Comment by angievanhegan** [comment]
@StephMSlack This is the way we usually build cards, so that they resize to fit. I think it looks worse here as the blog titles are so short. I'm assuming that you'd nearly always have images. However, if you think you'd prefer for the heights to be fixed as they are in the resources section, I suggest we wait until that has real content too, then we can fix all the heights together. Is that ok?

There's another issue for the blog form.

**Comment by StephMSlack** [comment]
Ok @angievanhegan. I'm scheduled to go through this with the Comms & Policy team first thing Thurs morning, so will feed back/sign off then.

**Comment by StephMSlack** [comment]
@angievanhegan this is fine, thanks

**Comment by matty-manta** [comment]
@pipe-manta                        

The text search doesn't seem to be working properly.
