### ISSUE TITLE
If there's no file to download on a resource page, the 'download' heading on the right hand side should not appear

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#150]
Please can you estimate this. Thanks

Drupal link: http://bgs-dev.mrmdev.co.uk/dysphagia-management-for-older-people-towards-the-end-of-life

**Comment by angievanhegan** [comment]
@dilwarhussain Nice! Thank you. 
@StephMSlack this is ready for you to sign off.

**Comment by StephMSlack** [comment]
@angievanhegan @dilwarhussain thanks for this. all good from here
