### ISSUE TITLE
Reduce the height of the resources when shown in list view on the resources landing page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#152]
<img width="1273" alt="screen shot 2018-02-22 at 10 41 56" src="https://user-images.githubusercontent.com/3796718/36551467-3afd3d80-17bd-11e8-95e3-7ffef1568a2a.png">
Please can you add an estimate to this to so that we have a record of the time. Thanks

**Comment by angievanhegan** [comment]
@dilwarhussain another one for you. Thanks

**Comment by angievanhegan** [comment]
Hello @dilwarhussain They still look like they have lots of spare space and don't need to be that high (and like the 3 tags at the bottom could do with being on one line instead of stacked).  Also, the grid view has gone back to the same height it was yesterday. 

<img width="1260" alt="screen shot 2018-02-23 at 07 12 33" src="https://user-images.githubusercontent.com/3796718/36595776-2d54a04a-1869-11e8-8607-ad1ae0c946a2.png">
<img width="303" alt="screen shot 2018-02-23 at 07 12 53" src="https://user-images.githubusercontent.com/3796718/36595777-2d723b5a-1869-11e8-8fe7-ecca08205771.png">

**Comment by dilwarhussain** [comment]
How's this now @StephMSlack ?

**Comment by StephMSlack** [comment]
@angievanhegan @dilwarhussain this is much better, thanks!
