### ISSUE TITLE
Add 'Section' to the group type (appears as a label on the groups landing page)

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#153]
Section behaves exactly as a SIG, it just has a different name (yes, this makes no sense at all)

# Done criteria
- [ ] A label which says 'section' should appear on the Group landing page

# Designs and Drupal pages
- [Drupal page](http://bgs-dev.mrmdev.co.uk/bgs-groups)
- [Design](https://invis.io/4EDQ458R5#/281120927_BGS_Groups)

**Comment by angievanhegan** [comment]
@cat-manta Please can you design a label for the groups landing page which says 'section'? It will be applied to some of the special interest groups. Thanks

**Comment by cat-manta** [comment]
@angievanhegan I've added a link to the design at the top

**Comment by angievanhegan** [comment]
@cat-manta This is perfect. And the pictures are all great! Thank you.

**Comment by angievanhegan** [comment]
@meldera One for you to do if you'd like it. There's an extra type of group that we need to add to the list in Drupal (you can see tihs when you create a group page). A section is exactly like a SIG and appears (in alphabetical order) under the 'special interest' heading on the BGS Groups landing page. The only difference with a section is that it adds the label onto the box link (see Cat's designed - link at the top). Thanks

**Comment by StephMSlack** [comment]
@angievanhegan tried adding this to test group 2 and it didn't work. But, I think I may have convinced them to do away with the section label on the site except in the title of the group, so we may not need this!

**Comment by angievanhegan** [comment]
@StephMSlack OK - I'll wait until you confirm if we need it or not. As long as you know there might not be space to add it onto the card title in the text (but it'd almost certainly be fine in the page title at the top of the group page)

**Comment by StephMSlack** [comment]
@angievanhegan I have confirmed, we dont need the section label on the group card. BGS have agreed not to use Section in the card title, it will just be used in the full title on their page.
