### ISSUE TITLE
Migrate blog posts and comment

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#156]
Estimate: 1.5 days @ £560 + VAT = £840 + VAT

An invite from WP has been sent to support@mantaraymedia.co.uk to create an account. Account has admin access, so you should be able to see what is needed.

- [x] Consolidate tags (according to spreadsheet sent by Steph
- [x] Migrate images in content into image nugget

**Comment by angievanhegan** [comment]
@StephMSlack Can you provide us with details of the Blog and the comments please? I'm assuming we'll need some admin login details. Thanks

**Comment by StephMSlack** [comment]
@angievanhegan An invite from WP has been sent to support@mantaraymedia.co.uk to create an account. Account has admin access, so you should be able to see what is needed. Let me know if you have any problems

**Comment by russ-manta** [comment]
@angievanhegan @StephMSlack quote 1.5 days

**Comment by angievanhegan** [comment]
@StephMSlack Please see the estimate at the top of the issue and let us know if you'd like us to go ahead. Thanks

**Comment by StephMSlack** [comment]
@angievanhegan @russ-manta Does this include moving the images across as well? Currently some of the images on the blog are small and dont meet our minimum specs for the cards.

**Comment by angievanhegan** [comment]
Steph has confirmed this can be done.

**Comment by angievanhegan** [comment]
@meldera Are the details at the top enough to make a start on this, or do you need server access/details?

**Comment by angievanhegan** [comment]
@russ-manta Can we re-do the import and remove all the topics? Steph would like to use the [new list(https://projects.invisionapp.com/share/4EDQ458R5#/screens/289094992_Topics-Menu-V0-1) which is much more concise

**Comment by StephMSlack** [comment]
@angievanhegan @russ-manta the final list of topics is in the tab 19.04.18 in this google doc
https://docs.google.com/spreadsheets/d/11hHBYGcKRz9DVlWtJaTyrK1oc7JZYTD78DF5dTA_Pn8/edit#gid=1575467942
