### ISSUE TITLE
Migrate news and policy content

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#157]
Estimate: 1/2 day for this at £560 (+VAT) per day

# Done criteria
 - [x] All policy updates [(Media and Policy > Policy updates)](http://www.bgs.org.uk/policy-digest/resources/policy-digest)
 - [x] last 6 months of press releases [(Media and Policy > Press release)](http://www.bgs.org.uk/press-3/press-and-pr/bgs-press-releases)

(not the 'in the news' section)

**Comment by angievanhegan** [comment]
@StephMSlack Can you provide extracts for these please?

**Comment by StephMSlack** [comment]
@angievanhegan Recia moved the site to a new support agency and I've been trying to get an xml extract for weeks. Now trying to get a login from Recia to access the sql database myself. Might not be able to resolve this instantly

**Comment by russ-manta** [comment]
@angievanhegan @StephMSlack I reckon 1/2 day for this at £560 (+VAT) per day

**Comment by angievanhegan** [comment]
Steph has confirmed this can be done.

**Comment by angievanhegan** [comment]
@StephMSlack Please can you provide details/access for the server? (also for #165 ) Thanks

**Comment by StephMSlack** [comment]
@angievanhegan see comment for #165

**Comment by StephMSlack** [comment]
thanks @angievanhegan

**Comment by angievanhegan** [comment]
@StephMSlack This can be closed? Thanks

**Comment by StephMSlack** [comment]
yes @angievanhegan
