### ISSUE TITLE
Mega drop down navigation for topics

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#159]
# Done criteria
- [x] ~~BLOCKER Need [mobile design](https://projects.invisionapp.com/share/4EDQ458R5#/screens/296384372)~~  
- [x] ~~TWEAK - remove random peach~~
- [x] ~TWEAK - sort out mobile version~
- [x] ~TWEAK - add a link to a real topic page (cga-in-community-settings) in the menu so we can see it works~
- [x] ~~BLOCKER - need approval on categories from Steph~~
- [x] ~~BLOCKER - need final approval from [colin on the nav first](https://projects.invisionapp.com/d/main#/console/12154002/281178767/preview)~~
- [x] ~~Appears in global navigation~~
- [x] ~~Display 4 categories and a max of 20  topics~~
- [x] ~~Content types to be tagged to appear in topics: Resources, News, Policy, Blog, Events, Group~~

# Designs & Docs
- [Wireframes](https://realtimeboard.com/app/board/o9J_k0NkHnc=/?moveToWidget=3074457345978345173)
- [Design v1](https://invis.io/4EDQ458R5#/289094992_Topics-Menu-V0-1)
- [Design v2 - we're not using this one](https://invis.io/4EDQ458R5#/289094993_Topics-Menu-V0-2)
- [List of categories and topics](https://docs.google.com/spreadsheets/d/11hHBYGcKRz9DVlWtJaTyrK1oc7JZYTD78DF5dTA_Pn8/edit?usp=sharing)

- [ ] ~Fix mobile menu styling for Topics~
NOTE 
- **We're using version 1 of the nav**
- Categories do NOT have a page
- Topics live within Categories
- Topics can only live within ONE Category

**Comment by angievanhegan** [comment]
@StephMSlack Can you confirm how many categories there are going to be? Thanks

**Comment by angievanhegan** [comment]
Angie, Steve, Steph and Recia to talk about using 6 categories in the navigation, creating 6 topics pages (dynamically) with filters for the topics within the page

**Comment by StephMSlack** [comment]
@angievanhegan The significantly reduced list is here:
https://docs.google.com/spreadsheets/d/11hHBYGcKRz9DVlWtJaTyrK1oc7JZYTD78DF5dTA_Pn8/edit?usp=sharing
Down to 4 topic areas and removed duplicates. Will be discussing with Geraint and Colin tomorrow

**Comment by StephMSlack** [comment]
@angievanhegan final list of topics available in the google drive. All have content and there are no duplicates.
https://docs.google.com/spreadsheets/d/11hHBYGcKRz9DVlWtJaTyrK1oc7JZYTD78DF5dTA_Pn8/edit?usp=sharing

**Comment by angievanhegan** [comment]
@StephMSlack Excellent. So, which way are we going:

A) Four category pages with filters for topics (with only the categories displaying in the nav)
B) A page for each topic (with a mega drop down in the nav)

**Comment by StephMSlack** [comment]
@angievanhegan - Option B please

**Comment by angievanhegan** [comment]
@StephMSlack OK, great. Let's start working on the design for the topics. Once we have the design we'll ask for a quote.

@cat-manta Over to you, please see the notes at the top of the page.

**Comment by cat-manta** [comment]
@angievanhegan @StephMSlack I've added 2 versions of the topics nav to the description at the top

**Comment by StephMSlack** [comment]
thanks @cat-manta I'm preferring option 1 at the moment (with the topic area title in purple).

**Comment by angievanhegan** [comment]
@cat-manta what's your preference? And do you think we should get Steve's opinion on this before we go ahead?

**Comment by angievanhegan** [comment]
@russ-manta Please can you provide a quote and a points estimate for this? Thanks

**Comment by russ-manta** [comment]
@angievanhegan  1/2 day - £280 + VAT

**Comment by pipe-manta** [comment]
Hi @angievanhegan At the moment there is no limit of 20 topics to display on each category, but it's possible to manage that easy on the vocabulary.

**Comment by angievanhegan** [comment]
@pipe-manta Is there a topic page ready that we can get it linking to so that we can show it working? Thanks

**Comment by dilwarhussain** [comment]
@angievanhegan @StephMSlack Links in the mega menu are linking off to the new topics page now.

**Comment by StephMSlack** [comment]
thanks @dilwarhussain 

@angievanhegan @dilwarhussain - Its looking great on a widescreen, but had a look at it on a mobile/tablet and it wasn't really readable. Any thoughts on alternate solutions for mobile/tablet?
![img_8824](https://user-images.githubusercontent.com/32127102/39746227-9fda8b9e-52a1-11e8-9a21-34c3941c0ef6.PNG)
![img_8825](https://user-images.githubusercontent.com/32127102/39746368-0e8c24f8-52a2-11e8-97f7-100776b4e857.PNG)

**Comment by StephMSlack** [comment]
thanks @dilwarhussain. 
the menu looks much better now!

still seeing the random peach when moving to a different item on the menu 

![img_8827](https://user-images.githubusercontent.com/32127102/39813628-16606350-5389-11e8-8fb1-c415b756c458.PNG)

**Comment by angievanhegan** [comment]
@dilwarhussain There's another tweak for you (listed at the top). Don't forget to use strikethrough to show when the done criteria are done :o) Thanks

**Comment by angievanhegan** [comment]
@pipe-manta Is this still in progress, or can we move it to done? Thanks

**Comment by cat-manta** [comment]
@pipe-manta Can you get rid of the white line at the top of the menu? I think it makes more sense without it, then the background of the menu icon can go back to the light purple.
Can you add more space to the right of the arrows please.

**Comment by pipe-manta** [comment]
@cat-manta done the latest changes

**Comment by StephMSlack** [comment]
@angievanhegan this is fine
