### ISSUE TITLE
Topics page (node)

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#160]
NOTE: Courses or Non BGS events will NOT appear on this page

# Done criteria
- [x] ~TWEAK Remove images from cards~
- [x] ~TWEAK Remove title 'tagged content'~
- [x] ~TWEAK Add 'Last updated field to 'blog', 'news' and 'policy updates'~
- [x] ~~TWEAK Have new date field auto populate with 'date published' date~~
- [ ] ~TWEAK - Group pages should only appear at the top and not in the results below~
- [x] ~~BLOCKED - Waiting for Steph to decide if she'd like us to build this~~
- [x] ~~BLOCKED Waiting for design of Navigation so that we can get a quote for nav and node~~
- [x] ~~BLOCKED - Steph confirming approach~~
- [x] ~~**ISSUE 1** Remove the SIG label~~
- [x] ~~There may be 1, 2 or 3 SIGs (if it's one it should span the full width)~~
- [x] ~~Display 20 items per page. Content could be:~~
  - [ ] Blog 
  - [ ] News item
  - [ ] Policy update
  - [ ] Resource
  - [ ] Event (BGS event only)
- [x] ~~Show most recent at the top~~
- [x] Filter to show
  - Blog posts
  - Events 
  - News
  - Policy updates
  - Resource

# Designs & Docs
- [Wireframe](https://realtimeboard.com/app/board/o9J_k0NkHnc=/?moveToWidget=3074457345978345173)
- [Design](https://invis.io/4EDQ458R5#/282070402_Topic-Node)

**Comment by angievanhegan** [comment]
@cat-manta This is ready to be designed. Hopefully it's bascially just checking that what you did for a group landing page will work for this page too. Thanks

**Comment by angievanhegan** [comment]
@cat-manta I think:

1. We should lose the CPD points thing (it's too much detail here)
2. We ought to make it clear whether a card is a resource, an event, a blog item, a news item or a policy update
3. Blog posts will always have an image
4. Policy updates and news items may have an image
5. What do you think about making sure that dates are all placed more consistently?
6. Would it look better if we didn't show the location of events here? 
7. What does Steve think? 

Thank you 👍

**Comment by cat-manta** [comment]
1. Sure can do
2. Maybe we need to look at tagging the type of content, because this makes sense but we would lose the type of resource and event
3. Do I need to add images to the design?
4. Ditto ^
5. The dates weren't placed properly because I hadn't updated the title text, have done this now :)
6/7. @ican-icant ?

**Comment by angievanhegan** [comment]
@cat-manta 

1. Ta
2. I think the type of content is more important than the sub type
3. yes please
4. Ditto
5. I don't think you updated it...

**Comment by cat-manta** [comment]
@angievanhegan I've updated the design

**Comment by cat-manta** [comment]
@angievanhegan Steve doesn't think images should go on this page, not sure if that's possible though

**Comment by angievanhegan** [comment]
@StephMSlack This is ready for you to sign off. As per Cat's comment above, Steve is keen that we don't use images on this page to keep it uncluttered and easier to read and understand what’s what.

**Comment by StephMSlack** [comment]
Thanks @angievanhegan @cat-manta 
One thing - could we lose the section label on the image? Speaking to the team here they have agreed that we don't need to highlight/differentiate between a SIG & a Section except in the relevant SIG/Section page title.
I'll circulate to the team for review

**Comment by StephMSlack** [comment]
@angievanhegan - Could we increase the number in the display to 12 or 20 (in line with resources/blog display)
If there are 3 SIGs linked to that topic, I assume it would move onto another line (v's showing 3 across).

**Comment by angievanhegan** [comment]
@russ-manta Please can you provide a quote and a points estimate for this? Thanks

**Comment by russ-manta** [comment]
@angievanhegan   3 days @ £560 per day = £1680 +VAT

**Comment by dilwarhussain** [comment]
@angievanhegan @russ-manta The 'sort' options here contain filters for content types. This will have to be separated out into another filter option. I need to know what that's going to look like, where it's going to go.

**Comment by angievanhegan** [comment]
@dilwarhussain How's this? I think the default sort should be most recent first. We don't actually need a sort by drop down - we'll only be putting in options for the sake of it. 

<img width="954" alt="screen shot 2018-04-27 at 15 30 07" src="https://user-images.githubusercontent.com/3796718/39383709-e990d498-4a2f-11e8-9ac3-0f76cf54a750.png">

**Comment by angievanhegan** [comment]
@StephMSlack This is ready for you to review. We'll make it 20 per view when you've seen it

http://bgs-dev.mrmdev.co.uk/topics-test/cga-in-community-settings

**Comment by StephMSlack** [comment]
@angievanhegan @dilwarhussain one issue - all the page & group content automatically falls to the back of the content listing - I assume as this content type doesn't have a date associated with it. But some of those pages will be more up to date/recent compared to a blog from 2013 or earlier. Is there anything we can do about this?
![screen shot 2018-05-02 at 16 51 18](https://user-images.githubusercontent.com/32127102/39534242-13e136aa-4e29-11e8-81ff-8a3d51f51372.png)

**Comment by angievanhegan** [comment]
@StephMSlack The SIG shouldn't actually appear in that list, It should only appear at the top! Also, I'm not sure if 'page' content should be appearing on here either - we didn't add it into the requirements. Can you think of any page content that would be particularly relevant?

**Comment by dilwarhussain** [comment]
@StephMSlack @angievanhegan I've limited the content to the ones listed above and also added pages (I can remove if not needed). The sort order is using the last updated date from the content. This is why all the blogs are appearing at the top all together, because they were very recently imported/edited.

**Comment by StephMSlack** [comment]
@dilwarhussain could I check which field you are using to sort the content by date? 
The resources have a last updated field as well. For example the introduction to CGA has a last updated date of 04 Feb 2016, but it is appearing at the top of the list on the topic node page.

![screen shot 2018-05-08 at 10 02 56](https://user-images.githubusercontent.com/32127102/39748177-5b033e0c-52a7-11e8-984a-1bce5ca0e9c1.png)

**Comment by dilwarhussain** [comment]
@StephMSlack I'm using the last updated date, so it's not a field that appears on the content, it's just the timestamp that's created when one of the content types are saved.

**Comment by dilwarhussain** [comment]
@StephMSlack The issue is that the content types do not have one uniform date field across them to be used to sort by.

i.e. Only the resource content type has the last updated field. Events have a start date, end date and display date. The page content type does not have date fields at all, which may be why it wasn't included in the initial list of content types.

Have a look through the content types you want to display in this view and let us know what date would you like the content to be sorted by. One workaround may be to add a 'Last updated' field to the content types which will be used to sort on this display.

**Comment by StephMSlack** [comment]
Thanks @dilwarhussain, I thought that might be the case.

I think the results are too bitty right now -is it possible to add the last updated field to the blog and news/policy content types  and when they come online the events pages? And is it possible to auto-populate this field with the date published (when you add the field to those content types in the CMS? Otherwise I'll need to edit all 800 blogs :( )

**Comment by dilwarhussain** [comment]
That's cool @StephMSlack. I'll discuss with @angievanhegan later today 👍

**Comment by dilwarhussain** [comment]
@StephMSlack I've added the 'last published' date field to blog, news and policy update. We will add to events too when we begin work on those. I've also auto-populated the field on all 800 blogs to use the existing date field. The page is being sorted by the new field now so all should be working fine.

**Comment by angievanhegan** [comment]
@cat-manta @StephMSlack Didn't we decide that we wouldn't display any images on the topics pages? Even or the blogs? Although  we love having images, it looks quite messy that some have images and some don't, esecially if this combination is on the same line. @dilwarhussain This is entirely my fault for forgetting to pass this on. Sorry.

**Comment by StephMSlack** [comment]
@angievanhegan @dilwarhussain - please could we follow up the slack discussion and look at how to include a promo on the topic node to push users to a page (eg the topic Age & ageing journal also needs to show the Age & ageing page in about us)

**Comment by angievanhegan** [comment]
@StephMSlack I'll create new cards for this it's a new issue. Fingers crossed they'll both be little ones.
