### ISSUE TITLE
Additional documents to download available at the bottom of the resource page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#161]
(from Steph)Some of the things we produce are worksheets that people can use and adapt/reproduce as needed so they need to be word docs.

- [x] **ISSUE 2** Update margin (see notes below)
- [x] **ISSUE 1** Update the vertical grey line as per design (see Steph's comments below)
- [x] BLOCKED - Steph to see if the additional documents can go into the main body (possibly with a heading)
- [x] Design for downloads at the [bottom of the main section of the page](http://bgs-dev.mrmdev.co.uk/resources/how-to-get-funding-and-fellowship-applications) 

[Design in Invision](https://projects.invisionapp.com/share/4EDQ458R5#/screens/266499635_Resource-Node)

**Comment by angievanhegan** [comment]
@pipe-manta another one for you. Thanks

**Comment by pipe-manta** [comment]
@angievanhegan At the moment it's possible to add any type of field using Sidebar Attachment nugget. 

I have added an example on this resource http://bgs-dev.mrmdev.co.uk/princesa-the-pooch with both of the block on the RHS.

**Comment by angievanhegan** [comment]
@StephMSlack this is ready for you to sign off.

**Comment by StephMSlack** [comment]
![screen shot 2018-02-28 at 10 22 44](https://user-images.githubusercontent.com/32127102/36782599-5747170a-1c71-11e8-82e6-bd857e0065d4.png)

**Comment by meldera** [comment]
Current functionality requirements are not compatible with formats other than .pdf
If this has to be changed, they will loose the automatic cover generation.
Otherwise attachments will have to be used for formats other than .pdf

**Comment by angievanhegan** [comment]
@meldera So if it's a word doc it would require a cover image? Or we'd have to rebuild it to enable Drupal to create a cover image from a Word doc?

**Comment by meldera** [comment]
@angievanhegan All resources will require cover images to be manually uploaded, regardless of what the file format is.

**Comment by StephMSlack** [comment]
@angievanhegan I've added an attachment nugget to this resource http://bgs-dev.mrmdev.co.uk/how-to-get-funding-and-fellowship-applications 
The attachment nugget within the main content block hasn't been styled to fit our design (we haven't needed it so far!) but if we could update the look a bit, we should be able to make it work (v's using the attachment nugget in the RHS). See what you think

**Comment by angievanhegan** [comment]
@StephMSlack Yes@ The nugget in main content seems to work fine to me. I'll pass it to Cat to ask for some design. 

@cat-manta Some of the resources are going to need a couple of additional documents. We don't want to add them to the right hand column because the sticky nav will mean people can't get to it.  We'd like to add a nugget in the main content. I've added content, but it needs a bit of design to make it look good. It has all the same elements as the download on the right hand side. Thanks

![screen shot 2018-03-01 at 09 30 07](https://user-images.githubusercontent.com/3796718/36849957-67c786ec-1d33-11e8-9d19-1f1699e9ee64.png)

**Comment by cat-manta** [comment]
@angievanhegan I've added extra attachments to the bottom of the resource node design:
https://invis.io/4EDQ458R5#/266499635_Resource-Node

**Comment by angievanhegan** [comment]
@cat-manta Lovely. Thank you. @pipe-manta A little bit more work for you! Thank you both.

**Comment by angievanhegan** [comment]
@pipe-manta Nice! @StephMSlack Ready for you to sign off.

**Comment by StephMSlack** [comment]
@angievanhegan this download function is working fine
Is it possible for the attachment nugget to have its title left aligned? It starts to look out of place when centred on the page

**Comment by angievanhegan** [comment]
@StephMSlack Sorry Steph, can you send me a screen grab so I know what you mean. Thanks.

**Comment by StephMSlack** [comment]
![screen shot 2018-03-14 at 15 53 42 2](https://user-images.githubusercontent.com/32127102/37413909-ec334602-279f-11e8-93b2-6dcfc2a49bc1.png)

Supporting documents is the title of the attachment nugget.

**Comment by dilwarhussain** [comment]
@StephMSlack I've aligned the title to the left for the attachments

**Comment by StephMSlack** [comment]
thanks @dilwarhussain 
@angievanhegan one small thing I noticed - the size of the dividing line between documents (when you more than one) seems to be set to the height of the image rather than the height of the box (which includes the image and the download text). Is there anyway we can make it consistent?
![screen shot 2018-03-21 at 14 17 42](https://user-images.githubusercontent.com/32127102/37715165-3a734a24-2d13-11e8-8f4a-dc37faef4d7c.png)

**Comment by angievanhegan** [comment]
@StephMSlack i wonder if it would be better to lose the line? I think it might just look better without it.

**Comment by StephMSlack** [comment]
@angievanhegan if @cat-manta is happy to lose the line, we can lose the line :)

**Comment by cat-manta** [comment]
@angievanhegan @StephMSlack I think it would be better for clarity to keep the line, but maybe the line should go all the way down past both resources, and have another horizontal line to separate the resources on the top and bottom?

**Comment by angievanhegan** [comment]
@cat-manta Do you have time to update the design? Thanks

**Comment by cat-manta** [comment]
@angievanhegan @StephMSlack I've updated the design, I thought it might be easier, and didn't take long

**Comment by dilwarhussain** [comment]
@StephMSlack New lines applied to attachments view. http://bgs-dev.mrmdev.co.uk/resources/how-to-get-funding-and-fellowship-applications

**Comment by StephMSlack** [comment]
thanks @dilwarhussain could the margin for the line be changed slightly as currently in the lower two have the title partly hidden. I think it relates to when the title is using the document name rather than a title being added.
<img width="821" alt="screen shot 2018-03-27 at 14 21 02" src="https://user-images.githubusercontent.com/32127102/37970066-649d6e22-31ca-11e8-825c-fd2581262991.png">

**Comment by dilwarhussain** [comment]
@StephMSlack You're correct it was to do with using the file name instead of a title, so I've made the filename wrap round to the second line when it's longer than the area available to render. Best practice to use the title field to keep these looking great.

**Comment by StephMSlack** [comment]
thanks @dilwarhussain 
@angievanhegan signed off
