### ISSUE TITLE
Amend alignment on resource page to help editor understand the page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#162]
Please can you make the File and Description appear underneath the Resource series heading so that the editors can see where to add the file description. At the moment it's confusing. Thanks

![screen shot 2018-02-27 at 13 13 47](https://user-images.githubusercontent.com/3796718/36746453-5b0e2aec-1bc0-11e8-97e3-fd9035bf530b.png)

**Comment by meldera** [comment]
![please-f5](https://user-images.githubusercontent.com/29143534/36794337-f8398140-1c97-11e8-9978-dd389bce558f.png)
