### ISSUE TITLE
Migrate resources from XML file

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#164]
Estimated at 3 days @ £560 + VAT

**Comment by russ-manta** [comment]
@StephMSlack can you remind me where all the resources live by sending some links please?

**Comment by angievanhegan** [comment]
@russ-manta Steph is going to put them all into an XML file as they are in various places. There is a top level 'Resources' section on the site which contains most of them. But this is a good start: 

http://www.bgs.org.uk/publicationfind-2/resources/resourcesgeneralinfo/findapublicaton

**Comment by russ-manta** [comment]
@angievanhegan I think 3 days for this

**Comment by angievanhegan** [comment]
@StephMSlack This has been estimated. Let us know if you'd like us to go ahead.

**Comment by StephMSlack** [comment]
@angievanhegan - Unfortunately we have just found that we wont be able to get the files out of our current site. So this issue will be managed manually. Thanks for the quote

**Comment by angievanhegan** [comment]
@StephMSlack what a shame about the extract.
