### ISSUE TITLE
Migrate content for archive section

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#165]
Estimate: 1/2 day for this at £560 (+VAT) per day

**BLOCKER** What to do about filter pages
- [About us > Archive > Biographies](http://www.bgs.org.uk/geriatricmedicinearchive/bgsarchive/biographies)
- [About us > Archive > Geriatric history](http://www.bgs.org.uk/geriatricmedicinearchive/bgsarchive/geriatricshistory)

**Comment by russ-manta** [comment]
@angievanhegan @StephMSlack I reckon 1/2 day for this at £560 (+VAT) per day

**Comment by angievanhegan** [comment]
@StephMSlack Please let us know if you'd like us to go ahead with this.

**Comment by StephMSlack** [comment]
@angievanhegan @russ-manta is the back-up file from our current site useful at all in terms of extracting data?

**Comment by russ-manta** [comment]
@StephMSlack it will be quicker to input the content manually, that's what my quote is based on

**Comment by StephMSlack** [comment]
OK, thanks @russ-manta 
@angievanhegan I'll let you know

**Comment by angievanhegan** [comment]
Steph has confirmed this can be done.

**Comment by angievanhegan** [comment]
@StephMSlack Please can you provide details/access for the server? Thanks

**Comment by StephMSlack** [comment]
@angievanhegan @cutlern 
Recia has given me the details to access the FTP site if that is of help?
Host: sftp://104.236.241.214
user: ftp-recia
pass: 7Sds3c#b%ph2toEz4kh
port: 22

**Comment by angievanhegan** [comment]
@cutlern Are we too late in the process to migrate the geriatric histories into resource pages? Steph would like to create a new resource type called 'history' and possibly put them into a series. 

For the biographies, they can stay as standard pages, Steph is going to list them with FAQ nuggets (e.g. A - G, H - M etc)

**Comment by cutlern** [comment]
@angievanhegan No, that's fine :)

**Comment by angievanhegan** [comment]
@cutlern Is it all done now? Can I move it to BGS review for Steph to check over? Thanks

**Comment by cutlern** [comment]
@angievanhegan yeah it's ready for checking, there were some missing images/broken links though:

News/policies

Will have broken links once site is transferred

http://bgs-dev.mrmdev.co.uk/policy-and-media/future-of-health-and-social-care-in-england

http://bgs-dev.mrmdev.co.uk/policy-and-media/national-assembly-for-wales-health-social-care-and-sport-committee-inquiry-into / http://www.bgs.org.uk/policy-digest-m/resources/policy-digest/wales-loneliness-isolation

http://bgs-dev.mrmdev.co.uk/policy-and-media/long-term-sustainability-of-the-nhs-and-adult-social-care-government-response / http://www.bgs.org.uk/about/resources/policy-digest/long-term-sustainability-of-the-nhs-and-adult-social-care-government-response

404 links

http://bgs-dev.mrmdev.co.uk/policy-and-media/correspondence-between-the-bgs-and-jeremy-hunt-mp / http://www.bgs.org.uk/policy-digest-m/resources/policy-digest/bgs-letter-to-jeremy-hunt

http://bgs-dev.mrmdev.co.uk/policy-and-media/bgs-submission-in-response-to-the-health-select-inquiry-on-planning-for-winter / http://www.bgs.org.uk/policy-digest-m/resources/policy-digest/2016-winter-pressures-consultation

http://bgs-dev.mrmdev.co.uk/policy-and-media/bgs-policy-update-september-2016 / http://www.bgs.org.uk/bgs-policy/resources/policy-digest/sep16-policy-update?jjj=1523013586335

http://bgs-dev.mrmdev.co.uk/policy-and-media/kings-fund-approaches-to-social-care-funding / http://www.bgs.org.uk/home-1/resources/policy-digest/king-s-fund-approaches-to-social-care-funding

Histories:

Will need an updated link once geriatrics page is sorted:

http://bgs-dev.mrmdev.co.uk/resources/charting-the-course-of-philanthropy-in-the-care-of-older-people-and-why-it-is-important / http://www.bgs.org.uk/geriatricmedicinearchive/bgsarchive/geriatricshistory/charting-course-philanthropy

Broken images:
http://bgs-dev.mrmdev.co.uk/resources/history-of-geriatric-medicine-in-the-uk-pioneers-of-geriatric-medicine / http://www.bgs.org.uk/geriatricmedicinearchive/bgsarchive/geriatricshistory/history-of-the-development-of-geriatric-medicine-in-the-uk-article-3

Biographies 

Broken images:
http://bgs-dev.mrmdev.co.uk/bgs-presidents-biographical-sketches-peter-crome / http://www.bgs.org.uk/geriatricmedicinearchive/bgsarchive/biographies/bgs-presidents-biographical-sketches

http://bgs-dev.mrmdev.co.uk/bgs-presidents-biographical-sketches-graham-mulley / http://www.bgs.org.uk/geriatricmedicinearchive/bgsarchive/biographies/bgs-presidents-biographical-sketches-graham-mulley

**Comment by StephMSlack** [comment]
@angievanhegan 
Archive - All the biographies have come through.
We are missing the following from the resources section:
http://www.bgs.org.uk/geriatricmedicinearchive/bgsarchive/geriatricshistory/brief-history-care-elderly 
http://www.bgs.org.uk/geriatricmedicinearchive/bgsarchive/geriatricshistory/md-early-surveys
http://www.bgs.org.uk/geriatricmedicinearchive/bgsarchive/geriatricshistory/the-major-influences-in-geriatric-medicine
http://www.bgs.org.uk/geriatricmedicinearchive/bgsarchive/geriatricshistory/hippocrates-mwarren
http://www.bgs.org.uk/geriatricmedicinearchive/bgsarchive/geriatricshistory/history-of-the-development-of-geriatric-medicine-in-the-uk-article-4
http://www.bgs.org.uk/geriatricmedicinearchive/bgsarchive/geriatricshistory/doreennorton

**Comment by cutlern** [comment]
Hi @StephMSlack Sorry about that, don't know how I missed them!! They've been added now if you'd like to check them :)

**Comment by StephMSlack** [comment]
thanks @cutlern this is great
