### ISSUE TITLE
Enable a google map to be added as a resource

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#166]
A resource would be created as normal, instead of having text content in the main body, it should show a google map. BGS would like to do this to show all the research centres.

Drupal link: http://bgs-dev.mrmdev.co.uk/resources/princesa-the-pooch (2 maps added in 2 regions)

**Comment by meldera** [comment]
Correct. Give permission to use the iframe paragraph and restrict allowed domains on the front end.

**Comment by angievanhegan** [comment]
@russ-manta Can this be enabled please? It'd be great if you can add an example for me/Steph to see. Thanks

**Comment by angievanhegan** [comment]
@dilwarhussain lovely. Thanks. 
@StephMSlack This is ready for you to review. You can edit/add a map in the postscript section using the iframe nugget.

**Comment by StephMSlack** [comment]
@angievanhegan thanks, this is fine
