### ISSUE TITLE
Logging into content gives error message

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#167]
![screen shot 2018-02-28 at 13 19 04](https://user-images.githubusercontent.com/3796718/36805074-67d2fee0-1c8a-11e8-8e92-b05751a218e7.png)

Also, if you're looking at a resource which prompts you to log in, it take you to the login page, then when you login you end up at the home page and have to find the resource again. Please can you be returned back to the page which prompted the login.

**Comment by dilwarhussain** [comment]
@StephMSlack This is fixed now.

**Comment by StephMSlack** [comment]
thanks @dilwarhussain 
@angievanhegan this is fine to close
