### ISSUE TITLE
Ensure events cards look ok on group landing page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#171]

**Comment by angievanhegan** [comment]
@StephMSlack This is ready for you to review.

http://bgs-dev.mrmdev.co.uk/peri-operative-care-of-older-people-undergoing-surgery

**Comment by StephMSlack** [comment]
@angievanhegan @dilwarhussain this looks good. \

Can we set the size of the boxes so they are the same as the resource boxes? Events is one of the key things we need to push, but they are looking a little small next to the larger resources boxes and then the cards with images in the blog/news

**Comment by StephMSlack** [comment]
@angievanhegan @dilwarhussain I've used the upcoming events - latest feed on the trainee group page - we'll need the event happening soonest (eg the September one) to show before the November meeting. I assume this sorting may be linked to the event dates which are not coming into drupal properly at the moment?

**Comment by dilwarhussain** [comment]
@StephMSlack I've changed the height of the event cards to work like the resource cards. And I've fixed the ordering by using the start date in civi.

**Comment by StephMSlack** [comment]
Great, thanks @dilwarhussain 
@angievanhegan this is fine to close
