### ISSUE TITLE
External event payment

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#176]
Estimate: 5 days at £560 + VAT 
**There's a line in the proposal for event submission and payment (non BGS events) for 5 days @ £500. This covers the entirety of this work**

# Done criteria
- [x] Payment
- [ ] ~Build and style landing page (no search or filters needed)~
- [ ] ~Events furthers into the future are at the bottom of the page (soonest events at the top)~
- [ ] ~Build and style node page~
- [ ] ~Build and style form to enable people with account to submit an event with these fields~
- [ ] ~Enable Web Admin to review/edit and publish event~
- [ ] ~Web Admin able to specify date for event to be removed from the site~
- [ ] ~Landing page is linked to from 'External events' link in the Events section of global nav~
- [x] Redirect to payment contribution page in Civi
- [x] Check who is emailed / cced by the civicontribution payment page - membership@bgs.org.uk & editor@bgs.org.uk (add these)

FIELDS -  All fields are mandatory except the reciprocal marketing checkbox.

- ~Event title (maximum characters to be decided)~
- ~Start date~
- ~End date~
- ~Venue - specific address inc postcode (NODE PAGE)~
- ~Venue - City/Country (CARD CONTENT)~
- ~Organiser~
- ~Information about your event (we may need to include some additional guidance text here)- Free text box, limit to 150 words)~ **Limited to 600 characters**
- ~Intended audience (we may need to include some additional guidance text here) - Free text box~
- ~Cost~
- ~Weblink or email address for programme and registration~
- ~check box - I agree to promote in response a BGS meeting on an equal basis. If the check box is not ticked, we need to show a cost for promoting the event on the site.~

# Designs & Docs
- [Non BGS event landing page on RT board](https://realtimeboard.com/app/board/o9J_k0NkHnc=/?moveToWidget=3074457345967174273)
- [Non BGS event node](https://realtimeboard.com/app/board/o9J_k0NkHnc=/?moveToWidget=3074457345967174273)

**Comment by angievanhegan** [comment]
@russ-manta This one also needs costing and estimating please. Thanks

**Comment by russ-manta** [comment]
@angievanhegan 5 days for this

**Comment by angievanhegan** [comment]
@StephMSlack Russ has estimated this (see the top of the issue). Please let us know if you'd like us to go ahead with this. Thanks

**Comment by StephMSlack** [comment]
Hi @angievanhegan Going through budgets at the moment - could we talk about this one?

**Comment by angievanhegan** [comment]
@StephMSlack If you want to use the 5 days allocated to Event submission and payment (non BGS events) then that's fine with us.

**Comment by StephMSlack** [comment]
@angievanhegan I'm double checking with Geraint and Recia. This one links to the event listing process diagram I sent through on slack (below). 

![external event listing process 1](https://user-images.githubusercontent.com/32127102/40435083-c8d8c38c-5ea7-11e8-83da-c44c1c70874f.png)

We need to take a payment from for-profit users. I'm clarifying with Geraint/Daniella whether this can go through Civi or needs to go via drupal/Stripe and where the payment sits within the process (Geraint had it at the beginning, which may require the user to duplicate inputting information).

**Comment by StephMSlack** [comment]
@angievanhegan the fields above are correct

**Comment by angievanhegan** [comment]
@russ-manta Can I pass this over to you to sort out the payment aspect please?

**Comment by russ-manta** [comment]
@angievanhegan yes I've now added a new task to this card for that
