### ISSUE TITLE
Resources - filter by latest

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#178]
- [ ] ~**ISSUE 1** Please make the 'latest' filter sort on last edited date (not published date). ~
- [x] ~~The filter seems to show the oldest first. Please can it show the most recently published first.~~ 
- [x] ~~Please can the blog filter say 'latest' rather than 'date' so that it's working in exactly the same way as Resources and Policy & Media~~

Drupal link:http://bgs-dev.mrmdev.co.uk/resources

**Comment by angievanhegan** [comment]
@dilwarhussain Please can the dropdown filter on blog say 'latest' instead of 'date' so that the filters on Blog, Resources and Policy & Media are all the same. Thanks

**Comment by angievanhegan** [comment]
This is ready to sign off.

**Comment by StephMSlack** [comment]
@angievanhegan This is still showing inconsistently. There are 2015 resources mixed with 2018 and 2017 resources. 

I think it is linked to the date published/date updated fields. I think we are using the last updated field for ordering the display, but showing the published date on the card. 

Can we use the same field for both? I think we should display last updated on the card as well as using that field to order the display. 

Here are screen shots of what I am seeing. I am logged out and it is using the default sort.
![screen shot 2018-03-21 at 15 17 57](https://user-images.githubusercontent.com/32127102/37718769-64882958-2d1b-11e8-890a-e73b6c044212.png)
![screen shot 2018-03-21 at 15 18 14](https://user-images.githubusercontent.com/32127102/37718771-66f3cd0a-2d1b-11e8-8517-d026b71228f6.png)
![screen shot 2018-03-21 at 15 18 35](https://user-images.githubusercontent.com/32127102/37718779-6ad8272c-2d1b-11e8-8bf6-f3a9a4784e8e.png)
![screen shot 2018-03-21 at 15 18 47](https://user-images.githubusercontent.com/32127102/37718791-7114544e-2d1b-11e8-9964-bf5abc6d7e36.png)

**Comment by angievanhegan** [comment]
@StephMSlack Which date would you like this to sort on? Date created or last edited?

**Comment by StephMSlack** [comment]
@angievanhegan @dilwarhussain sorry for the delay. Last edited please

**Comment by dilwarhussain** [comment]
'Latest' sorting is now using the 'Last updated*' field on the resource content type with most recent at the top.

**Comment by StephMSlack** [comment]
thanks @dilwarhussain @angievanhegan this is fine
