### ISSUE TITLE
Number of resource results different whether the user is logged in out

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#179]
Logged out see 21 resources, logged in users see 25. These numbers should be exactly the same.

**Comment by meldera** [comment]
Some are unpublished

**Comment by angievanhegan** [comment]
@StephMSlack Simple answer! See Arseni's comment above.

**Comment by StephMSlack** [comment]
@angievanhegan thanks - I was hoping for the simple answer.
