### ISSUE TITLE
Add Blog updates to BGS group landing page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#183]
At the bottom of the page the heading is 'Latest news, blogs & policy updates' but it's only showing the updates from the Policy and Media. We'll need to add another section for the Blog updates as we don't have a combined 'see latest' section to take them both too. 

# Done criteria
- [x] Update heading 'Latest news, blogs & policy updates' to 'Latest news and policy updates'
- [x] Add new section showing latest blog updates (with the heading 'Latest blog posts')

Add this under ADDITIONAL CONTENT > FEED > select GROUP LATEST CONTENT > BLOG POSTS

http://bgs-dev.mrmdev.co.uk/proactive-care-of-older-people-undergoing-surgery

**Comment by angievanhegan** [comment]
@dilwarhussain I think I could probably do some of this myself, but I got confused when looking at which feeds to select so I thought it was better to ask for help. Thanks

**Comment by StephMSlack** [comment]
@angievanhegan I can add the blog to a group page, but the display is showing incorrectly on this page http://bgs-dev.mrmdev.co.uk/peri-operative-care-of-older-people-undergoing-surgery-pops

![screen shot 2018-03-22 at 12 26 26 2](https://user-images.githubusercontent.com/32127102/37770471-706c9cde-2dcc-11e8-9ab2-28e571bf7f8b.png)

The headings for the feeds do not display automatically on the groups page - but that is fine as I do not think they should.

**Comment by angievanhegan** [comment]
@StephMSlack you just needed to set it for four wide to get the right format. So, I'm assuming it's ok to sign this off.
