### ISSUE TITLE
Check BGS Groups landing page in Safari

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#185]
http://bgs-dev.mrmdev.co.uk/bgs-groups

**Comment by dilwarhussain** [comment]
@angievanhegan @StephMSlack Can you guys check this on your versions of Safari, should be looking good now, thanks.

**Comment by StephMSlack** [comment]
@angievanhegan @dilwarhussain thanks! its looking better - though a new issue has arisen - the second block of groups no longer stretches across the page
<img width="1280" alt="screen shot 2018-03-15 at 14 57 20" src="https://user-images.githubusercontent.com/32127102/37471268-3f0727c4-2861-11e8-8742-fef7d7082e82.png">

**Comment by dilwarhussain** [comment]
@StephMSlack Just noticed this myself, should be fixed now 👍

**Comment by StephMSlack** [comment]
thanks @angievanhegan @dilwarhussain this is showing correctly on Safari now.
