### ISSUE TITLE
Enable right hand modules on group landing page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#187]
# Done criteria
- [x] **ISSUE 1** Remove popular links functionality from Group landing page (see comments below)
- [x] Text (and image)
- [x] Card link
- [x] Attachment

# Designs & Docs
- [Examples on Falls and Bone health group page](http://bgs-dev.mrmdev.co.uk/falls-and-bone-health)
- [Sample right hand modules](http://bgs-dev.mrmdev.co.uk/about/examples/right-hand-column)

**Comment by angievanhegan** [comment]
I added some right hand modules here, but they're not appearing. What am I doing wrong? 

http://bgs-dev.mrmdev.co.uk/falls-and-bone-health

**Comment by angievanhegan** [comment]
@dilwarhussain They're appearing now. Did you fix it?

**Comment by StephMSlack** [comment]
@angievanhegan I can add these and edit the newly added sidebar/RH nuggets.

@dilwarhussain this seems to have had an impact on the popular links function. The option to add the URL has disappeared & the spacing of the box has changed on the front end. Screen shots below

Group steph editing (recently added)
![screen shot 2018-03-21 at 16 53 52](https://user-images.githubusercontent.com/32127102/37724590-0947f592-2d29-11e8-82c2-6eed905ea951.png)

View on page
![screen shot 2018-03-21 at 16 59 10](https://user-images.githubusercontent.com/32127102/37724698-40f526a4-2d29-11e8-9f68-53e3c5fbde25.png)

Dilwars test
![screen shot 2018-03-21 at 16 54 17](https://user-images.githubusercontent.com/32127102/37724606-1444590e-2d29-11e8-852e-d82562819146.png)

**Comment by angievanhegan** [comment]
@StephMSlack Sorry, I should have explained. I think the popular links right hand module was made in error. The plan had been to use the standard right hand modules to give you that functionality. You can either feature one resource (with a card link) or you can add a bulleted list (with a text rhs) if you wanted to link to two or three different resources. The only think the popular links gives you is a button, but to be honest I think it's better to minimise the use of these.

**Comment by StephMSlack** [comment]
@angievanhegan OK, that is fine. Could the popular links in the CMS sidebar be removed then? Or at least minimised. It is really large and overwhelms the page in the CMS, and as the button cannot be used to direct the user anywhere, its probably best not to have it. 
![screen shot 2018-03-22 at 12 04 18](https://user-images.githubusercontent.com/32127102/37769541-44bce9c0-2dc9-11e8-8dfe-c13db79b8986.png)

**Comment by dilwarhussain** [comment]
@StephMSlack RHS poular links field removed.

**Comment by StephMSlack** [comment]
thanks @dilwarhussain much less confusing

**Comment by StephMSlack** [comment]
@angievanhegan this is fine now
