### ISSUE TITLE
Change the name of the groups to Nation and Region

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#188]
BGS call them Nation and Region rather than National and Regional.

**Comment by angievanhegan** [comment]
@StephMSlack Do you still need this doing?

**Comment by StephMSlack** [comment]
@angievanhegan yes please - it is the heading text within the page (which I cannot change) not the menu/page name

**Comment by StephMSlack** [comment]
Thanks @dilwarhussain 
@angievanhegan this is good to go
