### ISSUE TITLE
Control publish and expiry date for specified content types

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#189]
# Done criteria
- [x] Blog posts
- [x] Policy updates
- [x] Member update
- [x] News articles

**Comment by angievanhegan** [comment]
@dilwarhussain please can you let me know if this is more than a 2. Thanks

**Comment by dilwarhussain** [comment]
@angievanhegan I've set this up on all the content types above, but it needs a cron job set up to work, this usually is done on the live site. Might need help from Russ if we need to enable to test on the dev site.

**Comment by russ-manta** [comment]
@cutlern can you check if this is working please?

**Comment by angievanhegan** [comment]
@StephMSlack It looks like this is ready for you to check

**Comment by StephMSlack** [comment]
@angievanhegan this is working fine
