### ISSUE TITLE
Create form to enable someone to submit a blog

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#194]
# Done criteria
- [ ] The button should now open an email window and send an email to pr@bgs.org.uk.
Thanks

**Comment by angievanhegan** [comment]
@StephMSlack Is this still required for the launch? Thanks

**Comment by angievanhegan** [comment]
@StephMSlack This is ready for you to review.

**Comment by StephMSlack** [comment]
@angievanhegan this is fine, thanks. I'll close the issue
