### ISSUE TITLE
Check emails for resources feedback is being sent

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#195]
See issue #107

- [ ] ~Not working to multiple addresses~

**Comment by dilwarhussain** [comment]
@StephMSlack What email address should these be going to? Just tested with my email address and they are sending fine.

<img width="1175" alt="screen shot 2018-06-14 at 10 34 28" src="https://user-images.githubusercontent.com/29142647/41404353-e5d8955c-6fbe-11e8-9400-b1d85e0852e8.png">

**Comment by StephMSlack** [comment]
@dilwarhussain please could they go to editor@bgs.org.uk and s.slack@bgs.org.uk
thanks

**Comment by dilwarhussain** [comment]
@StephMSlack Done

**Comment by StephMSlack** [comment]
@dilwarhussain Sorry to say, but I didnt receive an email letting me know that feedback on a resource has been submitted. I commented on the hospital wide geriatric assessment and received an error message on submission
![image](https://user-images.githubusercontent.com/32127102/41694144-ceb85aa2-74d6-11e8-86b6-9be161efbf36.png)

**Comment by dilwarhussain** [comment]
@StephMSlack The error message will not show once live.

@russ-manta It seems emails are only working to mataraymedia.co.uk accounts at the moment? Just tried with my personal email and it didn't come through. Steph didn't get the email either.

**Comment by dilwarhussain** [comment]
@StephMSlack Emails are being sent out to the correct addresses now.

**Comment by StephMSlack** [comment]
@angievanhegan this if fixed and fine to close
