### ISSUE TITLE
Setup permissions

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#197]
This spreadsheet needs to be approved by BGS first. 

https://docs.google.com/spreadsheets/d/1UUJRooiPsyaohSc-AL9U2ZeWj8H35gS8uGy_fIaCe-4/edit#gid=1470448264

**Comment by angievanhegan** [comment]
@StephMSlack Is this right now? Can we go ahead and set it up?

**Comment by russ-manta** [comment]
@StephMSlack do we need to revisit this still?

**Comment by StephMSlack** [comment]
@russ-manta @angievanhegan I'm just reconfirming this. Within the node, will they be able to edit the related tab?

**Comment by StephMSlack** [comment]
@angievanhegan we are happy with the table in the google doc above, as long as they can also access/edit the related tab in Drupal

**Comment by russ-manta** [comment]
now done
