### ISSUE TITLE
Update layout of search boxes (with shorter date fields always on the right hand side)

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#198]
Note: Please don't change the fields used, just the alignment/order of the ones that are already there. 

# Done criteria
- [ ] ~News and Policy landing page http://bgs-dev.mrmdev.co.uk/policy-and-media~
- [ ] ~Blog http://bgs-dev.mrmdev.co.uk/blog~
- [ ] ~Resources http://bgs-dev.mrmdev.co.uk/resources~

(this layout will also be used on events and topics pages later

![search](https://user-images.githubusercontent.com/3796718/37979692-ddd12dc2-31ae-11e8-9832-f5ed9f70aa79.png)

**Comment by dilwarhussain** [comment]
Hey @StephMSlack Could you take a look at the filters please. Thanks.

**Comment by StephMSlack** [comment]
@dilwarhussain 
Could you remove the 's' in the authors field (it should be author)

@angievanhegan 
this still feels out of alignment and I realised that we have search/clear all at a certain distance from the left, then the dates at a different distance from the left and then the lines/centre of the cards below at a different distance  from the left.
![screen shot 2018-04-05 at 14 01 52](https://user-images.githubusercontent.com/32127102/38367271-24c3f3b8-38da-11e8-91f2-d38f83f7da22.png)
.

**Comment by angievanhegan** [comment]
@ican-icant can you have a catch up with @StephMSlack about the alignment of these when you have a minute. You're the best person to discuss options. Thanks

**Comment by angievanhegan** [comment]
@StephMSlack @ican-icant What did you guys agree with this?

**Comment by StephMSlack** [comment]
@angievanhegan we have had to leave this one as the layout changes due to the responsive nature of the styling. so this is fine.
