### ISSUE TITLE
Linking box links to view pages

### ISSUE THREAD

**Issue by dilwarhussain** [MantaRayMedia/bgs#199]
# Done criteria
- [ ] ~Link off to views pages for 'Policy & Media', 'Blog' & 'Resources' using box links~

**Comment by angievanhegan** [comment]
@pipe-manta is this still blocked?

**Comment by pipe-manta** [comment]
@russ-manta @angievanhegan The new flexible box links nugget is working, now is possible to combine entity reference with custom content on the same view.

http://bgs-dev.mrmdev.co.uk/pipe-new-box-links

**Comment by StephMSlack** [comment]
@angievanhegan this is fine
