### ISSUE TITLE
Event node (including tabs and concertinas for event content in Civi)

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#202]
- [x] TWEAK Fix right hand download link (see notes below)
- [x] TWEAK Fix repeating content blocks (see notes below)
- [x] TWEAK Add 'Session overview' as title (see notes below) 
- [ ] ~BLOCKER Can Veda hide excess cost tables~
- [ ] ~Style session information (concertina ok, but tabs very difficult)~
- [ ] ~ISSUE 1 Styling box links in content additional~
- [ ] ~Event node created with link to event in Civi (using CiviCRM entity)~
- [ ] ~Rule to create an unpublished Drupal node when a new CiviEvent is created with a Civi reference back to the CiviEvent~
- [ ] ~Title (from Civi or could use Drupal title if it matches the CiviEvent title)~ (This is brought through from civi when the event is created, can be updated on Drupal if needed)
- [ ] ~Date field - Civi~
- [ ] ~Location: link with text - Drupal~
- [ ] ~Social media - Drupal + ical icon with date from Civi?~
- [ ] ~Topics - Drupal~
- [ ] ~Download registration form - Drupal~
- [ ] ~Download Programme - Drupal~
- [ ] ~Contact - Civi~
- [ ] ~Who / Why / Poster information (*new) - Civi~
- [ ] ~Register now button - Drupal link & title to allow links to Civi, Events/external events and change text to eg. Add to wait list~
- [ ] ~Event terms and conditions - Drupal (link field)~
- [ ] ~Sponsors - Drupal~
- [ ] ~Region field - Drupal select list to show Region on upcoming events view filters~
- [ ] ~Credits - Civi (new custom fields)(Now Drupal field)~
- [ ] Organisation - Civi (Name), ~Drupal (logo)~
- [ ] ~Event - social programme (Custom Fields) - Evening Reception Information, Conference Run, Drinks Reception  (*new) - Civi~
- [ ] ~Rates - Civi (being added on Drupal)~
- [ ] ~Schedules - Civi~
- [ ] Submit abstract - Civi link to Civi page? (waiting for advise from veda on what to link to)

# Wireframes and Designs
- [Wireframe on the RT board](https://realtimeboard.com/app/board/o9J_k0NkHnc=/?moveToWidget=3074457345967174273)
- [Design - Event node](https://invis.io/B3GI8K9SP57) 
- [Design - Events landing](https://invis.io/8AFNAIKSM73)
- [Design - Events landing with filters](https://invis.io/U2GI8MXT67A

BGS would like to display the following fields from Civi within the event page:

1. Session title
2. Time 
3. Session name
4. Speaker name

See an [example](https://www.ageanaesthesia.com/programme)

This would require us to add some in page navigation - I'm suggesting a tab for each day and a show/hide for each session. The tabs would not be needed on a one day event. See wireframe below. 

![event page - 3 day](https://user-images.githubusercontent.com/3796718/38377865-ac17733a-38c1-11e8-8785-95df96c50821.png)

Please can you let me know if this could be included within scope. We have a total of 27 development days allocated to the event section (see [all events wireframes on the RT board](https://realtimeboard.com/app/board/o9J_k0NkHnc=/?moveToWidget=3074457345967174273)

**Comment by angievanhegan** [comment]
@russ-manta Can you estimate how much time in total this tabbed and show/hide navigation in this context would take? Thanks

**Comment by angievanhegan** [comment]
From Russ: I don't think we can quote properly until Veda have finished at least the first stage of events which they are due to do by the end of the week

**Comment by angievanhegan** [comment]
@russ-manta is Veda's stuff progressed enough to look at this issue yet? Thanks

**Comment by russ-manta** [comment]
Waiting on view from VEda to be able to show the schedule

**Comment by StephMSlack** [comment]
@dilwarhussain on the RHS nugget - we currently add abstract information as a content nugget, but that is getting pushed down the page with the logo/related links/programme etc. Is it possible to add abstracts in the overview section of the CMS as one of the links? Or is there another way we can get it to sit higher on the RHS?

**Comment by angievanhegan** [comment]
@dilwarhussain @russ-manta I this still blocked?

**Comment by russ-manta** [comment]
@daniellaveda is there any feedback on whether the costing tables at the top of an event can be hidden? Thanks
![bgs-sessions](https://user-images.githubusercontent.com/25846670/41604268-b2e47438-73d6-11e8-8a5d-f86611848753.jpg)

**Comment by daniellaveda** [comment]
Question is if we can split the price set out - sessions/fees

**Comment by daniellaveda** [comment]
@russ-manta 

Price options can be limited to sessions only - by applying more filters on child view (based on price field) on :
amount (== zero) and 
label (~Day).

Using regex on label to display even Symposium - Day|Symposium.

E.g - https://bgs-civicrm.vedacrm.co.uk/event-sessions/17. See screenshot:
![red-7806-views-eid17-only-sessions](https://user-images.githubusercontent.com/27422088/41723614-6f3cec2c-7563-11e8-863e-f9140d73481a.png)

**Comment by angievanhegan** [comment]
@dilwarhussain this is looking so much better! 

Is there any way that we could make this table full width? 

![screen shot 2018-06-25 at 12 22 20](https://user-images.githubusercontent.com/3796718/41865393-859d8442-7872-11e8-9b11-76af29efc987.png)

And remove the space between these tables? 

![screen shot 2018-06-25 at 12 23 14](https://user-images.githubusercontent.com/3796718/41865414-9a0b1b60-7872-11e8-996d-73b6ab78c22a.png)

**Comment by dilwarhussain** [comment]
@angievanhegan The top table is being pulled through from civi with widths already in the styles of the table. The gap between the other two tables are just in the content block. I deleted the space between the tables.

**Comment by angievanhegan** [comment]
@StephMSlack This is ready for you to to sign off. Thanks

**Comment by StephMSlack** [comment]
@angievanhegan @dilwarhussain I think some changes elsewhere may have caused the RHS programme download to fall over - 
![screen shot 2018-06-27 at 16 18 17](https://user-images.githubusercontent.com/32127102/41983411-e9465e06-7a25-11e8-8aa9-56f4612fad9d.png)

**Comment by StephMSlack** [comment]
@angievanhegan @russ-manta - for some reason the content blocks are repeating - even though they are only on the page once.

<img width="909" alt="screen shot 2018-07-03 at 22 38 45" src="https://user-images.githubusercontent.com/32127102/42245827-1ffe5b92-7f12-11e8-8823-75862809b577.png">
<img width="604" alt="screen shot 2018-07-03 at 22 39 14" src="https://user-images.githubusercontent.com/32127102/42245831-23f4dd84-7f12-11e8-9501-68a1c02af06e.png">

**Comment by StephMSlack** [comment]
@russ-manta When we pull the sessions through from the price sets, would it be possible to give them a title - Session Overview

![screen shot 2018-07-05 at 13 05 01](https://user-images.githubusercontent.com/32127102/42322416-58fabba0-8054-11e8-8980-35bec98d7b9d.png)

**Comment by russ-manta** [comment]
@StephMSlack all done
