### ISSUE TITLE
Headings in Video nugget not working in sticky nav

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#204]
The resource contains a content block and a video block. The titles are being taken from the title field for each nugget and displaying perfectly. Neither of the headings are appearing in the sticky nav on the right hand side. 

http://bgs-dev.mrmdev.co.uk/resources/patient-pathways-to-identify-unmet-need

**Comment by StephMSlack** [comment]
@angievanhegan @dilwarhussain thanks a lot, this is great
