### ISSUE TITLE
Style arrows for scrolling on contact page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#205]
These arrows should be styled in the same way as the results feed (pink): 

http://bgs-dev.mrmdev.co.uk/about/contact

![screen shot 2018-04-16 at 13 06 05](https://user-images.githubusercontent.com/3796718/38826952-fa181eaa-4176-11e8-8b2a-7fc8aef51a06.png)
![screen shot 2018-04-16 at 13 05 39](https://user-images.githubusercontent.com/3796718/38826953-fa331e62-4176-11e8-88de-74219d0d1ed4.png)

**Comment by dilwarhussain** [comment]
@StephMSlack Slider buttons have been styled.

**Comment by StephMSlack** [comment]
thanks @dilwarhussain
