### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#206]
# Done criteria
- [x] ~~TWEAK Make sure twitter feed shows BGS tweets~~
- [x] ~~TWEAK The feed under the membership banner runs off the page when on a mobile~~
- [x] ~~BLOCKER With Colin for review~~

# Designs & Docs
- [Design - version 6](https://invis.io/A4I94W3DU8X)

**Comment by angievanhegan** [comment]
@StephMSlack Over to you to get feedback from your team.

**Comment by angievanhegan** [comment]
@cat-manta What was the outcome of your conversation?

**Comment by mrm-git** [comment]
@pipe-manta No 'hand rollover' on Latest tabs

**Comment by pipe-manta** [comment]
@cat-manta Done the buttons with another colour on hover for all the promos

@ican-icant Hand cursor on hover ready

**Comment by angievanhegan** [comment]
@StephMSlack This is ready for you to review

**Comment by StephMSlack** [comment]
thanks @pipe-manta

**Comment by StephMSlack** [comment]
@angievanhegan - happy with how to change featured articles and that the look matches the design. 

The feed under the membership banner runs off the page when on a mobile
the twitter feed still links to MRM - I've updated the twitter # info, but still have your feed...

**Comment by StephMSlack** [comment]
@angievanhegan how do we fix the twitter feed?

**Comment by angievanhegan** [comment]
@pipe-manta One more for you. Thanks

**Comment by pipe-manta** [comment]
@StephMSlack I have requested on Slack your twitter login details, please don't include them here.

**Comment by pipe-manta** [comment]
@angievanhegan Twitter feed is displaying now @gerisoc tweets

**Comment by angievanhegan** [comment]
@StephMSlack This is ready for you to sign off

**Comment by StephMSlack** [comment]
@angievanhegan @pipe-manta when we pull through the tweets, could we remove the image/not show the image. It starts to look messy
![screen shot 2018-06-05 at 11 09 54](https://user-images.githubusercontent.com/32127102/40969968-284212ca-68b1-11e8-800b-bb4fb6ce845d.png)

**Comment by StephMSlack** [comment]
@pipe-manta is there any way that we can ensure that the bottom of the top left box (with the larger image) aligns with the bottom of the promo? I know the boxes are responsive so this may not be possible, but is there any way we can set the height so they align? 

![screen shot 2018-06-05 at 11 14 05](https://user-images.githubusercontent.com/32127102/40970249-ea2c128c-68b1-11e8-843e-f832d453d0fb.png)

**Comment by pipe-manta** [comment]
Hi @StephMSlack I have removed the images on the twitter feed.

**Comment by StephMSlack** [comment]
thanks @pipe-manta 
Any chance we can set the height of the boxes as we have done with the feeds on the Groups pages?
![screen shot 2018-06-07 at 11 11 11](https://user-images.githubusercontent.com/32127102/41093551-8858fd84-6a43-11e8-854c-32ce15925edb.png)

And is there anything we can do about the height of the boxes in the top section of the page?

**Comment by angievanhegan** [comment]
@pipe-manta Can you answer Steph's question please? Thanks

**Comment by pipe-manta** [comment]
Hi @StephMSlack On the curated links, at the moment only the left box can adapt the height when the boxes on the right are higher, but not on the other way. It's working to keep the consistency with the design and looks responsive.

We can create another solution with an extra development time, but losing the proportion 16:9 of the image on the left, in some cases, it will be cropped on the sides or top/bottom depending on the new responsive dimensions.

**Comment by angievanhegan** [comment]
@StephMSlack Let us know what you'd like us to do with this.

**Comment by StephMSlack** [comment]
@angievanhegan @pipe-manta lets leave it as it is for now and if I need you to do extra work following feedback from the team we can re-look at it then.

**Comment by StephMSlack** [comment]
@angievanhegan I'm happy with the function of this and how it is looking. We can close this as there is another ticket to add the event feed to the homepage
