### ISSUE TITLE
Search results not being displayed after using the back button

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#207]
If you:

> enter search criteria (e.g. type = e-learning) 
> then press search
> click search to look at the results
> click on a result
> then press the back button

The search criteria still displays, but you need to press search again to get the results again. You shouldn't need to press the search button again to see the filtered results. 

This happens on all search pages: News and policy and Blog

**Comment by pipe-manta** [comment]
Hi @angievanhegan, this is ready to check

**Comment by StephMSlack** [comment]
thanks @angievanhegan @pipe-manta
