### ISSUE TITLE
SIG join link behaviour

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/bgs#208]
# Done criteria
- [x] BLOCKED  SIG selection is via code on live on Civi profile 19 -  Need Veda to add this code up to the staging site/server
- [ ] ~Style checkboxes for SIG selection~
- [ ] ~If logged out the link should redirect the user to login and then onto the SIG join page once logged in~
- [x] Login to lvei to try and unpick

**Comment by russ-manta** [comment]
@daniellaveda could Veda upload/release this code to the staging server (from live) please?

**Comment by daniellaveda** [comment]
@russ-manta we spoke about this Wednesday - did you find the code in live?

**Comment by russ-manta** [comment]
![my-bgs-sigs](https://user-images.githubusercontent.com/25846670/41776801-0676e620-7621-11e8-8709-40bb33a83b56.jpg)

@daniellaveda I've just been having a look with the 'colin member' login I'm not really any the wsier (I might be being dumb!). Which template is used to embed the code?

**Comment by daniellaveda** [comment]
Code is here @russ-manta 
https://bitbucket.org/vedanfpconsultingltd/bgs/commits/dd2e2a99c1f32f3c4609b40472f81379bd1fd5c6

**Comment by russ-manta** [comment]
@daniellaveda thanks, got it.  @dilwarhussain could you have a look at styling the SIG checkboxes on this page: http://bgs-staging.mrmdev2.co.uk/user/1/edit/Personal_Details_28

For reference, this is how they look on the live mybgs site at the moment:
![bgs-sig-groups](https://user-images.githubusercontent.com/25846670/41926624-c9bd5044-7967-11e8-80e8-c1b7acad2f2f.jpg)

**Comment by StephMSlack** [comment]
@russ-manta when I am not logged in, the SIG button takes me to login, I login then get redirected to the personal details profile, except the profile is showing blank (as are the others)

![screen shot 2018-07-11 at 11 03 07](https://user-images.githubusercontent.com/32127102/42565004-2cf012c6-84fa-11e8-9146-7d78639a10b8.png)
It works correctly when I am already logged in

**Comment by russ-manta** [comment]
@StephMSlack please try this now

**Comment by StephMSlack** [comment]
thanks @russ-manta this is working now
@angievanhegan this is fine to close

**Comment by russ-manta** [comment]
SIG sign up checkboxes have gone

**Comment by russ-manta** [comment]
@StephMSlack now fixed

**Comment by StephMSlack** [comment]
thanks @russ-manta this is back and working. @angievanhegan this is good to close again
