### ISSUE TITLE
Members directory (search page)

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#209]
3 days in the proposal - Russ confirmed it should be do-able in 3 days

- [ ] ~ISSUE Change text on checkboxes and have checkboxes unchecked on page load~
- [ ] ~Blurb up top~
- [ ] ~Filters for users~
- [ ] ~Change placeholder text to 'search by name/title/hospital'~
- [ ] ~Filters for search results - add Region/Special Interest Group~
- [ ] ~Checkboxes for 'Research expertise' / 'Speaking'~
- [x] Auto complete on organisation (needs additional field)
- [ ] ~Auto complete on name in search field~
- [ ] ~Email function (one way, no storage of email, people can include their contact details in the message body~
- [ ] ~Add link to directory in About us section (Can use box link for this)~
- [x] Name and title of people in Civi may also be displayed on:
  - [x] Blog author details (on blog page)
  - [x] Resource author details (on resource page
  - [x] Committee member details (on BGS Group page)
- [ ] ~Where the person using the site is a member, the above details should appear as a link which takes them to the person's member page~

**Comment by angievanhegan** [comment]
Steph has confirmed this can go ahead. @dilwarhussain Let me know when you're reading to start this and I can explain everything

**Comment by StephMSlack** [comment]
@dilwarhussain Could you give me access to the member directory?

**Comment by StephMSlack** [comment]
@dilwarhussain the text in the search for the check boxes needs to change to 
Interest in research
interest in speaking at events.

Also these boxes are automatically ticked when I open the search + sign. The checkboxes should be empty until the user completes them

**Comment by StephMSlack** [comment]
@dilwarhussain is it possible to add some tags/interests to some of the users in the directory? I cannot access other contacts in Civi to do this myself, so I cannot check if the interests search works

**Comment by dilwarhussain** [comment]
@StephMSlack I've changed some permissions to allow you to edit contacts. Can you try again for me please, if it still doesn't allow I can add some tags to the users for you.

I've made a note about changing the filters.

**Comment by dilwarhussain** [comment]
I can see the same error as an admin actually, when clicking on 'edit' on the profile and making changes there. I've been using the inline editing on civi, so you just click on the field you want to change and make changes there (see below). 

<img width="1073" alt="screen shot 2018-06-07 at 11 38 26" src="https://user-images.githubusercontent.com/29142647/41094888-b12eea44-6a47-11e8-84d6-69fe9e373652.png">

I'll get @russ-manta to take a look at the error message when editing the whole profile.

**Comment by StephMSlack** [comment]
And here I was hoping I would get SUPER rights...
I can edit these now. thanks @dilwarhussain

**Comment by angievanhegan** [comment]
@StephMSlack Does that mean this can be closed? Thanks

**Comment by StephMSlack** [comment]
@angievanhegan not yet - The top point hasnt been completed - _the text hasn't been changed and the check boxes are still ticked._

**Comment by angievanhegan** [comment]
@dilwarhussain See Steph's comment above about the first TWEAK

**Comment by dilwarhussain** [comment]
@StephMSlack I've changed the text for the two filters. I've also had to change them from a single on off switch to a drop down list. Because the field in civi is created with multiple options, me trying to force it to display as a single on off switch was causing problems. Let me know if this is okay or if we need to continue looking at this.

**Comment by StephMSlack** [comment]
@dilwarhussain I've got 7 records in civi opted in to the directory but only 4 showing on the drupal page.
![screen shot 2018-06-28 at 14 45 44](https://user-images.githubusercontent.com/32127102/42038139-1e18c4e0-7ae2-11e8-8ace-53ba67132a37.png)
![screen shot 2018-06-28 at 14 47 07](https://user-images.githubusercontent.com/32127102/42038163-2be96eb2-7ae2-11e8-95c4-903687df94bd.png)

**Comment by StephMSlack** [comment]
@dilwarhussain the alignment of the search is out
![screen shot 2018-06-28 at 14 57 19](https://user-images.githubusercontent.com/32127102/42038837-d26d1972-7ae3-11e8-9388-9a23e9dfa3e2.png)

**Comment by StephMSlack** [comment]
@dilwarhussain @russ-manta - just checking the search - I have added the staging user to two SIGS but when I choose those SIGS in the search, I dont get any results.

![screen shot 2018-07-03 at 10 31 16](https://user-images.githubusercontent.com/32127102/42211821-631173da-7eac-11e8-94c0-5c12f37cc309.png)

![screen shot 2018-07-03 at 10 31 51](https://user-images.githubusercontent.com/32127102/42211826-6716c1a6-7eac-11e8-8a8b-361a8cf5cdcf.png)
![screen shot 2018-07-03 at 10 32 10](https://user-images.githubusercontent.com/32127102/42211832-69aa9d70-7eac-11e8-95e4-60f1440265fe.png)

**Comment by russ-manta** [comment]
@StephMSlack can you try again, seems to be wokring ok now

**Comment by StephMSlack** [comment]
@russ-manta I'm getting a page not found error when trying to click on the members directory

![screen shot 2018-07-17 at 14 20 34](https://user-images.githubusercontent.com/32127102/42819901-b5af032a-89cc-11e8-9265-4f6248949da6.png)

**Comment by StephMSlack** [comment]
@russ-manta once the link to the directory from the my account page is fixed, this is good to go.

**Comment by StephMSlack** [comment]
@russ-manta @angievanhegan one quick question - what is the default order for members to be displayed on the search page? Is it alphabetical by surname or something else?

**Comment by angievanhegan** [comment]
@dilwarhussain Can you help with Steph's question? ^

**Comment by dilwarhussain** [comment]
@angievanhegan @StephMSlack Yes this is using the 'Last Name' field from civi to sort.

**Comment by StephMSlack** [comment]
thanks @dilwarhussain
