### ISSUE TITLE
Become a member page

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/bgs#210]
# Done criteria
- [ ] ~TWEAK Steph can't access  join form/process unless logged in to the CMS.~
- [x] Recreate stepped workflow with webforms
- [x] Copy webforms over from the BGS staging site
- [x] Enable login without confirmation and add anti-spam
- [x] Fix direct debit not appearing in webform
- [ ] check payment amounts for retired member

# BGS review criteria
[Link to review goes here](http://)
- [ ] Check webform steps work correctly: http://bgs-dev.mrmdev.co.uk/bgs_membership

**Comment by russ-manta** [comment]
here is the form: http://bgs-dev.mrmdev.co.uk/bgs_membership

**Comment by StephMSlack** [comment]
@angievanhegan @russ-manta Thanks for moving this across.

At the moment I cannot access the join form/process unless logged in to the CMS.

There are some styling issues - @angievanhegan I've added them here, but let me know if they need to move elsewhere. 

Membership Rates Page

1. can we add a promo to the bottom of the form?
2. is it possible for BGS to edit this page? Not sure where it sits/how it is put together.
3. Linked to 2 - does the content need to sit in a table? Or can I display it in a different way?
4. Join button for each membership type is in white so cannot be seen. They should be pink buttons

Throughout the webform:
- more space required between the continue/restart buttons.
- where are you based - dropdown not resizing for content, choosing non-UK should redirect to a different page (this could be because I'm logged in)

**Comment by angievanhegan** [comment]
@dilwarhussain Steph can't access  join form/process unless logged in to the CMS.

**Comment by StephMSlack** [comment]
thanks @dilwarhussain I can now access this when not logged in.

**Comment by StephMSlack** [comment]
@dilwarhussain @angievanhegan I'm walking through the forms - should I add all comments on the forms to #247 or this issue?

**Comment by angievanhegan** [comment]
@StephMSlack Add them all here and we'll go through them later and maybe divide them out.

**Comment by StephMSlack** [comment]
@angievanhegan @conferences-BGS @dilwarhussain 
Stepping through the join form - can the table follow the design on the rest of the site? (remove the blue background for the header row) 
Could we remove the bold from the text 'please do not....' the text remains, but if it could use one of our header styles that would be great

![screen shot 2018-07-03 at 11 11 13](https://user-images.githubusercontent.com/32127102/42213902-f11b0c86-7eb1-11e8-9810-8d712044d215.png)

**Comment by StephMSlack** [comment]
@russ-manta @dilwarhussain this might link to the payment processor issue - but when people are joining we need to remove the pay later option from the form. (they can choose a pay later option over the phone but not online)
![screen shot 2018-07-03 at 11 35 37](https://user-images.githubusercontent.com/32127102/42215128-7163ca60-7eb5-11e8-8bd7-3712187af1aa.png)

**Comment by StephMSlack** [comment]
@russ-manta @dilwarhussain something seems to have gone wrong with the payment amount when I chose the option category A, retired member - the individual cost and the total should be the same amount

![screen shot 2018-07-03 at 11 51 29](https://user-images.githubusercontent.com/32127102/42215922-ed30cc68-7eb7-11e8-8a3b-8621cf09095e.png)

**Comment by StephMSlack** [comment]
@angievanhegan We are happy with the page and styling. The comments above link to the process of joining #247 so not sure if you want me to move these across and close this issue?

**Comment by russ-manta** [comment]
@StephMSlack I can't replicate the retired member issue, can you let me know which series of options you got to make this happen?

**Comment by StephMSlack** [comment]
I think since then I've had Daniella update the membership price sets (they change to 50% rate on the 1st July) which may have resolved the double up issue.

**Comment by StephMSlack** [comment]
@russ-manta I'm just trying the direct debit option now - do you know if it is configured to the smart debit test environment or the live environment

**Comment by conferences-BGS** [comment]
Live! Don't process any DD via staging

Geraint Collingridge. Sent from mobile

________________________________

**Comment by StephMSlack** [comment]
@russ-manta @angievanhegan the become a member page / join page is fine and good to be closed. Still discussion around the join process styling, but that is on another task.
