### ISSUE TITLE
Directory cards to appear on my account page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#214]
@StephMSlack In the original design or the 'my account page' we had cards displaying for members in the directory. If you'd like to include this functionality (in addition to there being a link to the member directory) Russ has estimated this at 1/2 day of development time £280 + VAT
                       
Let me know if you'd like to go ahead with this. 

- [ ] ~TWEAK  Make sure the members job title running off the end of the card~ (This wasn't happening for me, but I've added a word wrap, let me know if this is fixed)
- [ ] TWEAK If they have two hospitals listed, only showing the first (This is just one text field being pulled through from civi, whatever is in that field is what will display here, no way to split it up unfortunately)
- [ ] ~TWEAK reduce the space between the lines of text when a name runs onto a second line~
- [ ] ~TWEAK Directory should have a capital and could the text below read - members who share common interests with you~

**Comment by StephMSlack** [comment]
@angievanhegan yes we would like the member directory to show on the my account page. This does not need to include the member images (as we doubt there will be many images available and a row of avatars may look odd) but should include name and job title/organisation. 

Could you confirm what parameters you will use to decide which members to show? ie will it be location or similar specialty?

**Comment by angievanhegan** [comment]
@StephMSlack We suggest that it shows people in the same SIGs as you, in a random order. Then on refresh, you'd get another random group from this set. I suspect related interests is more important the geography. Let me know if this works for you and we'll confirm we can do it!

**Comment by StephMSlack** [comment]
@angievanhegan had a chat to geraint about this and he highlighted that many members choose to join multiple SIGs. so he wanted to know how the random criteria would be applied. eg seeing random members of the first alphabetical SIG they have joined, or randomly from all the SIGs they are a member of? Ideally we would choose from their list of interests (which they can highlight) but these have not been populated yet.
How easy/hard would it be to change the filter criteria at a later date (eg from SIG membership to location).

**Comment by angievanhegan** [comment]
@dilwarhussain Can you answer Steph's questions please? I can't!

**Comment by angievanhegan** [comment]
@StephMSlack Dilwar confirmed it'd be easy enough to change the filter criteria later on.

**Comment by StephMSlack** [comment]
@angievanhegan @dilwarhussain - is there a way to stop the members job title running off the end of the card? And if they have two hospitals listed, only showing the first? The card becomes very cluttered with more than that.
Could we reduce the space between the lines of text when a name runs onto a second line?
thanks!

**Comment by StephMSlack** [comment]
@angievanhegan @dilwarhussain could we also change the text slightly? Directory should have a capital and could the text below read - members who share common interests with you
Thanks

**Comment by angievanhegan** [comment]
@dilwarhussain Some tweaks listed out above. Thanks

**Comment by dilwarhussain** [comment]
@StephMSlack @angievanhegan Fixed with a few comments above.

**Comment by StephMSlack** [comment]
Thanks @dilwarhussain

**Comment by StephMSlack** [comment]
@angievanhegan this is fine to sign off
