### ISSUE TITLE
Make topics menu behave like Kings Fund topics menu

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#216]
Request from Steve

https://www.kingsfund.org.uk/

- [ ] ~TWEAK - Need to reduce the padding between items~
- [ ] ~TWEAK - Needs a few design tweaks @cat-manta (Steve will discuss with Cat)~
- [ ] ~TWEAK - No cursor needed on 'Topics' rollover cos you can't click it!~
- [ ] ~TWEAK - Cannot scroll screen when hovering on menu item~

**Comment by dilwarhussain** [comment]
@ican-icant Can you check the drop down on the main menu items now please.

**Comment by ican-icant** [comment]
@dilwarhussain @pipe-manta a few issues:
> Need to reduce the padding between items
> Needs a few design tweaks @cat-manta (i'll discuss with Cat
> No cursor needed on 'Topics' rollover cos you can't click it!
