### ISSUE TITLE
Add members directory to Member account page

### ISSUE THREAD

**Issue by dilwarhussain** [MantaRayMedia/bgs#217]
# Done criteria
- [x] TWEAK Synch
- [x] Search on full name in view
- [ ] ~TWEAK Ensure breadcrumb includes members's name (see comments below)~
- [ ] ~Add view to members page~
- [ ] ~Add Speaking/teaching expertise to header~
- [ ] ~Region can come off SIG group area at the bottom~
- [ ] ~Members should be able to contact other members. 'Get in touch' button should bring up~
- [ ] ~Can only contact members if you opt in to the members directory~
- [ ] ~If not a member of the directory, trying to message should ask you if you wish to opt into the directory.~
- [x] Don't show members directory view on other peoples' profiles

**Comment by StephMSlack** [comment]
@dilwarhussain I'm not sure what this links to/what I should be seeing. I don't seem to have access to the member directory either. Thanks Steph

**Comment by StephMSlack** [comment]
@dilwarhussain the Get in touch button shouldn't be on the my account page
![screen shot 2018-06-06 at 14 59 18](https://user-images.githubusercontent.com/32127102/41042804-7b70ed4c-699a-11e8-988d-422059f76c2d.png)

**Comment by dilwarhussain** [comment]
@StephMSlack Do you mean that shouldn't when looking at your own user account page?

**Comment by StephMSlack** [comment]
@dilwarhussain yes. when it pops up its sending an email to myself :). 

It made me think I could get in touch with the BGS. Could it be turned into a way to contact the BGS if it appears on your own My Account page? Not sure if that would be a simple or more complex thing...

**Comment by StephMSlack** [comment]
@angievanhegan not exactly sure what I am signing off - is this the pages users see once they have searched the member directory?

**Comment by StephMSlack** [comment]
@angievanhegan I think I need to access a couple of different logins and populate some more info about the users in Civi before I can be happy that this all works.

**Comment by dilwarhussain** [comment]
@StephMSlack I've made the contact button only appear on other users pagers. 

Also your account has opted in for directory member, I've changed the 'hussaind' account to not be opted in. Will these two accounts be okay to test the functionality?

**Comment by StephMSlack** [comment]
Thanks @dilwarhussain 
Could you let me know what page/system am I testing here? is it seeing other directory members, their directory page (layout and content pulling from CIvi) or something else?

**Comment by dilwarhussain** [comment]
Yes I think this is slightly similar/overlapping with #214 which is signed off. I think the main thing to test here is the functionality around messaging other directory members. You should get the form to message if you are a directory member, otherwise you should get a box saying you need to opt in to message other users.

**Comment by StephMSlack** [comment]
@dilwarhussain I've used an incognito window to sign in as you and test the member contact function.
In Civi your record (Helen Rodgers) has opted out of the directory but when I am signed using the helen rodgers account I can still contact users in the directory using the contact form.

**Comment by StephMSlack** [comment]
@dilwarhussain Are changes that are being made in CiviCRM on the members record updating in Drupal? I changed the member directory opt-out in Civi, but in Drupal you are still a directory member.

**Comment by dilwarhussain** [comment]
@StephMSlack Seems we lost the sync between this field and the role in Drupal when we updated the civi database. Just working on this now.

**Comment by StephMSlack** [comment]
@dilwarhussain Also, when I am logged in as me, then view a different contact in the member directory, the breadcrumb trail changes to welcome "Name of other contact"

This shouldn't happen (though is it happening now as I am a web admin? In which case we need to set up a basic member account for testing)

![screen shot 2018-06-11 at 11 31 49](https://user-images.githubusercontent.com/32127102/41227004-41935ea0-6d6b-11e8-9bb3-21d8e3950ea8.png)

**Comment by angievanhegan** [comment]
@dilwarhussain A tweak for you. Thanks

**Comment by russ-manta** [comment]
@StephMSlack @dilwarhussain I think the simplest thing for the breadcrumb would just be to remove 'Welcome' for all

**Comment by russ-manta** [comment]
@StephMSlack the members directory sync should now be working on staging

**Comment by StephMSlack** [comment]
@russ-manta 
I've joined as a student member. I've edited my account and become part of the members directory. But the member directory feed is not showing on my account page. 

Once logged in, I should also not see the join button at the top of the page, as I am already a member

![screen shot 2018-07-03 at 14 14 00](https://user-images.githubusercontent.com/32127102/42221891-9338760c-7ecb-11e8-9b42-ff774d67fbbc.png)

![screen shot 2018-07-03 at 14 14 00](https://user-images.githubusercontent.com/32127102/42221938-b3a48f3e-7ecb-11e8-9c81-e2fdd81781b1.png)

**Comment by russ-manta** [comment]
@StephMSlack the two issues above should now be fixed

**Comment by StephMSlack** [comment]
@russ thanks for the change. All members should see the member directory on the MyAccount landing page, even if the member hasn't opted in to share their details in the directory (they just cannot contact other members through the directory). 

At the moment if I havent opted into the directory it doesnt appear on the My account page

Once I opt in to the directory, the member director feed appears on the MyAccount landing page.

Opted out of directory
![screen shot 2018-07-11 at 13 34 56](https://user-images.githubusercontent.com/32127102/42571834-0cbd6f74-8510-11e8-8a39-bd0517024952.png)

opted in
![screen shot 2018-07-11 at 13 42 10](https://user-images.githubusercontent.com/32127102/42571905-3ef750cc-8510-11e8-80fb-9a28097ae504.png)

**Comment by russ-manta** [comment]
@StephMSlack fixed - now appears for all members
