### ISSUE TITLE
Check events cards on feeds

### ISSUE THREAD

**Issue by dilwarhussain** [MantaRayMedia/bgs#222]
# List of views
- [ ] ~Home page featured (Latest)~
- [ ] ~Home page header (Curated links)~
- [ ] ~Home page (Nugget)~
- [ ] ~Topics~
- [ ] ~Resources 'You may be interested in'~ They don't appear here, only resources.

**Comment by dilwarhussain** [comment]
Create concatenated conditionals to print 'Resource type', 'Event type' or content type.

**Comment by angievanhegan** [comment]
@StephMSlack These have all been checked now.

**Comment by StephMSlack** [comment]
thanks @angievanhegan
