### ISSUE TITLE
Header and menu updates

### ISSUE THREAD

**Issue by cat-manta** [MantaRayMedia/bgs#224]
# Done criteria
- [x] ~Mobile - move 'Join' and 'Blog' buttons to dropdown menu when logged in~
- [x] ~Desktop - menu dropdown has an active state design, and general design has been updated~

# Designs & Docs
- [Mobile logged in header](https://invis.io/4EDQ458R5#/296384372_Home-Mobile-3)
- [Desktop menu dropdown](https://invis.io/4EDQ458R5#/289094992_Topics-Menu-V0-1)

**Comment by StephMSlack** [comment]
@angievanhegan the design change is fine.
The blog/join buttons on mobile are in the dropdown menu when logged out as well as when logged in.
