### ISSUE TITLE
Redirect to privacy page after login

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/bgs#226]
# Done criteria
- [ ] For GDPR redirect to a page to accept the privacy policy when logging in for the first time, keep redirecting here until privacy policay checkbox has been accepted
- [ ] ?

# Designs & Docs
- [Link goes here](http://)
- [Link goes here](http://)

# BGS review criteria
[Link to review goes here](http://)
- [ ] ?
- [ ] ?
- [ ] ?

**Comment by StephMSlack** [comment]
@angievanhegan @russ-manta - See slack discussion below. Colin has decided that BGS do not need users to sign up to the privacy policy when first logging in, so this task can be removed from the backlog.

Steph

Russ [1:23 PM]
@Steph @G are you creating a privacy page/form which we can redirect to after login?

G [3:06 PM]
@Daniella please can you share the GDPR module information with Russ. The privacy policy is 95% complete

Daniella [3:18 PM]
@Russ docs for GDPR can be found here: https://docs.civicrm.org/gdpr/en/latest/configuration/ Let me know if you need anything else

Russ [3:25 PM]
@Daniella thanks @G is the idea that you/we will create a webform with a copy of the data policy on it that users will check a box to agree to?

G [10:24 AM]
@Russ The GDPR module in Civi provides a record of contacts accepting the privacy policy to be used for new subscribers/ event attendees or members. BGS have decided that we will not require every member or user to agree to the data privacy policy, but will send an email to advise them of the update and ask them to update their preferences in Civi

G [10:27 AM]
There will need to be a webpage on Drupal that holds the four legal statements:
1. Website terms of use
2. Privacy Statement
3. Membership terms and conditions
4. Event terms and conditions

G [10:27 AM]
Colin has consulted with legal and the need for privacy policy to be read and accepted not required: Civi can do this if needed

**Comment by russ-manta** [comment]
no longer needed - from steph ' Due to Colin’s decision we no-longer require users to be redirected to the privacy policy when first logging into the website. So this issue can be removed from the github list. FYI'
