### ISSUE TITLE
Past events

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/bgs#230]
# Done criteria
- [ ] TWEAK the event summary from Civi should remain on the page when the event expired.
- [ ] ~Register and download links on top right should be removed when date is in past~
- [ ] ~Hide view of where\what\rate etc + any other fields not present in past events wireframe according to if date is past~
- [ ] ~Show programme info~
- [ ] ~Post event content - Drupal (Content block nuggets?)~
- [ ] ~Book of abstracts - Drupal PDF upload/link to file within the website~
- [ ] ~Related events - Drupal, show upcoming events related by topic. Possibility to have this as a curated like resources (need to quote this)?  If too much work then no curated option~

# Wireframes and Designs
- [Wireframe on the RT board](https://realtimeboard.com/app/board/o9J_k0NkHnc=/?moveToWidget=3074457345967174273)
- [Design - Event node](https://invis.io/B3GI8K9SP57) 
- [Design - Events landing](https://invis.io/8AFNAIKSM73)
- [Design - Events landing with filters](https://invis.io/U2GI8MXT67A)

**Comment by angievanhegan** [comment]
@StephMSlack This is ready for you to review: http://bgs-dev.mrmdev.co.uk/events/past-events

**Comment by StephMSlack** [comment]
@dilwar - could we keep the event summary field in the past event content?

**Comment by StephMSlack** [comment]
@dilwarhussain How do we show the related events? do we need to add them or do they appear automatically (as with resources) and if so, are they linked to topics?

**Comment by dilwarhussain** [comment]
@StephMSlack We can keep the event summary. The related events should be working automatically now, just need some styling to finish off.

**Comment by StephMSlack** [comment]
@dilwarhussain yes please, they should have exactly the same filters as the upcoming events page

**Comment by dilwarhussain** [comment]
@StephMSlack The past events view now has the same filters as upcoming.

**Comment by angievanhegan** [comment]
@dilwarhussain There was a tweak here that I missed. See your comment on 12 June.

**Comment by dilwarhussain** [comment]
@StephMSlack Made the change to keep the event summary after the event has passed.

**Comment by StephMSlack** [comment]
thanks @dilwarhussain @angievanhegan I'll close this again
