### ISSUE TITLE
Events landing page

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/bgs#231]
# Done criteria
- [ ] ~Add filter for date (Need rule to populate Drupal date field before this can be done)~
- [ ] ~Add filters for topics, Region, City~
- [ ] ~Search by name~
- [ ] ~Event type on Card - from Civi~
- [ ] ~City field on card - from Civi~
- [ ] ~Coverage - is this required? If so perhaps add a coverage checkbox to the event content type~

# Designs & Docs
# Wireframes and Designs
- [Wireframe on the RT board](https://realtimeboard.com/app/board/o9J_k0NkHnc=/?moveToWidget=3074457345967174273)
- [Design - Event node](https://invis.io/B3GI8K9SP57) 
- [Design - Events landing](https://invis.io/8AFNAIKSM73)
- [Design - Events landing with filters](https://invis.io/U2GI8MXT67A

**Comment by angievanhegan** [comment]
@StephMSlack This is ready for you to review

http://bgs-dev.mrmdev.co.uk/events

**Comment by StephMSlack** [comment]
@dilwarhussain could you let me know when you have had a chance to add the date filters for the search?

**Comment by dilwarhussain** [comment]
@StephMSlack The event type label is being pulled in from civi. 
I will let you know when the date filters are added.

**Comment by dilwarhussain** [comment]
@StephMSlack The date filters are now working.

**Comment by StephMSlack** [comment]
@dilwarhussain sorry I didnt notice this before - could we have the date fields on the right of the search and the other fields in the left column? Then we have consistency regarding how the search looks across events/Media & Policy/Resources.

Otherwise, happy with the styling and information. We will be updating the event labels in Civi once the staging version is installed on your server (annual spring/autumn conference doesnt look that good!)

![screen shot 2018-06-13 at 10 07 22](https://user-images.githubusercontent.com/32127102/41341430-97c42b88-6ef1-11e8-93a2-30d5618ac6a5.png)

**Comment by dilwarhussain** [comment]
@StephMSlack Filters are consistent with Resources etc. now.

**Comment by StephMSlack** [comment]
thanks @dilwarhussain 

@dilwarhussain since the site move on Monday, we are now getting the event heading showing below the cards
![image](https://user-images.githubusercontent.com/32127102/41693360-f6f34b5c-74d2-11e8-8a0c-fb711e7b9aad.png)

**Comment by StephMSlack** [comment]
@angievanhegan I'm having trouble adding events to Civi at the moment, so until I can add new events to the system and check how things look (eg that the scrolling and pagination work) I wont be able to sign this off

**Comment by StephMSlack** [comment]
@dilwarhussain we are getting past events still appearing in the upcoming events section.
![screen shot 2018-06-28 at 12 53 24](https://user-images.githubusercontent.com/32127102/42032711-60bfa756-7ad2-11e8-99a5-b04266cd07a0.png)

**Comment by dilwarhussain** [comment]
@StephMSlack The end date for these (which is now showing on the card) for these are 30 june and august.

**Comment by StephMSlack** [comment]
@dilwarhussain do you need us to add the region of the event in drupal or are you pulling this information over from Civi? (I was checking the search was working)

**Comment by dilwarhussain** [comment]
@StephMSlack yes the region is to be set in Drupal so we have a specific set we can choose from.

**Comment by StephMSlack** [comment]
thanks @dilwarhussain 
@angievanhegan this is fine. I cannot check if the show more function (the small blue arrow) is working until we have more events in place, but otherwise this is good to go
