### ISSUE TITLE
Intro text and member sign up on Members Directory page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#236]
# Done criteria
- [x] Add editable text field at the top of the members directory page
- [x] Enable members to join the directory from the members directory page (it'll also need to show if you're already a member or not) - now being done via a civi profile on my account

**Comment by StephMSlack** [comment]
@angievanhegan @russ-manta - yes this is what we need. thanks

**Comment by StephMSlack** [comment]
@russ-manta Just confirming the opt in process with Geraint. It may be as simple as a link to the civi profile that the user needs to update in the My Account section.

**Comment by StephMSlack** [comment]
thanks @angievanhegan @russ-manta this is fine and good to go

@angievanhegan FYI I added a note on slack about the profiles users see, which links to the use of the membership details profile mentioned above
