### ISSUE TITLE
Add events to home page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#237]

**Comment by angievanhegan** [comment]
@pipe-manta Why is this blocked? Can it be done now?

**Comment by dilwarhussain** [comment]
There is a specific feed that needs to be selected on the homepage to display this view.

**Comment by StephMSlack** [comment]
@dilwarhussain does this feed only show the 3 next events? We need to be able to use this to promote specific events as well - eg the Autumn Meeting should be on the home page even if there are 5 smaller events taking place before this.

**Comment by dilwarhussain** [comment]
@StephMSlack There is now a 'Featured homepage events' nugget where you can pick which events show on the feed and also where it should be placed on the homepage.

**Comment by StephMSlack** [comment]
thanks @dilwarhussain

**Comment by StephMSlack** [comment]
@dilwarhussain when we re-order the events in the CMS, the display on the homepage is not changing.

order within the nugget
<img width="623" alt="screen shot 2018-06-21 at 21 59 35" src="https://user-images.githubusercontent.com/32127102/41754078-cf218dce-759e-11e8-88ff-3a503d1e8d8a.png">

order on homepage view
<img width="1280" alt="screen shot 2018-06-21 at 21 59 55" src="https://user-images.githubusercontent.com/32127102/41754099-ec1d08e0-759e-11e8-92f8-1c3f5bda231d.png">

**Comment by dilwarhussain** [comment]
@StephMSlack Order is being reflected on the homepage now.

**Comment by StephMSlack** [comment]
thanks @dilwarhussain 
@angievanhegan this is fine to sign off and close
