### ISSUE TITLE
Not all roles to be displayed on Account page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#241]
Where a person is a member of a SIG, it doesn't need to be shown, it's only intended to show if people are a chair, secretary etc. 

![Screen Shot 2018-05-24 at 08.55.02.png](https://images.zenhubusercontent.com/596d095761b4ca3b0a74b803/b5e9d9a7-f63f-4720-a65d-db077e6b6424)

**Comment by angievanhegan** [comment]
@StephMSlack can you confirm that this is correct?

**Comment by StephMSlack** [comment]
@angievanhegan yes this is correct - for the BGS roles we just want to show if they are a 
committee member (chair/secretary etc)

**Comment by dilwarhussain** [comment]
@StephMSlack Attached is the full list of relationship types being used in civi. Can you tell me which ones you would like me to limit the BGS roles list to please, thanks.

[bgs_roles.txt](https://github.com/MantaRayMedia/bgs/files/2053235/bgs_roles.txt)

**Comment by StephMSlack** [comment]
@dilwarhussain just confirming this with Geraint will get back to you soon

**Comment by StephMSlack** [comment]
@dilwarhussain here is the updated list. 
[bgs_roles.txt](https://github.com/MantaRayMedia/bgs/files/2053528/bgs_roles.txt)

Are the fields being displayed as in the doc? if so, we may need to do some editing so they make sense from a user point of view (eg changing PAC to policy and communications). Will renaming the fields impact what you are doing?

**Comment by StephMSlack** [comment]
thanks @dilwarhussain 
i'm getting a number of error messages on my login of the my account page, so cant see the changes at the moment

**Comment by StephMSlack** [comment]
thanks @dilwarhussain 
Is there anyway that we can put a hyphen in when you show two fields? Eg Secretary of SIG - Anaemia. It would just make the text read better. Most of the other fields in the relationship list are singular and wouldn't need it.

**Comment by dilwarhussain** [comment]
@StephMSlack I've added a hyphen in between.

**Comment by StephMSlack** [comment]
thanks @dilwarhussain 

Also, we dont need to show the speaking/research expertise fields on this page, only for the members directory

**Comment by dilwarhussain** [comment]
@StephMSlack Gone!

**Comment by StephMSlack** [comment]
thanks @dilwarhussain

**Comment by angievanhegan** [comment]
@StephMSlack Can this be signed off now?

**Comment by StephMSlack** [comment]
Yes @angievanhegan
