### ISSUE TITLE
Topics link from Resources, News, Policy, Groups and Events to link to relevant topic page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#242]
At the moment, they all link to search results showing only the same type of content (e.g. link on resource page shows all resources with the same topic). Now that we have topic pages, please can these links go directly to them? 

- [x] ~Resources~
- [x] ~News and Policy~
- [x] ~Blog~
- [x] ~Group pages~
- [ ] ~Events~

**Comment by angievanhegan** [comment]
@dilwarhussain Please let me know if this isn't a quick job. Thanks

**Comment by dilwarhussain** [comment]
@StephMSlack Topics are now linking to the topic page.

**Comment by StephMSlack** [comment]
thanks @dilwarhussain this is great

**Comment by angievanhegan** [comment]
@StephMSlack This is done. you can move it to closed once you've checked it. Thanks
