### ISSUE TITLE
New promos not becoming parallax by default

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#243]
Let me know if there's actually something that the editors should be doing. Thanks

**Comment by dilwarhussain** [comment]
@StephMSlack Can you send me a link to a node where this isn't working please. Just added a promo to this test page and it looks okay to me: http://bgs-dev.mrmdev.co.uk/dh-page-test

**Comment by StephMSlack** [comment]
@dilwarhussain it is the one on the homepage (autumn meeting) and the membership directory - but I cannot remember where I put it!

**Comment by StephMSlack** [comment]
@dilwarhussain and typically, I've added the member directory to http://bgs-dev.mrmdev.co.uk/about/why-we-do-it and it is parallax now....
