### ISSUE TITLE
Styling issue on costs table

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/bgs#246]
# Done criteria
- [x] TWEAK Issue still occurring in [other places](http://bgs-dev.mrmdev.co.uk/events/british-geriatrics-society-spring-meeting-2019) see notes below
- [x] Under FAQ section
http://bgs-dev.mrmdev.co.uk/about/become-a-member

**Comment by angievanhegan** [comment]
@StephMSlack This is ready for you to sign off. You can close it.

**Comment by angievanhegan** [comment]
@dilwarhussain I've added a TWEAK

**Comment by dilwarhussain** [comment]
@angievanhegan @StephMSlack This is fixed now.

**Comment by StephMSlack** [comment]
thanks @dilwarhussain
