### ISSUE TITLE
Style pages in the 'join' process

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#247]
These are Civi pages so probably won't be able to look quite as styled as the rest of the site, but we should do what we can. Steve will advise on how much we'll do. 

http://bgs-dev.mrmdev.co.uk/civicrm/membership-rates

Steph will confirm what to do with the banner on the first page.

**Comment by angievanhegan** [comment]
@dilwarhussain This is in the scope of the proposal Dilwar. I suggest we do the styling we can, then review it with Steve. Let me know if you want me to organise that. Thanks

**Comment by angievanhegan** [comment]
@dilwarhussain some comments from Steph: 

There are some styling issues - @angievanhegan I've added them here, but let me know if they need to move elsewhere.

Membership Rates Page

can we add a promo to the bottom of the form?
is it possible for BGS to edit this page? Not sure where it sits/how it is put together.
Linked to 2 - does the content need to sit in a table? Or can I display it in a different way?
Join button for each membership type is in white so cannot be seen. They should be pink buttons
Throughout the webform:

more space required between the continue/restart buttons.
where are you based - dropdown not resizing for content, choosing non-UK should redirect to a different page (this could be because I'm logged in)

**Comment by dilwarhussain** [comment]
@angievanhegan I haven't done any styling on these pages yet, but will keep this in mind. Thanks.

**Comment by dilwarhussain** [comment]
@StephMSlack Is there a specific promo you'd like to show on the 'Membership Rates' page? It's not a Drupal page so unfortunately you won't have the flexibility of nuggets, but I should be able to add a specific promo to the page manually.

**Comment by StephMSlack** [comment]
@dilwarhussain I'd have to create one for you. I'll look at doing that now. Is this page editable for the BGS staff? The membership rates all change to 50% discount on the 1st July, so we'll need to be able to change the content then...

**Comment by StephMSlack** [comment]
@dilwarhussain could you use the become a member promo - http://bgs-dev.mrmdev.co.uk/become-a-member

**Comment by StephMSlack** [comment]
@dilwarhussain when you get to the option to join a group, we are getting a lot of extra options (Veda Scratch Group etc) which are the smart groups. 
This should show the Organisations - SIG (will show as ORGSIG) and for anyone who joins as a GP member, we need to show BGSGroup.

**Comment by StephMSlack** [comment]
@angievanhegan Could we update the text on the membership confirmation page? I am happy to do this if you can tell me where. If not, text is below:

 
Thank you for your application to join the British Geriatrics Society.

Your application has been accepted subject to review by the membership team and you will receive an email confirmation shortly.

You will be able to register for our events at the members reduced rate immediately and access member only content, including the Age and Ageing journal if this is included in your subscription.
 
If you do not receive and email from us, or if you have any queries please contact Membership@bgs.org.uk or call 0203 747 6942.
 
Welcome to the British Geriatrics Society

**Comment by russ-manta** [comment]
@StephMSlack I've changed the confirmation message at the end.  You should be able to edit it too: http://bgs-staging.mrmdev2.co.uk/node/298/webform/configure

**Comment by StephMSlack** [comment]
@russ-manta walking through the join form - tried the Advanced clinical practitioner option and when I got to the payment I should have been able to pay by card and Direct debit, but I only received the card payment option,

I had a look in the civi join matrix and DD payment should be enabled. Would you mind having a quick look?

Screen shots
![screen shot 2018-07-05 at 10 03 46](https://user-images.githubusercontent.com/32127102/42313499-d776e126-803a-11e8-86d8-463bb5e4f509.png)
![screen shot 2018-07-05 at 10 05 09](https://user-images.githubusercontent.com/32127102/42313542-ee2aca54-803a-11e8-934a-7ee6d2da2ef5.png)
![screen shot 2018-07-05 at 10 14 54](https://user-images.githubusercontent.com/32127102/42314154-53c6cd76-803c-11e8-8e99-5d5e2d810f37.png)
![screen shot 2018-07-05 at 10 15 27](https://user-images.githubusercontent.com/32127102/42314183-63ee714a-803c-11e8-9cbe-aee963aeb109.png)

**Comment by StephMSlack** [comment]
@russ-manta cab we make the T&C field mandatory, and is it possible for this to be a link to our Membership T&C on the website?

**Comment by russ-manta** [comment]
@StephMSlack direct debit is now fixed.  I've made T&C's required and added some text with a link to the terms and conditions

**Comment by StephMSlack** [comment]
@russ-manta The last page in the webform is not pulling the address or job title through from Civi. If this something for you or for Veda?

![image](https://user-images.githubusercontent.com/32127102/42811531-bb2a2e2a-89b2-11e8-9275-8bceee396c8b.png)

Also, Geraint would like to make a small change to the help text. Are you happy to give me access to the webform to change it? Or, it is the helptext for the journal

New text 
Category A and C – the Age and Ageing journal is mandatory.
Category B – the Age and Ageing journal is optional.
If you choose Category B: GPs, Nurses & AHPs (without Journal) Standard Benefits you would not receive the journal and if you  choose Category B: GPs, Nurses & AHPs (with Journal) Enhanced Benefits you would receive the journal

Current text
Category A and C – the Age and Ageing journal is mandatory.
Category B – the Age and Ageing journal is optional, if you are choosing Category B: GPs, Nurses & AHPs (without Journal) Standard Benefits you would not receive the journal and if you are choosing Category B: GPs, Nurses & AHPs (with Journal) Enhanced Benefits you would receive the journal
For all free membership categories – the Age and Ageing journal is not included as part of your membership

**Comment by russ-manta** [comment]
@StephMSlack here's where you can edit the text: http://bgs-staging.mrmdev2.co.uk/node/298/webform/components/37?destination=node/298/webform I'll await your s and veda's feedback on the address and job title fields before making any changes there

**Comment by StephMSlack** [comment]
@russ-manta my access to the webform has been removed :( Could you upgrade my permissions?

**Comment by russ-manta** [comment]
@StephMSlack try now

**Comment by StephMSlack** [comment]
@russ-manta I'm getting an error now
![screen shot 2018-07-17 at 14 03 06](https://user-images.githubusercontent.com/32127102/42819029-42ca45ce-89ca-11e8-94ef-a1cf6fa267a2.png)

**Comment by russ-manta** [comment]
@StephMSlack that error is now fixed but it might be quicker for me to edit the text on the form - can you send me the text please?

**Comment by StephMSlack** [comment]
thanks @russ-manta 
The text is linked to the Journal help text

New text
Category A and C – the Age and Ageing journal is mandatory.
Category B – the Age and Ageing journal is optional.
If you choose Category B: GPs, Nurses & AHPs (without Journal) Standard Benefits you would not receive the journal and if you choose Category B: GPs, Nurses & AHPs (with Journal) Enhanced Benefits you would receive the journal

**Comment by russ-manta** [comment]
@StephMSlack  thanks this has now been changed

**Comment by StephMSlack** [comment]
thanks @russ-manta

**Comment by StephMSlack** [comment]
@russ-manta - a small thing - the text has managed to repeat itself in the first line. So in the first line remove from 'Category B to optional' and all category B info should be on line 2.
<img width="1248" alt="screen shot 2018-07-26 at 14 16 14" src="https://user-images.githubusercontent.com/32127102/43264770-df7b86a6-90de-11e8-8a11-a30dd626b4d6.png">

**Comment by russ-manta** [comment]
@StephMSlack done

**Comment by StephMSlack** [comment]
thanks @russ-manta 
@angievanhegan we can close this one now :)
