### ISSUE TITLE
Ensure people can add themselves to the members directory

### ISSUE THREAD

**Issue by dilwarhussain** [MantaRayMedia/bgs#249]
# Done criteria
- [x] TWEAK Add membership number to account page
- [x] BLOCKED WE're missing a profile for this - Civi profiles with membership fields don't seem to display on Drupal user tabs - this occurs in both Veda and Manta Ray staging sites
- [x] Check manage my account page to include the 'opt in to the members directory checkbox'.
- [x] Ensure blocks on my account page display according to members directory membership, may need to change template / views (check page--user.tpl.php file and also member directory related block view

**Comment by russ-manta** [comment]
@daniellaveda could someone take a look at why Civi profiles with membership fields within them do not show up as tabs on the Drupal user account?  Seems to affect your staging environment and ours

**Comment by daniellaveda** [comment]
@russ-manta 
Any profile of type other than contact or individual will not work with drupal user account (due to the fact there could be multiple possible memberships)

Profile ID 24 is membership profile, and because contact could have multiple memberships, profile won't work with user account.

I think possible solutions for memberships are:
1. use views to display membership related information, and expose it as tab.
2. create custom tab like payment history.

**Comment by russ-manta** [comment]
@daniellaveda Thanks, ok I think we should remove those items from the Civi profile then as it seems a bit odd to have items there that they can't shouldn't edit anyway and we are already pulling membership number etc through on the RH sidebar on the user profile: http://bgs-staging.mrmdev2.co.uk/user

**Comment by russ-manta** [comment]
@StephMSlack  to get this profile to work under manage my account we've had to remove the fields that were showing membership info such as membership type etc. Most of this is already being on the account page anyway  http://bgs-staging.mrmdev2.co.uk/user . We are still showing the membership number of the profile but perhaps this could be moved to the my account page too?
The fields we have had to remove are these ones as shown on the veda staging site: https://bgs-civicrm.vedacrm.co.uk/civicrm/admin/uf/group/field?reset=1&action=browse&gid=24

**Comment by StephMSlack** [comment]
@russ-manta thanks for the update. The change to the profile is fine. You suggested adding the membership number to the My Account page as well - could we go ahead with this please?

**Comment by angievanhegan** [comment]
@StephMSlack I'm assuming that having the membership number on the account page isn't essential for go live so I've removed the 'for go live' label and put this in the backlog.

**Comment by russ-manta** [comment]
@StephMSlack the membership number has now been added to the RHS on the my account page

**Comment by StephMSlack** [comment]
@russ-manta - i'm getting 2 different IDs
my account page
<img width="1280" alt="screen shot 2018-09-06 at 14 58 41" src="https://user-images.githubusercontent.com/32127102/45162275-831ad100-b1e5-11e8-98e6-cf4ff2f820cd.png">

Membership details tab
<img width="1280" alt="screen shot 2018-09-06 at 14 58 34" src="https://user-images.githubusercontent.com/32127102/45162291-8c0ba280-b1e5-11e8-8b71-b75a99b40df6.png">

ID in Civi
<img width="1280" alt="screen shot 2018-09-06 at 15 00 31" src="https://user-images.githubusercontent.com/32127102/45162339-a6de1700-b1e5-11e8-8ed0-52303eebda9f.png">

**Comment by StephMSlack** [comment]
thanks @russ-manta
