### ISSUE TITLE
Research and start design process

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#25]
# Done criteria
- [x] Talk to Angie to work out what the done criteria are for this task
- [x] Decide on style guide approach
- [ ] Had a meeting with Mar Munoz
- [x] Create style guide 'template' (based on example Cat found) [link here](https://invis.io/4EDQ458R5)
- [x] Add info from BGS branding guidelines to style guide (colours, fonts etc)
- [ ] Read a book?
- [x] Gather requirements with Steve
- [ ] Make a note of likes and dislikes on competitors' websites
- [x] Create moodboards

# For BGS review
- [ ] Happy with iterative approach to design?

**Comment by angievanhegan** [comment]
Hi @cat-manta - I've created this task as part of this first setup sprint. As you can see from the 'done criteria' - I'm not totally sure what we should put in this one. Do you want to call me when you've got a minute and we can talk it through and work it out together. It's fine to work this out as we go. You're a brilliant designer, so it will all be fine - all we're changing here is the approach 😊  This sprint may be mostly about research Style Guides so you have an idea of what would work.

**Comment by cat-manta** [comment]
@angievanhegan Yes sure, I'll probably be available for a call anytime today, so just give me call whenever you're free :)

**Comment by cat-manta** [comment]
@angievanhegan What does 'Add info from BGS style guide to MRM style guide' mean?

**Comment by angievanhegan** [comment]
@cat-manta good questions! I meant adding things like the colours and fonts and anything else that's useful. Logo's and their restrictions perhaps. Basically, taking whatever you can out of the print style guidelines and transferring it across to the Digital Style guide.

**Comment by angievanhegan** [comment]
@cat-manta Please could you add a link to the style guide template in here when you're ready? Thanks

**Comment by angievanhegan** [comment]
@cat-manta  Please could you add a link to the style guide template in here when you're ready? Thanks

**Comment by cat-manta** [comment]
@angievanhegan Ahh I see, so you mean copy things from BGS' branding guidelines to the style guide that we're creating?
And sure.
