### ISSUE TITLE
Enable ordering of groups changes

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#252]
Need to be able to control the order of the Professional groups as they appear on the BGS Groups landing page. 

If it's easier, the change can be applied to the SIGs too.

**Comment by angievanhegan** [comment]
@russ-manta Is there any way that this is quicker to do than to quote?

**Comment by angievanhegan** [comment]
@russ-manta Colin would like this for Go Live too. Please can you provide a costing? thanks

**Comment by russ-manta** [comment]
@StephMSlack @angievanhegan  we can probably do this without quoting but  it's slightly lower priority at the moment compared to other go live items

**Comment by russ-manta** [comment]
@StephMSlack this is now done.  If you go to one of the professional group pages (eg. http://bgs-staging.mrmdev2.co.uk/nurse-and-ahps-council)and then click on the nodequeue tab (eg. http://bgs-staging.mrmdev2.co.uk/node/3324/nodequeue )

Click on the BGS groups link and you can then reorder the groups in the list.  Make sure you click the 'Save'button after making any changes and these will then be reflected on the Groups landing page

**Comment by StephMSlack** [comment]
Thanks so much @russ-manta 
@angievanhegan this is fine to close
