### ISSUE TITLE
Remove white background from box links within additional content

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#256]
(feedback from Steve)

These box links shouldn't be on a white background. 
http://bgs-dev.mrmdev.co.uk/about

Do you think it's because they had to do them within Additional Content and not in Main content? (they're not available there)

Thanks

**Comment by dilwarhussain** [comment]
@angievanhegan Putting these in the postscript region fixes this. Have a look on the page, I've added some under the additional region. Main content and Additional content always have white backgrounds as thats the main content region.

**Comment by angievanhegan** [comment]
@dilwarhussain Thanks - I didn't know that. All sorted now.
