### ISSUE TITLE
Group pages not appearing in search results 

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#257]
Group pages are not coming up in the search

**Comment by dilwarhussain** [comment]
@angievanhegan Should be able yo find groups in site search now. http://bgs-dev.mrmdev.co.uk/search/node

**Comment by angievanhegan** [comment]
@dilwarhussain I tried looking for this and it didn't come up.
Nurse and AHP council

**Comment by dilwarhussain** [comment]
Works fine for me, logged in and out. I've flushed the caches. Could try once more for me please!

![screen shot 2018-06-13 at 09 59 53](https://user-images.githubusercontent.com/29142647/41341023-9895638e-6ef0-11e8-926b-d786887d6815.png)

**Comment by StephMSlack** [comment]
@dilwarhussain @angievanhegan sorry, this isnt working for me
Ideally the user should see the group, even if they just type Nurse (and then see the Nurse and AHP Council)

**Comment by angievanhegan** [comment]
@StephMSlack Did you flush your local cache?

Also, Steve confirmed that setting particular priority results would be part of an enhanced search and isn't in scope. Shall we talk more about enhanced search when you're back?

**Comment by StephMSlack** [comment]
@angievanhegan yes, lets talk about enhanced search next week. In the meantime, the search is now working and I'm happy to close the ticket
