### ISSUE TITLE
Search on global nav not working

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#258]
- [ ] ~TWEAK Advanced search is available to all users~

With the advanced search, we dont need the following content types to show:

- [ ] ~Country~
- [ ] ~organisation~
- [ ] ~organisation group~
- [ ] ~peer-reviewed article~
- [ ] ~system page~

NEW I have also excluded these ones:
- [ ] ~Slide~
- [ ] ~Form~
- [ ] ~Footer~
- [ ] ~Promo~
- [ ] ~Home page~

**Comment by StephMSlack** [comment]
@angievanhegan @pipe-manta the groups are not coming up in the search - they will need to. EG if I search for trainee, the first result I'd like to see is the trainee group - http://bgs-dev.mrmdev.co.uk/trainees

Also with the advanced search, we dont need the following content types to show:
Country
organisation
organisation group
peer reviewed article
system page

Thanks

**Comment by angievanhegan** [comment]
@StephMSlack Try clearing your cache. The search works for me exactly as you'd like it to. I'll add the other things as a TWEAK

**Comment by angievanhegan** [comment]
@pipe-manta Can you look at these done criteria please? Thanks

**Comment by StephMSlack** [comment]
@angievanhegan I cleared my cache and still didnt get them coming up I was getting the team appearing but not the group

**Comment by StephMSlack** [comment]
All the trainee council results are going to the team page, and nothing is appearing in the results for the group.
Have tried other groups as well

![screen shot 2018-06-13 at 16 43 38](https://user-images.githubusercontent.com/32127102/41362328-02914b58-6f29-11e8-86d5-b93db20f6566.png)

**Comment by angievanhegan** [comment]
@StephMSlack The group is appearing 7th down the list. If I type 'Researchers and Academics' or 'GeriGPs' They come up top.

**Comment by pipe-manta** [comment]
@angievanhegan at the monent only the editor and webadmin have access to the advanced search

**Comment by angievanhegan** [comment]
@pipe-manta Please can it be available to all users, including anonymous ones? Thanks

**Comment by StephMSlack** [comment]
@angievanhegan @pipe-manta is there are reason that some results have additional information about the content in the search result but others don't? I've had a look at these resources and they all have intro text and card content and there doesn't seem to be anything different between the resources, but only the title appears in the search result for two and the title and some additional text for the other two.
![image](https://user-images.githubusercontent.com/32127102/41692631-46096248-74cf-11e8-8d35-6846ec37d52f.png)

**Comment by pipe-manta** [comment]
@StephMSlack The additional information is displaying just part of the text where the keyword is prsent, in this case, "frailty".

We originally used the summary and body fields to display the keyword highlighted, but I have enabled also the paragraphs and now all the results include an additional text

![image.png](https://images.zenhubusercontent.com/59ef62dca468affe6df7f840/a03c201d-fefa-4e1f-8b6a-03227523504f)

**Comment by angievanhegan** [comment]
@StephMSlack This is ready for you to sign off

**Comment by StephMSlack** [comment]
thanks @pipe-manta
