### ISSUE TITLE
Change presentation of topics 

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#259]
Estimated at 1.5 days @£560 per day plus VAT

BGS would like to show the content by content type (groupings Resources, News & Policy then Blogs) with a header for each content type. Could use the tab design from the home page?

Also, Can we give the ability to add the professional groups to the top of the page, alongside the SIGs? These can be all the groups can be given the title 'Relevant BGS groups'

1. Resources
2. Event
3. Policy
4. News
5. Blog

**Comment by angievanhegan** [comment]
@russ-manta Please can you estimate this? Steph thinks Colin's going to want it for go live.

**Comment by russ-manta** [comment]
@angievanhegan @StephMSlack going to speak to @ican-icant  about this first. This could be quite a bit of work and there may be some usability issues

**Comment by StephMSlack** [comment]
@russ-manta the reason for this is that the blog content is overwhelming the resources content (which we need to prioritise). If we cannot tab the results (as per home page) can we group them by content type? Show resources at the top, then media & policy and then Blogs, with a header/title for each content type?

**Comment by angievanhegan** [comment]
@StephMSlack This has been estimated. Shall we go ahead?

**Comment by StephMSlack** [comment]
@angievanhegan @russ-manta would we be using the tab option or grouping the content? (just so I know what to expect!)

**Comment by StephMSlack** [comment]
@angievanhegan @russ-manta to confirm - yes we would like this change to take place

**Comment by angievanhegan** [comment]
@russ-manta One more for you. Do you think we need to rope in another developer for this one?

**Comment by StephMSlack** [comment]
@pipe-manta @angievanhegan is it possible to have a message display if there is no content for one of the tabs? "we currently have no content associated with this topic, please visit one of the other tabs in this topic"

**Comment by StephMSlack** [comment]
thanks @angievanhegan @dilwarhussain 
Is it possible to change the text when there are no results? Could it please say - we currently have no content associated with this topic, please visit one of the other tabs

**Comment by dilwarhussain** [comment]
Hi @StephMSlack I've changed the no results text and added the intro above the content type tabs.

**Comment by dilwarhussain** [comment]
@StephMSlack This is fixed now.

**Comment by StephMSlack** [comment]
Thanks @dilwarhussain 
@angievanhegan this is signed off and OK to close
