### ISSUE TITLE
Civi - add member roles sync rules with Drupal

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/bgs#260]
- [x] Create drupal sync rules so that drupal roles are updated in sync with membership types and statuses in civi
- [x] Add renew button to expired members profiles

**Comment by russ-manta** [comment]
@StephMSlack @conferences-BGS can you confirm which membership statuses in Civi are 'current' and which ones are expired and which statuses we should show a renew button to?  We need to add a sync to the Drupal roles for each of these. Let me know if that doesn't make sense

**Comment by conferences-BGS** [comment]
Current
Pending
Expired
On hold
Cancelled
Maternity

From memory
Can you detail any which are missing from this list in the staging environment and I'll say if active or not

Geraint Collingridge. Sent from mobile

________________________________

**Comment by conferences-BGS** [comment]
See attached Russ
All active
I think I missed

New
GDPR cancelled
Decreased
[Image]




Geraint Collingridge. Sent from mobile

**Comment by russ-manta** [comment]
@conferences-BGS thanks, a few omre questions then..
1. presumably only New, Current, Grace and Current Until Renewal count as active memberships?
2. Which membership statuses should we show a Renew button for?  Pending / Cancelled / Expired / On hold?
3. What do we do with GDPR_Cancelled? are they people that have requested removal?
4. We don't have Maternity - is that needed and do they have active member benefits?

**Comment by conferences-BGS** [comment]
New, grace, current, pending, current until renewal are ACTIVE

Expired and on hold - show button for renewal

GDPR cancelled - I would suggest show RENEW but if GDPR cancelled it's likely because they've unsubscribed or asked to be forgotten.
Parvezcan you suggest here

For cancelled or no membershi - JOIN

Ignore maternity - this is not a membership status but custom data and if they have this selected they are active.

Members on maternity who don't pay are put on hold

Geraint Collingridge. Sent from mobile

**Comment by russ-manta** [comment]
@conferences-BGS just adding these rules in for the sync. For 'Grace'  should they see a renew button? Are these people that should have renewed but haven't done so yet but remain active for a Grace period?

**Comment by StephMSlack** [comment]
@russ-manta @conferences-BGS  Russ as I understand things, yes they should see a renew button and your understanding is correct re their role on Civi. (G is in a meeting at the moment...)

**Comment by conferences-BGS** [comment]
Grace is a default Civi term we don’t use at all currently, but it would be applied after someone joins before they have paid. A renew button should be included but we might need to see how this works in real life

**Comment by StephMSlack** [comment]
thanks @russ-manta I've tried this with a couple of different accounts, the renew button appears when expired/cancelled etc. @angievanhegan this is fine to close
