### ISSUE TITLE
Email address getting mangled in content nugget in sidebar

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#261]
http://bgs-dev.mrmdev.co.uk/remember-bgs-in-your-will

![Screen Shot 2018-06-13 at 09.00.53.png](https://images.zenhubusercontent.com/596d095761b4ca3b0a74b803/dc628dd3-46fa-4c87-8714-bd1affe8bb15)

**Comment by dilwarhussain** [comment]
@angievanhegan Fixed now.
