### ISSUE TITLE
Style external courses form

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#262]
- [ ] ~TWEAK Don't need to show title (only full title)~
- [ ] ~TWEAK 'Title' should say 'Course title'~
- [ ] ~TWEAK Hide the time field~
- [ ] ~TWEAK Hide 'display date as' field~
- [ ] ~TWEAK Hide the card content details~
- [ ] ~TWEAK Hide the 'summary' field~
- [ ] ~TWEAK add the instructions for the cost field (e.g. number in GBP only, no £ needed)~ **Please enter the cost in GBP, no £ symbol needed**
- [ ] ~Hide card content for non editors~
- [ ] ~Add RHS info with content guidelines~
- [ ] ~Add link to login/register if not logged in~
- [ ] ~Form in a block~

(this is paid)

https://www.alnap.org/upcoming-events/add-an-event

**Comment by angievanhegan** [comment]
@pipe-manta Same tweaks as for conferences. Thanks

**Comment by pipe-manta** [comment]
@angievanhegan I have created the same page for both, http://bgs-staging.mrmdev2.co.uk/thank-you-for-your-submission They will be able to edit that page and include more text.

**Comment by angievanhegan** [comment]
This overlaps with #192
