### ISSUE TITLE
Events issues

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/bgs#268]
# Done criteria
- [x] Can't appear to save events in Civi (although sometimes appears to save if you revisit the event in a new window) - hangs when saving location screen: eg. http://bgs-staging.mrmdev2.co.uk/civicrm/event/manage/settings?reset=1&action=update&id=20
- [ ] ?
- [ ] ?

**Comment by daniellaveda** [comment]
Can't replicate on our staging site. Event ID 27 saved without hanging. Cant access MRM staging environment, access denied @Russ

**Comment by daniellaveda** [comment]
Getting the attached errors when accessing  New event then after trying to save
![screen shot 2018-06-21 at 11 46 00](https://user-images.githubusercontent.com/27422088/41714627-dccf32d8-7548-11e8-980c-46b86ca0996c.png)
![screen shot 2018-06-21 at 11 45 18](https://user-images.githubusercontent.com/27422088/41714628-dcea7714-7548-11e8-9b99-da207b9462ec.png)

**Comment by daniellaveda** [comment]
![screen shot 2018-06-21 at 12 02 00](https://user-images.githubusercontent.com/27422088/41715315-ed8d7eca-754a-11e8-9452-9e7c831e3bdb.png)
Hangs after adding online registration to event in your environment, but not in ours

If i dont enable online registration
![screen shot 2018-06-21 at 12 02 58](https://user-images.githubusercontent.com/27422088/41715369-20a7d864-754b-11e8-9939-e9bdfecb6d3e.png)
, i get this error:
