### ISSUE TITLE
Update IA

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#27]
# Done criteria
- [x] Update the IA after solving Group/Speciality issues - STEVE

# BGS review
- [x] Review and feedback on current version (this is the main IA doc on the board)

**Comment by ican-icant** [comment]
@angievanhegan I've added the updated IA into Realtime, but couldn't delete the old one, which is sitting underneath.

**Comment by StephMSlack** [comment]
@angievanhegan @ican-icant - updated on realtime - SIGS, Groups and councils has been updated to BGS Groups. Still working on Events, learning and careers (but may be making progress)

**Comment by angievanhegan** [comment]
@StephMSlack That's fantastic news!!
