### ISSUE TITLE
Event being added to the title navigation

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#274]
I've seen this happen a couple of times, when I'm viewing an event, it gets added to the nav

![screen shot 2018-06-25 at 12 26 05](https://user-images.githubusercontent.com/3796718/41865612-41e3b6ee-7873-11e8-9fc2-de238420341b.png)

**Comment by dilwarhussain** [comment]
@angievanhegan Can't replicate this on staging site. Try hard refresh?
