### ISSUE TITLE
Layout issues on Dignity topic page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#276]
http://bgs-staging.mrmdev2.co.uk/topics/dignity

![screen shot 2018-06-25 at 12 36 34](https://user-images.githubusercontent.com/3796718/41866016-8771ff8a-7874-11e8-9135-71039194482e.png)

**Comment by angievanhegan** [comment]
@dilwarhussain a funny layout bug. Not sure if it happens elsewhere.

**Comment by russ-manta** [comment]
@dilwar this is something to do with the content. Pipe and me saw this issue before and fixed the content I think. Try looking at the content for this node: http://bgs-staging.mrmdev2.co.uk/blog/the-geriatric-5ms-%E2%80%93-the-five-simple-words-every-geriatrician-needs-to-know

**Comment by dilwarhussain** [comment]
Thanks @russ-manta
