### ISSUE TITLE
Membership signup & renewal process 

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/bgs#278]
# Done criteria
- [x] How are the contribution fields displayed on the webform in the last step of the membership signup process? These aren't showing on the last step of our webform - is there a configuration step we are missing?
- [x] How does the renewal process work?  We need to provide a button to renew on the Drupal user page(s) should this just link straight through to the Contribution page in Civi?
- [x] How are new Drupal users created and linked during the signup process? I created a student user on staging and no corresponding Drupal user has been created. Is there an approval process that creates a linked Drupal account?
- [x] Create rule to add a linked Drupal account when a Civi contact is added (and send any associated emails/redirects) - RU

**Comment by daniellaveda** [comment]
https://bgs-civicrm.vedacrm.co.uk/bgs_membership#overlay=node/1/webform 
![screen shot 2018-06-28 at 10 37 47](https://user-images.githubusercontent.com/27422088/42026573-589a4882-7abf-11e8-8bb6-b9dc239ee3e4.png)

**Comment by daniellaveda** [comment]
Renewal process - is the join process again. Yes join button - have you seen the current process on the live site @russ-manta ?

**Comment by daniellaveda** [comment]
Will get back on drupal question

**Comment by russ-manta** [comment]
@daniellaveda we have the same fields on the webform. looking at the code it seems the whole "billing-paymen-block" section is not rendering which is where the payment fields are pulled through on your staging and live sites.  Any ideas on why this might be (see image)?
![bgs-webform-payment](https://user-images.githubusercontent.com/25846670/42027919-c683d78e-7ac2-11e8-8a93-9c7b0d039f2e.jpg)


For the renewal process on live, no haven't seen this, the account we have on live is already a paid member. Anyway we can add the link to the join form again no problem.

**Comment by daniellaveda** [comment]
Re drupal account - its created in the my details section so its not part of the renewal or join processes at the moment. if the renewal links are behind the login, then you should pass in the check sum into the webform @russ-manta

**Comment by daniellaveda** [comment]
re webform, im passing it on to Raj to look at @russ-manta

**Comment by russ-manta** [comment]
@daniellaveda did Raj have a chance to look at the webform payment issue?

**Comment by daniellaveda** [comment]
Hi @russ-manta 

yes - ticket updated here: https://support.vedaconsulting.co.uk/issues/7992
