### ISSUE TITLE
Past events coverage permissions

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/bgs#279]
# Done criteria
- [ ] Ensure only members and attendees of a particular event can view past event coverage

# Designs & Docs
- [Link goes here](http://)
- [Link goes here](http://)

# BGS review criteria
[Link to review goes here](http://)
- [ ] ?
- [ ] ?
- [ ] ?

**Comment by angievanhegan** [comment]
@russ-manta Please can you explain what @StephMSlack needs to test here? Thanks

**Comment by russ-manta** [comment]
Have added this to #282 closing this card now
