### ISSUE TITLE
Create first draft of migration plan

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#28]
**Approach is to migrate content as part of each sprint goal.** 

# Done criteria
- [x] Make sure sure BGS know if it's going to have to be mostly manual
- [x] BGS Agree approach to migrate content within the relevant sprint
- [x] Russ confirmed he's happy with this plan

**Comment by angievanhegan** [comment]
@StephMSlack I think the best way forward here would be to incorporate the migration of content into the relevant sprint goal. I think it'll break it down into a more manageable task. Are you (and Recia) happy with that? Thanks

**Comment by StephMSlack** [comment]
@angievanhegan Sounds like a good plan - Recia also thinks this sounds reasonable. We might need  to do some deadline juggling for content updates, depending on when they fit within the sprint schedule.
