### ISSUE TITLE
Enable people to see events they've registered for or been to

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#282]
- [x] Ensure only members and attendees of a particular event can view past event coverage
- [ ] ~Add cpd points and certificate link to my events view~

Need to ask Veda about pulling through:
- [x] Invoice Inovice can be shown using this url: civicrm/contribute/invoice?reset=1&id=76666&cid=19251  where id is the invoice id and cid is the civi contact id)

Note: CPD points and downloading certificate may not be needed for go live, but visibility of booked events is and being able to edit them (change sessions)

The design below is just a guide for the listing page, BGS would like as close as we can get with Civi. Steph is assuming people will simply go back to the civi form they used then they submitted it, but will be able to edit it. 

They'll also need to be able to go back in and pay, but Steph thinks this is all part of Civi. 

# Links
- [Design](https://invis.io/NJMW87I2WD5)

**Comment by angievanhegan** [comment]
@russ-manta Has this one slipped through the net?

**Comment by russ-manta** [comment]
@angievanhegan no, it's almost done but there's an issue with Civi permissions which I asked Veda about today and am going to follow up on with them

**Comment by angievanhegan** [comment]
@russ-manta Feel free to delete if this is a dupe.

**Comment by StephMSlack** [comment]
@angievanhegan @russ-manta - re: modifying events. Currently people are unable to go back in and modify their event booking through Civi. BGS had asked for this function to be available in Civi, but it is not possible at this point.

If a registrant needs to make a payment or add an evening reception ticket they need to contact the BGS office.

All session choices are mandatory at booking and any session changes will need to be done by the BGS office.

If a registrant needs to update their contact details, they can be directed to the profile pages in the My Account section which will update their record. 

So the pay now button in the design is not required. 
The modify booking button should direct users to call the BGS (for registration changes) and direct them to manage their account for changes to contact details. 

When an event has occurred & they have attended, they should be able to download their CPD certificate.

@russ-manta if you have received any info from Veda that contradicts this, do let me know!

**Comment by russ-manta** [comment]
@StephMSlack thanks for this. For the CPD ceritifcates, are they being generated by Civi, has this work been done yet?

**Comment by StephMSlack** [comment]
@russ-manta yes the CPD certificates are being generated in Civi. I will check with G/daniella to see if the work has been completed and let you know.

**Comment by StephMSlack** [comment]
@russ-manta I think it will be in the event custom data, but I am not sure exactly what form this will take

![screen shot 2018-07-12 at 15 29 22](https://user-images.githubusercontent.com/32127102/42639638-659935f0-85e8-11e8-8032-87567b238095.png)

**Comment by StephMSlack** [comment]
@russ-manta Daniella sent me the support ticket relating to this - https://support.vedaconsulting.co.uk/issues/6767 

and a screen shot of where you find the certificate (once it has been generated) below
<img width="901" alt="screen shot 2018-07-12 at 15 43 29" src="https://user-images.githubusercontent.com/32127102/42640608-93ff167e-85ea-11e8-8ad3-49a3cb034610.png">

**Comment by angievanhegan** [comment]
@russ-manta What do you need to unblock this? Is there anything I can do to help?

**Comment by conferences-BGS** [comment]
@russ-manta @angievanhegan Testing this
1 invoices appear in some instances for staff and live members but others throw up errors
See attachments

Can't see CPD certificates at all
![view invoice - geraint collingridge](https://user-images.githubusercontent.com/40232743/46950986-760fbe00-d07e-11e8-8076-9517f927b753.PNG)
![view invoice - stephen lim- wm spring 2018](https://user-images.githubusercontent.com/40232743/46950987-76a85480-d07e-11e8-8236-a7dd8630171b.PNG)

**Comment by russ-manta** [comment]
@conferences-BGS can you tell me which users (email addresses) this was for so I can troubleshoot please?

**Comment by conferences-BGS** [comment]
Dr Stephen Lim BM  for the REGION MEETING West Midlands Spring 2018
15 MARCH 2018
stephenlime@gmail.com Contact ID / User ID 5086  / 5230 

This seems to be meetings where the attendee had no fee: many members and non members (in nurse, AHP, student professions) can attend meetings for free

**Comment by russ-manta** [comment]
View certificate link is now hidden for bookings where no payment was taken

**Comment by conferences-BGS** [comment]
Tested - both CPD and invoices/ receipts now available.
