### ISSUE TITLE
Courses submission currently not asking for payment

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#283]
Steph and I think this was there before! 

The payment request is made, but if organisation submitting is a not for project they don't have to pay. 
Await confirmation from Steph on how to check NFP status for Course organiser

**Comment by angievanhegan** [comment]
@russ-manta This is a mixture of a bug and a tweak!

**Comment by StephMSlack** [comment]
@angievanhegan @russ-manta I have discussed with team here this morning and we have updated the processes for courses. All courses are to be paid for. I have updated the content on the page and we will use the approved/payment required process already in place, which generates a contribution page.
