### ISSUE TITLE
Enable insertion of line breaks within price matrix in Civi

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#287]
Post option help

**Comment by StephMSlack** [comment]
![screen shot 2018-07-19 at 15 49 13](https://user-images.githubusercontent.com/32127102/42953789-1787c134-8b73-11e8-8d89-bbdd506fb5e8.png)
@angievanhegan

**Comment by russ-manta** [comment]
@StephMSlack not sure where you got to with this one but think it is between you and Veda at the moment

**Comment by daniellaveda** [comment]
https://support.vedaconsulting.co.uk/issues/8302#change-29924 completed

**Comment by StephMSlack** [comment]
FYI @angievanhegan

**Comment by angievanhegan** [comment]
@russ-manta Is there anything for us to do here, or can this be closed?

**Comment by russ-manta** [comment]
@dilwarhussain can you take a look at the js error that is detailed here please?
https://support.vedaconsulting.co.uk/issues/8302#change-29924
https://support.vedaconsulting.co.uk/attachments/7358/8302-js-error.png

**Comment by dilwarhussain** [comment]
@russ-manta The JS error is fixed now

**Comment by StephMSlack** [comment]
thanks @dilwarhussain and @russ-manta this is fine
