### ISSUE TITLE
Build and style member directory person page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#288]
I think this one fell off the list. I hope it's not a big job? I think it's just a version of the My Account page with less on it. 

https://projects.invisionapp.com/share/4EDQ458R5#/screens/261765901

**Comment by angievanhegan** [comment]
@russ-manta @dilwarhussain Is it ok to assign this to Dilwar for next week?

**Comment by dilwarhussain** [comment]
@angievanhegan This is using the existing styling of the user page with the Groups and roles exposed to other member directory users now.

**Comment by angievanhegan** [comment]
@StephMSlack This is ready to test. For the sake of consistency of design, we've used the new layout of the My Account page. Professor Helen Rodgers is a good one to test this on.

**Comment by StephMSlack** [comment]
thanks @angievanhegan @dilwarhussain 
Happy with the style/layout of the page
the SIG list is only showing if you have opted into the member directory or are an admin. the SIG list should still show for all members, its only the contact button that disappears if you have not opted into sharing your information.

**Comment by angievanhegan** [comment]
@dilwarhussain One for you. Thanks

**Comment by dilwarhussain** [comment]
@StephMSlack Can you check the SIG list is showing correctly now please.

**Comment by StephMSlack** [comment]
@dilwarhussain @angievanhegan the membership directory has disappeared for each of my non-admin logins which have a valid membership. Once the directory is back, I can check this

**Comment by StephMSlack** [comment]
@angievanhegan - the contact button is not appearing when opted into the directory.

the list of group membership  is not showing consistently

![screen shot 2018-08-08 at 12 34 48](https://user-images.githubusercontent.com/32127102/43834868-b00b108e-9b07-11e8-956d-acfe046c3caa.png)

![screen shot 2018-08-08 at 11 47 33](https://user-images.githubusercontent.com/32127102/43834871-b6609f08-9b07-11e8-8ba6-41ebcc177949.png)

**Comment by russ-manta** [comment]
@dilwarhussain this was the other card  I mentioned with a groups issue on it. See Stephs comments above

**Comment by dilwarhussain** [comment]
@StephMSlack From the above example the reason the Stroke SIG is not showing is because there is no corresponding 'Stroke' group node on Drupal. These links are linking through to the Drupal pages. 

Are there other instances of SIGs with no Drupal node? 
How would you like to treat these SIGs on the user page, keeping in mind all the others are linking through to Drupal pages?

**Comment by StephMSlack** [comment]
@dilwarhussain the stroke SIG is the only one that wont have a SIG drupal node and apparently it is correct that it is not showing up on the member page. Apologies for the confusion. 

Additionally (looking on live) - the page is pulling through member focussed groups, but this member does not have a relationship with either organisation (nurse & AHP or Trainee)
![screen shot 2018-08-09 at 14 54 16](https://user-images.githubusercontent.com/32127102/43903337-22ced3d0-9be4-11e8-8014-c56068567223.png)

**Comment by dilwarhussain** [comment]
@StephMSlack This is ready to check

**Comment by StephMSlack** [comment]
@dilwarhussain weirdly, I am seeing when people are members of the trainee council, but not the nurse & AHP council.

![screen shot 2018-08-14 at 10 45 22](https://user-images.githubusercontent.com/32127102/44084672-3ab92fd0-9faf-11e8-80d6-5fc1c3f4ee03.png)
![screen shot 2018-08-14 at 10 45 32](https://user-images.githubusercontent.com/32127102/44084680-3fcb7244-9faf-11e8-8854-a56b267fcca2.png)

**Comment by dilwarhussain** [comment]
@StephMSlack This is fixed now.
