### ISSUE TITLE
Infographic

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#291]
Each box with pink text should link to another page on BGS, links are shown in pdf below:
http://bgs-staging.mrmdev2.co.uk/resources/the-elements-of-the-cga-process

The infographic svg file is on Sharepoint in the following location:
Manta Ray Media Ltd/Team Manta - Documents/PROJECTS/British Geriatric Society [585]/Content/Infographics [1229]/Graphic-assessment-v01.1.svg

**Comment by angievanhegan** [comment]
Steph to sign off graphic. Then Angie can schedule dev work

**Comment by StephMSlack** [comment]
@angievanhegan we are happy with version 2 - graphic assessment v01.1. this has the blue visuals incorporated into it.
[Graphic-assessment-v01.1.pdf](https://github.com/MantaRayMedia/bgs/files/2231927/Graphic-assessment-v01.1.pdf)
Each of the pink elements are links to pages within the BGS site
[links for cga graphic.pdf](https://github.com/MantaRayMedia/bgs/files/2231943/links.for.cga.graphic.pdf)

**Comment by angievanhegan** [comment]
@cat-manta Please can you add some notes at the top of this issues to make sure the developer requirements are clear? Thanks very much indeed.

**Comment by StephMSlack** [comment]
@dilwarhussain could the interactive infographic please go on the following pages - it will need a heading _How is CGA done_ so it appears in the RHS navigation
https://www.bgs.org.uk/resources/the-bgs-toolkit-for-comprehensive-geriatric-assessment-in-primary-care-settings

https://www.bgs.org.uk/resources/the-elements-of-the-cga-process (replace the current image, will also need the heading How is CGA done)

cc @angievanhegan

**Comment by dilwarhussain** [comment]
@StephMSlack The infographic has been added to the two pages

**Comment by StephMSlack** [comment]
@dilwarhussain thanks for this - FYI the RHS menu/nuggets keep flickering on these pages (almost like strobe lighting) and the infographic isn't interactive when using Safari as a browser and the diagram runs under the RHS column.

<img width="1187" alt="screen shot 2018-09-19 at 15 37 03" src="https://user-images.githubusercontent.com/32127102/45760492-1a3e4a80-bc22-11e8-9041-1c8043e03a73.png">

**Comment by dilwarhussain** [comment]
Hey @StephMSlack Those issues are now fixed.

**Comment by StephMSlack** [comment]
thanks @dilwarhussain
