### ISSUE TITLE
Person creating a website account creates a blank members alert

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#292]
Even if they're not a member.

**Comment by StephMSlack** [comment]
![screen shot 2018-07-25 at 14 19 31](https://user-images.githubusercontent.com/32127102/43209938-c80e2b5e-9025-11e8-9495-1aea075559a2.png)
@russ-manta FYI - not for go-live

**Comment by russ-manta** [comment]
@StephMSlack should be fixed now

**Comment by StephMSlack** [comment]
thanks @russ-manta 
@angievanhegan this is good to close
