### ISSUE TITLE
Join button for logged in non members needs to link to start of membership process

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#293]
If you have an account and you are already logged in, and click the join button to become a member, you should go to the first step of the join process. 

![Screen Shot 2018-07-25 at 10.14.14.png](https://images.zenhubusercontent.com/596d095761b4ca3b0a74b803/d77a4dbb-18d3-4a47-bbf0-0705be28f41a)

**Comment by angievanhegan** [comment]
@russ-manta Let me know if this isn't clear.

**Comment by russ-manta** [comment]
@dilwarhussain I assume it's the buttons on this page: http://bgs-staging.mrmdev2.co.uk/about/become-a-member. Perhaps we can show a different RH block for logged in non members at the top of the sidebar (using context?) and then hide the existing RH nugget for logged in users - not sure

**Comment by dilwarhussain** [comment]
@russ-manta I think I have the correct blocks showing for logged in/out users now.

**Comment by StephMSlack** [comment]
@russ-manta @dilwarhussain 
If a user is already logged in, all we really need is the button 'Join the BGS' 
the text we have in the current RHS nugget is only because we need to explain (in detail apparently :) ) the create account/login options

**Comment by StephMSlack** [comment]
@dilwarhussain @russ-manta Could this change also be reflected on the join page? http://bgs-staging.mrmdev2.co.uk/join-the-british-geriatrics-society (it is only on the become a member page at the moment)

**Comment by dilwarhussain** [comment]
Hi @StephMSlack Made those changes for you.

**Comment by StephMSlack** [comment]
thanks @dilwarhussain this is fine

**Comment by StephMSlack** [comment]
@angievanhegan good to close :)
