### ISSUE TITLE
Link to privacy (page in Civi) showing blank page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#294]
The link for the privacy document is opening a "page not found" page in a new tab

**Comment by StephMSlack** [comment]
http://bgs-staging.mrmdev2.co.uk/sites/default/files/civicrm/persist/contribute/LIVE_BGS_Privacy_Statement_CRM.pdf

![screen shot 2018-07-25 at 16 40 37](https://user-images.githubusercontent.com/32127102/43211484-7dd8eec6-9029-11e8-8c9b-b12e2fed71d4.png)

**Comment by StephMSlack** [comment]
![screen shot 2018-07-25 at 16 41 15](https://user-images.githubusercontent.com/32127102/43211528-98c2ff38-9029-11e8-8400-ca88f1dda07c.png)

**Comment by russ-manta** [comment]
@StephMSlack I think this is the link you need: http://bgs-staging.mrmdev2.co.uk/sites/default/files/civicrm/persist/contribute/LIVE%20Privacy%20Statement_Final%20.pdf

**Comment by StephMSlack** [comment]
@russ-manta I'm not sure where the link has come from (I didn't put it in!) or where to edit it. the pdf has been uploaded to Civi in the GDPR settings and there is no place to add a link in Civi, and I cannot edit the create an account page.

**Comment by russ-manta** [comment]
@StephMSlack where are you clicking to get that error - which page/button is linking to the page not found?

**Comment by StephMSlack** [comment]
@russ-manta its on the base of the create account page http://bgs-staging.mrmdev2.co.uk/user/register

**Comment by russ-manta** [comment]
@steph ok sorted looks like it's been edited more recently. Should really have kept the same filename and not added a filename with spaces but I've fixed the link so it's now using: http://bgs-staging.mrmdev2.co.uk/sites/default/files/civicrm/persist/contribute/LIVE%20Privacy%20Statement_Final%20.pdf

**Comment by russ-manta** [comment]
@StephMSlack  ok sorted looks like it's been edited more recently. Should really have kept the same filename and not added a filename with spaces but I've fixed the link so it's now using: http://bgs-staging.mrmdev2.co.uk/sites/default/files/civicrm/persist/contribute/LIVE%20Privacy%20Statement_Final%20.pdf

**Comment by angievanhegan** [comment]
@russ-manta @StephMSlack What's the next step with this?

**Comment by russ-manta** [comment]
This is done I think. Seems to work fine

**Comment by StephMSlack** [comment]
@angievanhegan good to close
