### ISSUE TITLE
Text changes to login screen (requested by Colin)

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#295]

**Comment by StephMSlack** [comment]
Change header - 'Become a member' to 'Become a BGS member'
Change button - 'Join' to 'Join the BGS'
Change the header 'Create a website account' to 'Create a non BGS member account'
Change text below to 
'Create a non-member account to register for a BGS event at full price, join a SIG, sign up for our blog updates or apply to promote an event on our website.
Change the button 'Register' to 'Set up non-member account'

**Comment by StephMSlack** [comment]
thank you @dilwarhussain
