### ISSUE TITLE
Show Tabs on user page (specifically payment history) for all logged in users

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/bgs#296]
# Done criteria
- [x] Is this region (tabs) hidden for non admin/web-admin users? - Can we show it?

**Comment by russ-manta** [comment]
@pipe-manta  can you look at this one please?

**Comment by russ-manta** [comment]
@StephMSlack this is now available under the manage my account section

**Comment by StephMSlack** [comment]
thanks @russ-manta
