### ISSUE TITLE
Membership details on My account page (top right) should not appear for non member

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#299]
The profile - membership details (ID 24) should only be visible if you are a BGS Member. it should not be visible if you only have a web account

**Comment by angievanhegan** [comment]
@russ-manta FYI - this is not one for go live

**Comment by dilwarhussain** [comment]
@angievanhegan My membership on RHS will not show if you do not have a membership with BGS.

**Comment by russ-manta** [comment]
@StephMSlack @dilwarhussain this is a bit misleading in staging at the moment as we have an old copy of the live database before I made all the Civi profile changes. Best to leave this until I restore last night's Civi database late on tonight

**Comment by StephMSlack** [comment]
@dilwarhussain thanks for this - the change/removal of the profile for non-members is fine and can be pushed to live.

Also, the RHS nugget encouraging members to join the society has disappeared in the live site. 

Staging
![screen shot 2018-08-14 at 10 50 35](https://user-images.githubusercontent.com/32127102/44085094-6f19682a-9fb0-11e8-80c4-0fa4baebd581.png)

Live
![screen shot 2018-08-14 at 10 55 02](https://user-images.githubusercontent.com/32127102/44085158-9195dbe0-9fb0-11e8-8bab-73bbc7091035.png)

**Comment by dilwarhussain** [comment]
@StephMSlack The memberships sidebar is showing for all user now.

**Comment by StephMSlack** [comment]
thanks @dilwarhussain this is fine to go live

**Comment by StephMSlack** [comment]
thanks @matty-manta @dilwarhussain
