### ISSUE TITLE
Create content access model

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#30]
# Done criteria
- [x] Review draft document from [BGS](https://drive.google.com/open?id=0B83TljygKW8SMHkwWEYxRjJzNE0)
- [x] Read [persona documents](https://drive.google.com/drive/folders/0BxTZOVint_EpOWNCNmhOUXNsNnc)
- [x] Complete document
- [x] Gaps recorded in requirement docs
- [x] Development team reviewed it
- [x] Ensure it works with Content Model #26 
# BGS review
- [x] Review draft [content access model](https://drive.google.com/open?id=1UUJRooiPsyaohSc-AL9U2ZeWj8H35gS8uGy_fIaCe-4) and flag up any obvious gaps

**Comment by StephMSlack** [comment]
@angievanhegan we reviewed this at our web development meeting last week. Colin had a query about the term committee member and who that relates to/how it would work and what they could access. Could we reconfirm the definition of this group of users?
