### ISSUE TITLE
Ask users to confirm profession in a dropdown list w/c 7 Aug [With Veda][BGS: P1]

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#300]
Estimated at half day 

Please could we do the simpler/quicker option (which is more in line with the membership sign up as well - though not as ‘nice’) of adding a webform (once the user is logged in) with a single question - Please confirm your profession and then dropdown list. Then the user can progress to the Civi Profile and booking. (From Steph's Slack message)

linked to #297 which was the previous iteration of this functionality
Text from 297 (now archived)

Event booking (http://bgs-staging.mrmdev2.co.uk/events/bgs-yorkshire-region-spring-meeting) using the 'Register online' button currently presents different url's according to the logged in user's career stage. This is done using an api call in the views template for the user eg.

civicrm_initialize(); $uid = $user->uid; // get CiviCRM Contact ID from Drupal User ID $params = array('version' => 3, 'sequential' => 1, 'uf_id' => $uid ); $cidresult = civicrm_api('UFMatch', 'Get', $params); $cid = $cidresult['values'][0]['contact_id'];
$result = civicrm_api3('EventUtils', 'getcontactpricerole', array( 'sequential' => 1, 'contact_id' => $cid, 'event_id' => $output, ));

//print custom event booking url $event_url= $participant_status_id = $result['values'][0]['url'];

BGS would like user to have the option to edit their career stage prior to booking (to make sure they get the correct price and url for the event). To do this they envisage either an intermediate page or a modal dialog which presents a dropdown in a form confirming the current career stage and giveing them the option to change it. Once they have confirmed the correct url they would submit the form and be directed to the correct url for that event in CiviCRM.

To create the form we could potentially use a civicrm enabled webform (career stage is a civi field)?

 Estimate 1-1.5 days for Modal, 0.5 to 1 days for intermediate webform page (no modal dialog). BGS would like to go with the intermediate page option

## note to put live just need to copy views-view-field--event--reg-link--id.tpl.php from staging to live once approved
- - -
**parents:**

1. https://trello.com/c/VlhAUISR

**Comment by russ-manta** [comment]
@StephMSlack @conferences-BGS this is now working in the staging environment. If you go to one of the events eg: http://bgs-staging.mrmdev2.co.uk/events/falls-2018 click register online and then complete the following form you should get taken through to the correct Civi event page at the end.  Let me know what changes you want to the intermediate page in terms of any text or additional fields etc

**Comment by StephMSlack** [comment]
@russ-manta when I try to check this I am getting an error page
![screen shot 2018-08-14 at 10 58 50](https://user-images.githubusercontent.com/32127102/44085320-10153858-9fb1-11e8-970e-b1f1e522faae.png)

**Comment by StephMSlack** [comment]
@russ-manta Could you change the text on the page please? Wherever it says career stage, could we change that to profession? Thanks

**Comment by russ-manta** [comment]
@StephMSlack I've changed the text for this on staging: http://bgs-staging.mrmdev2.co.uk/please-confirm-your-profession-below  was there  anything else or can we put this live and put this form in as the first step when registering for an event?

**Comment by StephMSlack** [comment]
@conferences-BGS could you have a look at this on Staging when you have a moment and let me know if there is anything else that needs adding/changing? thanks

**Comment by russ-manta** [comment]
@conferences-BGS I'll look at the error but this is likely because the staging version of Civi needs updating for the events to match those in staging Drupal. I'll update the databases to sort.  

As for the admin registrations, how are you handling this, are you just sending the relevant people a specific link?

**Comment by conferences-BGS** [comment]
@russ-manta Admin Registrations:
1. We specified that a link would be sent to each category of attendee - 

1. speaker link
2. non member speaker, 
3. sponsor
4. Volunteer
5. Complimentary registration - covering grant recipient/ Associate editor/Trustee

The person would need to create a web account and then using the link be able to circumvent the need for a fee and register themselves as a delegate

We need to also be able to register these people as administrators via the backend (Which is currently not possible either and is separately ticketed)

**Comment by russ-manta** [comment]
@conferences-BGS fine thanks. The intermediate page will not be affected by or affect this functionality so I'll just make sure it's working as it should on staging and then we can push it live

**Comment by russ-manta** [comment]
@conferences-BGS this is ready for retesting in staging, try one of the events: http://bgs-staging.mrmdev2.co.uk/events

**Comment by conferences-BGS** [comment]
@russ-manta Staging site appears to be down

**Comment by conferences-BGS** [comment]
@russ-manta 
Text change from "Please confirm your profession below
to
"Please confirm the profession of the lead delegate registering below"
This is to ensure the correct registration fee

Need to also beaware of this ticket in Veda support queue and potential impact overlap
I think that this change would be of benefit but can't approve until discussion had
https://support.vedaconsulting.co.uk/issues/8675?issue_count=13&issue_position=10&next_issue_id=8596&prev_issue_id=9303

**Comment by angievanhegan** [comment]
@russ-manta Please can you confirm for @conferences-BGS the next steps for this? I think you mentioned that it was in staging ready for sign off? Thanks

**Comment by russ-manta** [comment]
@conferences-BGS this text change ('Please confirm the profession of the lead delegate registering below') has now been made.  I can't see that this functionality would be affected by the Veda ticket but best to get this confirmed with them.

**Comment by angievanhegan** [comment]
@russ-manta  what do we need @conferences-BGS to do here?

**Comment by russ-manta** [comment]
@angievanhegan it's ready to go live from our perspective. The text change that BGS requested is done 'Please confirm the profession of the lead delegate registering below' but I think we're waiting on Veda to confirm that this new functionality won't affect any changes they are making as Geraint mentioned above.

**Comment by mrm-git** [comment]
➤ conferences-BGS commented:

@russ-manta Admin Registrations:

  1. We specified that a link would be sent to each category of attendee - 
  2. speaker link
  3. non member speaker, 
  4. sponsor
  5. Volunteer
  6. Complimentary registration - covering grant recipient/ Associate editor/Trustee

The person would need to create a web account and then using the link be able to circumvent the need for a fee and register themselves as a delegate

We need to also be able to register these people as administrators via the backend (Which is currently not possible either and is separately ticketed)

**Comment by russ-manta** [comment]
@conferences-BGS re the admin registrations aren't these all done via Civi and a link sent by BGS to the person directly?

**Comment by conferences-BGS** [comment]
@russ-manta We require the ability to send to speakers, sponsors, volunteers and other complimentary registrations a booking link that circumvents the price sets

We can't do all the registrations in the back end as administrators. Currently we send a

**Comment by conferences-BGS** [comment]
@russ-manta We require the ability to send to speakers, sponsors, volunteers and other complimentary registrations a booking link that circumvents the price sets

We can't do all the registrations in the back end as administrators. Currently we send a complicated multi step process like below
This link is just for Autumn grant recipients

https://www.bgs.org.uk/civicrm/event/register?reset=1&id=70&participantrole=70efdf2ec9b086079795c442636b55fb

For other meetings please let me know and I’ll show you where to get this link from in future

Please send successful recipients the below which doesn't always work. We need to also capture for speakers the below
Will need to coordinate with Veda see https://support.vedaconsulting.co.uk/issues/6738

Biography

- Accommodation Needs

- Travel needs

- Consent to share slides
- conflict of interests


Grant recipients
Please register yourself for the meeting using these steps 
1. Visit https://www.bgs.org.uk/user/login  and login to your membership account for the BGS site. Your membership will need to be active.
2. Ensure you are logged into this account then
3. Click this link https://www.bgs.org.uk/civicrm/event/register?reset=1&id=70&participantrole=70efdf2ec9b086079795c442636b55fb 
4. Complete the biographical details, contact and dietary requirements. Please also indicate your session choices and your acceptance of the required fields for opt in and privacy statement. 
You will need to select admin- grant recipient under registration fees
 
Please contact conferences@bgs.org.uk with any queries or issues
