### ISSUE TITLE
Some group pages not picking up newly added feed content

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#301]
some of the groups pages are not picking up newly added feeds - eg this page http://bgs-staging.mrmdev2.co.uk/north-west-thames has a blog feed, there is a blog (or more) associated with this group, but neither blog feed (group curated or group latest) is working. I have cleared the cache and refreshed the browser (Steph in Slack 31 July)

**Comment by angievanhegan** [comment]
@StephMSlack Can you add a specific example please? Thanks

**Comment by russ-manta** [comment]
@cutlern can you see if you can replicate this please?

**Comment by StephMSlack** [comment]
thanks @dilwarhussain 
@angievanhegan this is fine to close
