### ISSUE TITLE
Go live issues

### ISSUE THREAD

**Issue by conferences-BGS** [MantaRayMedia/bgs#302]
List of go-live issues raised by BGS

# Issues 
- [x] Member Directory 
-**DONE** too many users, linked to failed Drupal import. Also check parameters as only 2 records in Civi have opted in to the member directory 
-  **DONE** blank cards showing in results
- **DONE**search function missing fields (see screenshot) 

- [x] CiviCRM 
**With Veda** Cron errors

- [x] Login
Staff users unable to reset passwords, linking to login issues

- [x] Events 
- change to register button when not logged in (see #248 )
- **DONE** styling in Civi Form - dietary requirements/comms pref are not showing in a list, (currently 1 long line of text & radio buttons). Screen shot below
- **DONE** Button removed - when paying by invoice option to download prior to completing booking - download pdf link returns error (For Veda) Screen shot below
- **With Veda** PDF of invoice (in Civi) not showing registrant information, a number of fields in the invoice are blank (Veda)

- [x] GDPR 
Reset password has GDPR e-bulletins attached. All options are visible for sign up

- [x] Emails 
- **DONE** error message on event confirmation screen re: mandrill connection

- [x] mailing
**With Veda** Mosaico templates - have not come across to the live site.

- [x] Account Creation
new accounts are showing MyBGS Groups -even when no groups have been joined. And always showing Nurse/trainee council.

**Comment by StephMSlack** [comment]
Mandrill error - event confirmation email
<img width="1253" alt="screen shot 2018-08-01 at 23 41 42" src="https://user-images.githubusercontent.com/32127102/43553283-20e1e480-95e6-11e8-83c0-5a0d3f9cb84f.png">

**Comment by StephMSlack** [comment]
Download PDF error
<img width="1232" alt="screen shot 2018-08-01 at 23 39 27" src="https://user-images.githubusercontent.com/32127102/43553295-36bb0958-95e6-11e8-9c37-dec0eb35ccd3.png">
<img width="1280" alt="screen shot 2018-08-01 at 23 39 46" src="https://user-images.githubusercontent.com/32127102/43553296-391204d6-95e6-11e8-96f4-044140e9fe68.png">

**Comment by StephMSlack** [comment]
Event registration form - layout issue
<img width="1036" alt="screen shot 2018-08-01 at 22 56 41" src="https://user-images.githubusercontent.com/32127102/43553339-64322362-95e6-11e8-963a-907eeb2f3fd7.png">

**Comment by StephMSlack** [comment]
Downloaded invoice with missing fields
[INV_80859.pdf](https://github.com/MantaRayMedia/bgs/files/2251382/INV_80859.pdf)

**Comment by StephMSlack** [comment]
blank cards in member directory
<img width="1273" alt="screen shot 2018-08-02 at 00 01 56" src="https://user-images.githubusercontent.com/32127102/43553654-e934dd60-95e7-11e8-8819-7c58f638a9ea.png">

**Comment by StephMSlack** [comment]
Members Directory - missing fields

Live
<img width="1154" alt="screen shot 2018-08-02 at 00 08 22" src="https://user-images.githubusercontent.com/32127102/43553751-7421a368-95e8-11e8-99aa-98a0c8e8847e.png">

Staging
<img width="1188" alt="screen shot 2018-08-02 at 00 08 06" src="https://user-images.githubusercontent.com/32127102/43553755-798d0734-95e8-11e8-93a2-8e8aba17565f.png">

**Comment by russ-manta** [comment]
@StephMSlack have started looking at these will continue at 9

**Comment by russ-manta** [comment]
@StephMSlack quick update
1. Emails/mandrill in Civi should be sorted
2. Members directory is now showing now.  I've added filters for is a member and opted into the members directory which were not there - let me know if this needs changing.
3. Styling in civi form - due to profile field ids changing - Arseni is looking at this now
4. Members directory blank cards
5. Members directory search options missing - due to civi profile fields (ids) being different between live and staging - I'm making the relevant changes to fix this

will come on to the other items next

**Comment by russ-manta** [comment]
@StephMSlack 
1. Members directory search filters now fixed on main and my account pages
2. Styling in civi form. - done for 1st participant - checking 2nd participant
3. Looking at ebulltin preferences/permissions

**Comment by StephMSlack** [comment]
@russ-manta re: download PDF button - the button needs to be removed. @daniellaveda checked with the team and the functionality should have been removed, so it may be a styling issue that the button is still visible.

**Comment by russ-manta** [comment]
@StephMSlack will look at the download pdf button now.
Ebulletin preferences are now fixed so members/non-members see different options under manage my account - we don't have anything more granular than that at this stage

**Comment by russ-manta** [comment]
@StephMSlack download pdf issue now done

**Comment by StephMSlack** [comment]
thanks @russ-manta

**Comment by StephMSlack** [comment]
@russ-manta the webform for the member join process is not providing any error messages when compulsory fields are not completed. Could this be enabled please?

**Comment by russ-manta** [comment]
@StephMSlack will look at the webform now. The button/text changes on the become a member change are now done: https://bgs-live.mrmdev2.co.uk/about/become-a-member

**Comment by russ-manta** [comment]
@StephMSlack for the webform it does provide errors on each field when you fail to complete (same in staging). Do you mean you want a list of all the errors for the incomplete fields?

**Comment by StephMSlack** [comment]
@russ-manta it is just for the acceptance of the T&C at the end of the form. We tried to continue the booking without ticking them and the page would not progress

**Comment by StephMSlack** [comment]
@russ-manta - will need to chat to you about the button/text change on the become a member page.

When a user is not logged in, and they click register online, they should not be redirected to the membership page as there is no reference to booking events on this page.

What I had hoped for, is that is a user is not logged in they would see two buttons "create an account and register' or 'login and register'. Similar to how the membership buttons work (as an example)

**Comment by StephMSlack** [comment]
Hi @russ-manta  if you are happy with all your web checks, Colin is happy for us to turn the site to live.

**Comment by StephMSlack** [comment]
@russ-manta new account creation - all seem to show the BGS role box, even when a non member and no role in Civi
![screen shot 2018-08-02 at 14 47 10](https://user-images.githubusercontent.com/32127102/43587864-17bbaa76-9663-11e8-9f4d-cb9138a0f4ec.png)

**Comment by russ-manta** [comment]
@StephMSlack I've hidden the member focussed groups from all for now until we work out what's going on with it

**Comment by russ-manta** [comment]
@dilwarhussain can you take a look at this view and why the Member focussed groups are showing for all: https://www.bgs.org.uk/admin/structure/views/view/my_bgs_groups/edit/mfgs

**Comment by dilwarhussain** [comment]
Hi @StephMSlack Can you check if the correct Member focussed groups are coming through now. Thanks.

**Comment by russ-manta** [comment]
@dilwarhussain is there anything left to do on this card?
