### ISSUE TITLE
Bug - Communication preference text out of sync/ displayed badly

### ISSUE THREAD

**Issue by conferences-BGS** [MantaRayMedia/bgs#306]
Image displayed for members
![image.png](https://images.zenhubusercontent.com/5b21288239589c155032f05a/43509b16-7d02-419e-9fe6-52391b3628ae)

Current settings in GDPR dahboard
![image.png](https://images.zenhubusercontent.com/5b21288239589c155032f05a/79adeb9c-1adb-4478-a965-bdd7112c5273)

# Done criteria
- [x] ? Update text description in members account to reflect content in GDPR settings in bgs.org.uk
- [ ] ? If possible/ required to push to Drupal by BGS following change advise on how to do this
- [ ] ?

# Designs & Docs
- [Link goes here](http://)
- [Link goes here](http://)

# BGS review criteria
[Link to review goes here](http://)
- [ ] ?
- [ ] ?
- [ ] ?

**Comment by russ-manta** [comment]
@conferences-BGS this is all held within separate drupal fields within Drupal as this was the only way we could get the forms embedded in the new user registration form.
Any changes to the value of the bulletins selected are synced automatically with the groups in Civi but the descriptions are not and need to be edited manually in Drupal if there is any change required.  At the moment this needs to be done by Manta Ray.

I've made the text changes. Let me know if any more tweaks required.

**Comment by conferences-BGS** [comment]
Thanks Russ
Will need to document these types of update (i.e. BGS, MRM or Veda) closely
