### ISSUE TITLE
Event Issues - Part 1

### ISSUE THREAD

**Issue by conferences-BGS** [MantaRayMedia/bgs#307]
Issues report:

1.	Email address during registration for event
a.	The account email address can be changed during the registration process which will modify the delegate's whole profile after registration. Could we block this field so delegate cannot change it during the registration process or add a cc’d email field and some text explaining why this field should not be changed unless they want permanently modify the email address linked with their profile

# Done criteria
- [ ] ? Delegate can add in multiple email addresses and not over write the email they use to login to the account
- [ ] ?
- [ ] ?

# Designs & Docs
- [Link goes here](http://)
- [Link goes here](http://)

# BGS review criteria
[Link to review goes here](http://)
- [ ] ?
- [ ] ?
- [ ] ?

**Comment by russ-manta** [comment]
@conferences-BGS this is one for Veda I think. Needs a config change in Civi. Probably just an event profile change

**Comment by russ-manta** [comment]
adding @daniellaveda

**Comment by StephMSlack** [comment]
@conferences-BGS - Re: 1a - these are in your profiles in Civi. I've changed the email field to view only, and you can add another email address into the profile if you like and the appropriate help text there

**Comment by daniellaveda** [comment]
Ive been added - however the ticket is closed. Any action for me? @russ-manta @conferences-BGS

**Comment by conferences-BGS** [comment]
I've ticketed in Veda support and already add a cc email option

Geraint Collingridge. Sent from mobile

________________________________
