### ISSUE TITLE
Event issues - Part 2 Register online button pathway failure

### ISSUE THREAD

**Issue by conferences-BGS** [MantaRayMedia/bgs#308]
2.	Register online button if not log in an account bring you to join the BGS and not create an account / log in page
Delegates should be directed to a page given them the option to log into their account or create a new  one. They are currently directed to the page https://www.bgs.org.uk/join-the-british-geriatrics-society 
 
 Second error 
When clicking on register online (tested on Falls, Improving continence and Autumn 2018) the link to register brings you to the join the BGS. If you are not log in, it will offer you to create an account but will bring you back to the membership page. If already log it, it only offers you the option to join the BGS

 # Done criteria
- [ ] ? Contact logged in - should see register now button
- [ ] ? Contact logged out - prompted to login and then register and then register for event
- [ ] ? Contact without account - prompted to create an account, and then register for event

# Designs & Docs
- [Link goes here](http://)
- [Link goes here](http://)

# BGS review criteria
[Link to review goes here](http://)
- [ ] ?
- [ ] ?
- [ ] ?

**Comment by StephMSlack** [comment]
@conferences-BGS this was raised in #302. I don't think @russ-manta has had a chance to action this, as it involves the API calls.

**Comment by russ-manta** [comment]
@conferences-BGS @StephMSlack In the above 'Delegates should be directed to a page given them the option to log into their account or create a new one.' does this page exist at all? There was a page previously which you can still see if you log out and access this: https://www.bgs.org.uk/civicrm/event-landing?reset=1&eid=70  Is this basically the kind of thing you want but looking slightly different/different wording?

**Comment by conferences-BGS** [comment]
Steph had spent more time designing the look of this but that's the function.
We don't want to copy Veda interim design though


Geraint Collingridge. Sent from mobile

________________________________

**Comment by russ-manta** [comment]
@StephMSlack apologies if you have posted the design somewhere else but can you add it here too?

**Comment by StephMSlack** [comment]
@russ-manta when a user is not logged in, instead of see the register online button, they should see the RHS module below, and then once logged in/account created they then get directed either a) back to the event page where they see register online, or depending on how the API works, they go straight to the registration form.
<img width="362" alt="screen shot 2018-08-06 at 10 22 32" src="https://user-images.githubusercontent.com/32127102/43708715-00531c0e-9963-11e8-9f7a-6aca1cabbd5e.png">

The styling of the RHS nugget should reflect that on the become a member/join page

**Comment by russ-manta** [comment]
@dilwarhussain this needs to redirect back to the original event after logging in or creating a new account

**Comment by StephMSlack** [comment]
@dilwarhussain @russ-manta is it possible to add to the API call for the register now button? The buttons should only appear if online registrations are enabled on Civi. Ideally this would also link to the corresponding registrations start date. Screen shot below

Registrations open
![screen shot 2018-08-08 at 09 39 22](https://user-images.githubusercontent.com/32127102/43826348-06c1b0ae-9aef-11e8-8215-10a09a80d32d.png)

registrations closed
![screen shot 2018-08-08 at 09 38 45](https://user-images.githubusercontent.com/32127102/43826374-11e78a1c-9aef-11e8-8d46-d4741d43e199.png)

**Comment by StephMSlack** [comment]
@dilwarhussain @russ-manta - or is there a way in drupal we can manually show/hide the register online buttons?

**Comment by StephMSlack** [comment]
@russ-manta @dilwarhussain  to add to this, we did have a requirement to be able to link the event register function to another site (eg if the event registration process is being handled by the royal college of nurses), which is I think why the register link (screenshot below) is available in drupal. At the moment, this link is being super-seeded by the register online button as well. 
![screen shot 2018-08-08 at 11 47 33](https://user-images.githubusercontent.com/32127102/43833138-b222ae6e-9b01-11e8-9339-19571875e0ac.png).

**Comment by StephMSlack** [comment]
The logic would be

user logged out - see 2 options 'Create account and register' or 'login and register'
User logged in, event open for registrations - see 'register online'
user logged in/out & event not open for registrations - no button 
user logged in/out and external registration process - use the drupal link from CMS

**Comment by dilwarhussain** [comment]
@StephMSlack Can you test the functionality of the register links for this event on the staging site please: http://bgs-staging.mrmdev2.co.uk/events/british-geriatrics-society-autumn-meeting-2018 
It is currently using the custom register link on the Drupal event node, if you remove this link, it will automatically link to the registration page from civi. Let me know if this is all working as required. Thanks.

**Comment by StephMSlack** [comment]
thanks @dilwarhussain 

once logged in - could the link button say Register online (not custom link)
![screen shot 2018-08-09 at 09 23 23](https://user-images.githubusercontent.com/32127102/43887245-15d1d2f0-9bb6-11e8-8525-28018da459ef.png)

I got my wording slightly incorrect for the top button - it should be create account and register (not register online)
![screen shot 2018-08-09 at 09 26 30](https://user-images.githubusercontent.com/32127102/43887328-64c15de0-9bb6-11e8-8b52-fe681c20c845.png)

**Comment by StephMSlack** [comment]
@dilwarhussain I'm not sure what you mean re: if you remove the link it will automatically link to the registration page in Civi.
Is it possible to have either no button or a button saying Registration Closed if the event is not open for bookings?

**Comment by dilwarhussain** [comment]
@StephMSlack I've changed the text for the button. The register buttons will only show while registration is open. So the civi event will need to have a start and end registration date.

**Comment by StephMSlack** [comment]
thanks @dilwarhussain 
I'm getting an error message when I try to view the event
![screen shot 2018-08-09 at 10 59 40](https://user-images.githubusercontent.com/32127102/43892312-849b7260-9bc3-11e8-85ba-48034efa222d.png)

**Comment by StephMSlack** [comment]
Some of our events do have external booking processes - is it possible for us to add a link to an external site (if the registration has no start/end date in Civi) using the links section on the drupal event page?

**Comment by dilwarhussain** [comment]
@StephMSlack Can you check again please, not getting any errors here.
And yes you can use the register link in the links section on the drupal event to use for external bookings.

**Comment by StephMSlack** [comment]
@dilwarhussain I'm happy with the RHS buttons, happy with the external link working, but cannot seem to re-enact having the buttons not showing when a registration date is removed/in the past.

**Comment by StephMSlack** [comment]
@dilwarhussain thanks for this, happy for you to push the changes to live.

**Comment by StephMSlack** [comment]
@angievanhegan I'll need to re-check this one once it is on the live site

**Comment by dilwarhussain** [comment]
@StephMSlack I've made the changes to live, it is ready for you to test.

**Comment by StephMSlack** [comment]
thanks @dilwarhussain all is fine
@angievanhegan good to close
