### ISSUE TITLE
Add Geraint, Disha and Julie as Civi Admins

### ISSUE THREAD

**Issue by conferences-BGS** [MantaRayMedia/bgs#310]
Currently limited in reports we can see, actions and processes. Urgent
# Done criteria
- [ ] ?Make us full Civi admins
- [ ] ?
- [ ] ?

# Designs & Docs
- [Link goes here](http://)
- [Link goes here](http://)

# BGS review criteria
[Link to review goes here](http://)
- [ ] ?
- [ ] ?
- [ ] ?

**Comment by russ-manta** [comment]
@StephMSlack @conferences-BGS can you give me an example of things you are missing?

**Comment by conferences-BGS** [comment]
A whole series of reports built by Veda

[cid:image001.png@01D42E5D.C2DC4A00]


API Key for Outlook plugin

[cid:image002.png@01D42E5E.102B6570]

We specified and do need roles for the below, setting up in the medium term

1.    Admin for all areas – Geraint, Steph and Disha

2.    Super user – for most areas – Julie and Janet

3.    Staff user – all others with limited access to Administer settings

4.    Officer User – limted to view only for SIGs/ Sections (to be discussed)

**Comment by russ-manta** [comment]
@conferences-BGS ok I've given you all the civi permissions I can. Can you try logging out and back in and see if you have what you need?

**Comment by conferences-BGS** [comment]
Thanks Russ
We can see the areas we need – will review later filtering for staff members

**Comment by StephMSlack** [comment]
thanks @russ-manta I'll close this ticket now.
