### ISSUE TITLE
Bug Event error message

### ISSUE THREAD

**Issue by conferences-BGS** [MantaRayMedia/bgs#311]
Currently all bgs events showing error message
# Done criteria
- [ ] ? Restore event landing page or redirect/ display message about registering via etoiches
- [ ] ? Allow login and/ or event creation
- [ ] ? Allow registration

# Designs & Docs
- [Link goes here](http://)
- [Link goes here](http://)

# BGS review criteria
[Link to review goes here](http://)
- [ ] ?
- [ ] ?
- [ ] ?

**Comment by russ-manta** [comment]
@conferences-BGS @daniellaveda I'm not really looking at issues today but just noticed this one.  Should now be fixed.  It looks like a regression issue with a bug we patched a while back that may have been overwritten by a Civi release that Veda have done. I'll let them know. If you have any more issues can you try and put them in the 'Sprint backlog' or 'Backlog' pipeline?  Thanks Russ
