### ISSUE TITLE
Civi cron not running

### ISSUE THREAD

**Issue by dilwarhussain** [MantaRayMedia/bgs#314]
"Last cron run at 9th August 2018 4:00 PM."

https://www.bgs.org.uk/civicrm/a#/status

**Comment by russ-manta** [comment]
This seems to be due to a token missing in one of the scheduled reminders causing one of the jobs not to complete. This has been referred to Veda, otherwise it looks as if cron is running ok

**Comment by conferences-BGS** [comment]
Cron error gone now
But Civi Update message displayed
 CiviCRM Security Update Required
Unhide (Hidden permanently)
New security release 5.4.1 is available. The site is currently running 4.7.23.

How are updates being managed? @russ-manta

**Comment by russ-manta** [comment]
@conferences-BGS all civi updates/upgrades are handled by Veda. We may end up pushing them out but Veda will tell us when one is required.
