### ISSUE TITLE
Topic categories shouldn't be links/pages

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#315]
I think this only happens when the screen is medium width. The four categories for topics should not be pages (e.g. Acute care, Primary and Community care, Specific conditions, General). There should only be pages for the topics themselves

![Screen Shot 2018-08-10 at 10.26.00.png](https://images.zenhubusercontent.com/596d095761b4ca3b0a74b803/bde05c67-cfc0-4575-872f-374df279d23f)

**Comment by StephMSlack** [comment]
thanks, this is fine to close @matty-manta

**Comment by matty-manta** [comment]
Thanks @StephMSlack
