### ISSUE TITLE
Topics changes {14 hours}[BGS:P2]

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#317]
2 days

# Move SIG into tab
Create new tab for SIGs with the label 'BGS groups' (to be placed after blogs in the tab order)
SIGs to be listed using card content (as with the rest of the content in topics)

# Add a fifth column to the topics mega drop down
We'd suggest that the topics menu is all reallly looking quite full with 4 columns and that the titles of a couple of topics are long and are likely to wrap, making the layout look cluttered.

- - -
**children:**

1. https://trello.com/c/tVSGXJ7H
1. https://trello.com/c/LP3DM2o0

**Comment by StephMSlack** [comment]
fifth Column - list of headings and associated topics

[Topics V9 20.09.18.xlsx](https://github.com/MantaRayMedia/bgs/files/2400956/Topics.V9.20.09.18.xlsx)

**Comment by russ-manta** [comment]
@conferences-BGS 1. presumably we display the cards for the groups with the same design as the SIGS on the bgs groups page: https://www.bgs.org.uk/bgs-groups
2. do you want a 5th column on the topics mega drop down or are you happy with the 4 as is when hovering over topics in the navigation menu?
__
