### ISSUE TITLE
Resources changes {7 hours}[BGS:P2]

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#318]
1 day 

# Enable resource series to be tagged with topics
1. add a new tab  on topics page for resource series. 
1. topics need to be visible on the resource series node (after the text)

- - -
**children:**

1. https://trello.com/c/nJOaJ7fo

**Comment by conferences-BGS** [comment]
@angievanhegan what are you looking for on this one? Is there a lack of clarity

**Comment by angievanhegan** [comment]
@conferences-BGS There's nothing for you to do here. This is just a parent task. It's not been assigned to you and you've not been @'d so you can ignore it totally.  The child tasks in #369 which is in your column for you to look at.
