### ISSUE TITLE
External jobs {28 hours}[BGS:P2]

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#319]
4 days

# Enable BGS to publish external jobs
* [ ] Design and build using external events as a template (https://www.bgs.org.uk/events/external-events)
* [ ] To include payment function. Please include two payment options (two prices, using CiviContribute for payment processing) 

## Landing page
* Cards show: 
  * Job title
  * Location
  * Organisation
  * Deadline date
  * Salary
* Sort by
  * Deadline
  * Most recent
* Submit a job (button at the top)
* Same log in options as external events (interim page with details for submission on RHS)
* Jobs can only be edited by BGS once submitted
* Content needs an expiry/auto unpublishing date
* Do we need a search? Nice to have if doable in the time otherwise leave for another time
* Text at top of page (like External events)

## Node page / form
Fields with an * are mandatory

* Deadline*
* Date Posted*
* Job type*
* Organisation*
* Agency / Trust (who is advertising this)*
* Location*
* Salary*
* Sidebar
  * Attachments
* Share
* Option for different payment types (gold/platinum) will send message via rules once approved with link to the correct payment page in Civi.*
* RHS nugget when submitting the form (like external events form) with info on submitting

- - -
**children:**

1. https://trello.com/c/wtBmebZz
1. https://trello.com/c/SQQnEa8T
1. https://trello.com/c/dvQU0RDv

**Comment by StephMSlack** [comment]
@angievanhegan 
For the node/form:
*Advertising organisation: Text

Check box 
NHS hospital - free text - hospital name
private agency -free text -  agency name
Other (other can be an overseas hospital) - Free text -company name

*Title of job being advertised: (e.g. geriatrician, professor of gerontology, nurse specialist)
Free text

Number of vacancies: Text

*Closing date for application/submissions:
calendar /date

Interview date:
calendar /date

*Employer: (who the role will be based with)
Free text

*where the job is based (Region)
Drop down

*Details of post (no more than 200 words):
Free text

Person requirements: 
Free text 

Upload Job description (PDF only, Max size XXX) upload (RHS Nugget?)
Upload company logo (jpeg, png) (RHS Nugget?)

**Comment by conferences-BGS** [comment]
My comments on the above
@StephMSlack 
1. Headline description

1b Number of vacancies: Text

2. *Closing date for application/submissions:

*Closing date for application/submissions:
calendar /date

2b.Interview date:
calendar /date

3. Key information - 
3a. Profession of job being advertised: can be pulled from Civi professions(e.g. geriatrician,, nurse specialist)
3b.Free text Job title, (Job title in CIvi CRM)
*Title of job being advertised: (e.g. geriatrician, professor of gerontology, nurse specialist)
Free text
For the node/form:
*Advertising organisation: Text

3c. Sector - drop dow NHS, State, Private, Care Home, University, Research Centre
and
Check box
NHS hospital - free text - hospital name
private agency -free text - agency name
Other (other can be an overseas hospital) - Free text -company name

3d. Salary range
3e. Experience required
3f. Location (using PAF?)/ Region in Civi
or
*where the job is based (Region)
Drop down

3g.

4. The job description and person specification
*Details of post (no more than 200 words):
Free text

Person requirements:
Free text
5. URL link to employer and upload employer logo
Upload Job description (PDF only, Max size XXX) upload (RHS Nugget?)
Upload company logo (jpeg, png) (RHS Nugget?)
6. Submit application process (email X your CV and cover letter or URL to submit an application)

**Comment by StephMSlack** [comment]
@angievanhegan I'm putting together a google doc to clarify the above - will add it here tomorrow once it has been agreed with CEO/Geraint.

**Comment by conferences-BGS** [comment]
@russ-manta At what stage is this? I have two jobs to list at this time and 1 is time sensitive

**Comment by russ-manta** [comment]
@conferences-BGS we're just working on this now. For the different payment types eg gold/platinum , how would this work?
Would the person submitting a job have an option to choose or it based on if they are a member?

**Comment by russ-manta** [comment]
@conferences-BGS we're going to add a body/description section to the form which wasn't mentioned but must be needed I think. Where in the site will these external jobs live once some have been added?  Somewhere under about or somewhere else?

**Comment by conferences-BGS** [comment]
@russ-manta Already started manually adding here 
https://www.bgs.org.uk/about/bgs-vacancies-and-external-job-vacancies
So yes under about us for the moment and probably require the menu expanding to include

- 

- BGS Vacancies

- External vacancies

**Comment by russ-manta** [comment]
@conferences-BGS we have a deadline field for this. Is the plan that the content would automatically be unpublished once the deadline is in the past?

**Comment by conferences-BGS** [comment]
@russ-manta Yes. Listings for 6 weeks only so deadline is 6 weeks from date of publishing
This feature would also be required on the external events and courses process for paid listings
Currently I am manually adding an unpublish date

**Comment by russ-manta** [comment]
@conferences-BGS if the deadline for a job is less than 6 weeks presumably it gets unpublished before then?

**Comment by conferences-BGS** [comment]
@russ-manta in principle yes, but happy for a 6 week term to be applied as default

**Comment by angievanhegan** [comment]
@conferences-BGS This is the information we have in the requirements: Option for different payment types (gold/platinum) will send message via rules once approved with link to the correct payment page in Civi.*

**Comment by conferences-BGS** [comment]
Options should be invoice or card
Costs are £250 + VAT or £350 + VAT

The process should follow the same as an event - fill out form and select payment method. Then fill out if invoice or pay by card
What further is required?

**Comment by conferences-BGS** [comment]
Content payment and Job payment set up in MRM staging
![image](https://user-images.githubusercontent.com/40232743/49073166-bb044400-f229-11e8-8888-179fee1d6ae8.png)

Advertising page in staging here http://bgs-staging.mrmdev2.co.uk/civicrm/admin/contribute/settings?reset=1&action=update&id=3

**Comment by russ-manta** [comment]
@conferences-BGS for external events the authoir is sent an automated email '
Your content will be reviewed before publishing. If approved for publication you will receive a further message with a link to payment details and your content will be published once we have received payment.'

Presumably that is the same here?

**Comment by russ-manta** [comment]
@conferences-BGS this step above was to prevent people paying for content and then have it rejected and then BGS have to issue a refund

**Comment by conferences-BGS** [comment]
@russ-manta Yes
Thank you for your submission.
Your vacancy content will be reviewed before publishing. If approved for publication you will receive a further message with a link to payment details and your content will be published once we have received payment.'

Presumably that is the same here? Yes - can you confirm though that people are getting the link to pay by card for external events and this as well?

**Comment by russ-manta** [comment]
@conferences-BGS ok this is pretty much done. A couple more questions before we finish:

1. There is a requirement for a logo:
Should it appear on the RHS above the attachment?
http://bgs-staging.mrmdev2.co.uk/russ-new-test-job
2. If there is no logo and no attachment then should the left hand side of the page go full width or should we keep a space on the RHS whether there is anything there or not?
3. For the gold and silver options what are the actual differences on the site?  Is the gold option supposed to be highlighted in some way on the External jobs landing page?

**Comment by conferences-BGS** [comment]
@russ-manta 
1. Yes
2. Default to rest of site action when no logo/ attachment - i think this is keep space?
3. Gold: we want to pin to the top of the page, have a prominent border on the card and around the page when opened
