### ISSUE TITLE
Payment history function {14 hours} [With Veda][BGS: P2]

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#320]
2 days

# Enable people to see what they've paid to BGS 

- people may have paid for: events, membership, events submissions
- make the invoice/receipt available for download. 

There is a payment history at the moment, which Russ has turned on but it needs some expansion to allow the users to download their payment receipts. It can only be seen as an admin. 

Login 'Steph test BGS2' can be used for a test.

## Note RU - 261018 - done (on staging and live) except need to try and add parent tab when viewing the payment history, see payment history tab here https://www.bgs.org.uk/user/1/edit?destination=user/1 and click on when logged in as a non admin user. Needs a line or two adding to the bgs_profile.module to do this probably

**Comment by russ-manta** [comment]
@conferences-BGS this is now ready to look at in staging

**Comment by conferences-BGS** [comment]
@russ-manta @daniellaveda 
[INV_83568-paymenthistory.pdf](https://github.com/MantaRayMedia/bgs/files/2592994/INV_83568-paymenthistory.pdf)
Payment History pulling through a template which looks like an invoice that is due rather than a receipt
Will discuss with Veda about if this is the correct receipt to be pulling through

**Comment by russ-manta** [comment]
@conferences-BGS we don't have any detail of where to get a receipt from. Will have to ask Veda ourselves. Should we create a new ticket?

**Comment by conferences-BGS** [comment]
@russ-manta Existing ticket in Veda support already https://support.vedaconsulting.co.uk/issues/9585

**Comment by mrm-git** [comment]
➤ Russ Urwin commented:

Receipt issue with Veda now: https://support.vedaconsulting.co.uk/issues/9585
