### ISSUE TITLE
Events changes

### ISSUE THREAD

**Issue by matty-manta** [MantaRayMedia/bgs#326]
Booking online - some events are managed by external registration systems. To provide the book online button, the links section has been used. If the register link is not blank, then the register button should always appear (whether a user is logged in or out of the site). The events are still created in Civi (to create the drupal node) and the register start/end date fields are left blank. This is removing the book online link from the page when a user is not logged in.

**Comment by dilwarhussain** [comment]
@StephMSlack Can you check this is showing now please!

**Comment by StephMSlack** [comment]
@dilwarhussain I'm getting the register button when logged in, but also need to see the register button when logged out.
Its for this event - https://www.bgs.org.uk/events/living-well-in-older-age-preventative-and-anticipatory-care 

Logged in view
![screen shot 2018-09-04 at 14 40 52](https://user-images.githubusercontent.com/32127102/45035025-82990380-b048-11e8-8f79-8b357a652317.png)

Logged out view
![screen shot 2018-09-04 at 14 41 15](https://user-images.githubusercontent.com/32127102/45035034-89c01180-b048-11e8-9673-7ad855a27e36.png)

**Comment by StephMSlack** [comment]
@dilwarhussain - this is from the live site - let me know if I need to check your staging site instead

**Comment by dilwarhussain** [comment]
@StephMSlack Can you check this on the live site again please. Should be showing now.

**Comment by StephMSlack** [comment]
@dilwarhussain this is what I am getting on the live site now

![screen shot 2018-09-04 at 14 50 54](https://user-images.githubusercontent.com/32127102/45035491-a4df5100-b049-11e8-97bc-11efcb3842ac.png)

**Comment by StephMSlack** [comment]
Fixed
