### ISSUE TITLE
Evaluate this resource

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#329]
BGS staff can no longer access evaluation information submitted to the website and had been able to in the development/staging site. Sample email notifying staff of submission below. When logged in as web admin, receive a blank page with access denied in the tab.

Submitted on Sunday, August 12, 2018 - 19:46
Submitted by anonymous user: 10.0.0.211
Submitted values are:

Name: Laura Reid
Email: lauracreid1@gmail.com
Resource: https://www.bgs.org.uk/resources/deconditioning-awareness
The results of this submission may be viewed at:
https://www.bgs.org.uk/node/250/submission/249

**Comment by dilwarhussain** [comment]
@StephMSlack Web admins should have access to all webforms and results here now: https://www.bgs.org.uk/admin/content/webform in the 'Content' dropdown.

**Comment by StephMSlack** [comment]
thanks @dilwarhussain
