### ISSUE TITLE
Group/Region/member directory pages include BGS role

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#330]
Update API calls to include relationship type - co-chair of section/SIG committee

**Comment by StephMSlack** [comment]
Please also add:
Chair of Section
Chair of SIG
Co - Chair of SIG 
Co - Chair of Section
Chair of SIG
Chair of Section
the full list of relationships on Civi and whether they should be visible is attached. 
[Civi relationships shown on website.xlsx](https://github.com/MantaRayMedia/bgs/files/2335891/Civi.relationships.shown.on.website.xlsx)

**Comment by StephMSlack** [comment]
Is it also possible to also display this information based on whether the relationship is active? Inactive relationships have an end date
![screen shot 2018-09-12 at 13 38 07](https://user-images.githubusercontent.com/32127102/45425416-30cc2b00-b691-11e8-9064-c156e42ff0c7.png)

**Comment by russ-manta** [comment]
@StephMSlack I've added the other relationships listed above. Do you have a link you can point me to like the one you show in the screenshot above for Relationship end date?

**Comment by russ-manta** [comment]
@StephMSlack thanks that's helpful. Not sure how easy this is. For the end date are those relationships even if the end date is in the future? Should this contact Patricia Cantley be inactive even though the the current date falls within her start and end dates?

**Comment by StephMSlack** [comment]
@russ-manta the start and end date reflect their time in that role. So the relationship should show on the web page if the end date field is blank or has a date in the future. If the end date for the relationship is in the past, then the field shouldn't show on the web page. 

Once the relationship is in the past, the team here will be moving it to an inactive relationship, so if the above is not simple, the alternative might be that the relationship has to be current, and if it is inactive it should not show on the website (which may already be the case anyway)

**Comment by russ-manta** [comment]
@StephMSlack ok I can't do anything with the start end end date becuase some of the rationships don't have one but I've added a filter for Relationship = active so that the people will be removed form the group page if their relationship is set to inactive
