### ISSUE TITLE
External events

### ISSUE THREAD

**Issue by matty-manta** [MantaRayMedia/bgs#331]
Notification of submission emails should also be going to Conferences@bgs.org.uk

**Comment by russ-manta** [comment]
@StephMSlack they are now going to these 3: 'editor@bgs.org.uk, s.slack@bgs.org.uk, Conferences@bgs.org.uk'  should it just be Conferences@bgs.org.uk only ?

**Comment by StephMSlack** [comment]
@russ-manta going to all 3 email addresses is fine. Thanks
