### ISSUE TITLE
GDPR Text change

### ISSUE THREAD

**Issue by matty-manta** [MantaRayMedia/bgs#334]
Update the text in the SIG/Section GDPR information in Drupal
New text - “These bulletins are for any Section or Special Interest Groups you join - anyone can join a Section or SIG.
These are sent in order to keep you informed about the Section or SIGs activities and events.”

Old text - You are receiving this email as you opted in to a Section or Special Interest Group. These emails are sent in order to keep you informed about the Section or SIGs activity.

**Comment by StephMSlack** [comment]
@russ-manta this is in the my account section, update communication preferences tab, for users who are logged in. They currently see this:

<img width="1135" alt="screen shot 2018-09-18 at 11 03 28" src="https://user-images.githubusercontent.com/32127102/45680455-da4c6a00-bb32-11e8-96c5-a7d5b636d737.png">

**Comment by russ-manta** [comment]
@StephMSlack so should it go beneath the title at the top? 

I was confused because at the top of this card it says old text: 'You are receiving this email as you opted in to a Section or Special Interest Group. These emails are sent in order to keep you informed about the Section or SIGs activity.' but that doens't appear on the page.

**Comment by StephMSlack** [comment]
Hi @russ-manta When I am on the 'update communication preferences tab' and the 'create account' process, in the mail list sign up, under the text SIG & Section Bulletins heading is where the text needs to be replaced.

The screen shot below is what I see on the page when I am logged into one of my test accounts. This is the old text and needs to be replaced with the new text above.

![screen shot 2018-09-19 at 12 59 23](https://user-images.githubusercontent.com/32127102/45752020-1273ab80-bc0c-11e8-8b2c-14c689923826.png)

**Comment by russ-manta** [comment]
now done
