### ISSUE TITLE
Change order of resource series content

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#336]
Resource Series
Order of display within the series is currently oldest first, it should be latest first

**Comment by matty-manta** [comment]
eg https://www.bgs.org.uk/resources/resource-series/careers-and-workforce

**Comment by dilwarhussain** [comment]
@StephMSlack Is this in the correct order now?

**Comment by StephMSlack** [comment]
yes, thanks @dilwarhussain
