### ISSUE TITLE
Bouncing/jumping on roll over/hover with the box disappearing and reappearing (screen shots below taken less than 1s apart) [warranty]

### ISSUE THREAD

**Issue by matty-manta** [MantaRayMedia/bgs#338]
Equal heights must be set as default

┆Attachments: <a href="https:&#x2F;&#x2F;platform.harvestapp.com&#x2F;platform&#x2F;trello&#x2F;attachment&#x2F;5bf80cb7c844f61360b934b5&#x2F;TIoYXbzn">https:&#x2F;&#x2F;platform.harvestapp.com&#x2F;platform&#x2F;trello&#x2F;attachment&#x2F;5bf80cb7c844f61360b934b5&#x2F;TIoYXbzn</a>

**Comment by mikeode** [comment]
The problem arises when only one box has been added to a page. This has been resolved by checking how many boxs are on the page. If only one box, the 'card-with-summary' class is not added. This class is acted on by the mixin 'card-hidden-summary-paragraph-container' which is the source of the flickering. This mixin should be revisited as every entry in it is added as !important.

**Comment by mikeode** [comment]
Go live: move bgs.behaviour.js

**Comment by conferences-BGS** [comment]
@russ-manta Not sure what my action is? Is this deployed as a fix to live?

**Comment by mrm-git** [comment]
➤ Angie Vanhegan commented:

@russurwin can you clarify what Geraint's action is please? Thanks

**Comment by mrm-git** [comment]
➤ Russ Urwin commented:

@angievanhegan nothing really we just need to move live
