### ISSUE TITLE
Joining changes (4 hours)

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#342]
# Changes to Join Webform
The following fields added to final page of form: 
1.   	Date of Birth (mandatory)
2.   	Gender (Mandatory)
3.   	Phone number 

# Add conditional formatting:
Members to provide RCN/professional registration number based on profession chosen. RCN/ Other professional mandatory for: 
Advanced Clinical Practitioner, Advanced Nurse Practitioner, care home nurse, nurse, Occupational therapist, OT - dietician, paramedic, pharmacist, physiotherapist, speech and language therapist, physician associate
Note - currently on webform conditionals using Membership type and should be using the field 

# Update options displayed for joining as clinical fellow (profession field)
Joining as a Clinical Fellow presents two membership type options CMT or Registrar. Change membership type default view to blank (currently defaults to the lower price option of CMT) and allow users to choose an option from the drop down menu. If cannot show blank, can we default to Category A Registrar / specialty doctor

![Screen Shot 2018-08-29 at 11.17.34.png](https://images.zenhubusercontent.com/596d095761b4ca3b0a74b803/3d396655-76ec-4e59-be04-7fa821eef605)

# Overseas Members (Category C)
Shouldn’t be able to pay by Direct Debit. Needs removing
![Screen Shot 2018-08-29 at 11.17.47.png](https://images.zenhubusercontent.com/596d095761b4ca3b0a74b803/fa5d9617-9468-4131-a256-b88e20863399)

notes for RU. Changes to webform and bgs_behaviours.js to put live

**Comment by russ-manta** [comment]
@StephMSlack this is all now ready to test on staging: http://bgs-staging.mrmdev2.co.uk/bgs_membership

**Comment by StephMSlack** [comment]
thanks @russ-manta could the field GMC Number be mandatory for the Clinical Fellow profession type?
Otherwise, the rest of the form is fine. Thanks!

**Comment by conferences-BGS** [comment]
Close this task out

**Comment by angievanhegan** [comment]
This has been signed off, it just needs making live @russ-manta

**Comment by russ-manta** [comment]
These changes are now live

**Comment by angievanhegan** [comment]
@conferences-BGS Are you happy to sign this off?

**Comment by conferences-BGS** [comment]
@russ-manta @angievanhegan This is signed off
