### ISSUE TITLE
Press release content type {7 hours}[BGS:P2]

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#346]
Option 1: What would be the cost of creating a new content type - Press Release. This content type would need to be available in the news and policy section, in the feeds that go on the groups pages, and on the homepage (featured, latest).

Option 2) Alternatively - is it possible to create and assign a label to the News article content type, one called news and one called press release. If you could give me a cost for both please...

(1 day - roughly the same for either option, but we recommend option 1 to give you more flexibility)

* [ ] Press releases should also appear under Policy and Media (like news and policy) but just have a 'type' of Press release on these pages: https://www.bgs.org.uk/policy-and-media

- - -
**children:**

1. https://trello.com/c/JDcsWCFQ

**Comment by StephMSlack** [comment]
Approved by BGS 30/08/18

**Comment by StephMSlack** [comment]
@angievanhegan - Option 1 please, create the new content type please.

**Comment by russ-manta** [comment]
@conferences-BGS should press releases also appear under Policy and Media (like news and policy) but just have a 'type' of Press release on these pages: https://www.bgs.org.uk/policy-and-media

**Comment by angievanhegan** [comment]
Angie to chase up Geraint on question above about press release fields.

**Comment by conferences-BGS** [comment]
@russ-manta Please copy the fields from News content
