### ISSUE TITLE
Removing the topics from blogs published before 01/01/2017

### ISSUE THREAD

**Issue by matty-manta** [MantaRayMedia/bgs#349]
@angievanhegan have created this issue from the spreadsheet - estimated as half an hour and approved on the 22.08.2018

**Comment by angievanhegan** [comment]
@matty-manta This was part of Topic changes #317. I don't mind if it appears as part of that Epic or under support. Just let me know which you prefer.

**Comment by StephMSlack** [comment]
@matty-manta @russ-manta looking at this, all the topics have been removed from every blog (except those published in the last few days). The topics were only to be removed from those published **before** **01/01/2017**. 
Can this change be rolled back and the topics re-added for those blogs published between 01/01/2017 and now?

**Comment by StephMSlack** [comment]
@matty-manta Looks like the topics are still being used, (as the blogs are appearing in the topics pages) but the topics are not appearing on the Blog page or visible in the CMS

**Comment by conferences-BGS** [comment]
@angievanhegan @russ-manta Can you let us know if this task has been completed?

Also Recia thinks she is on the wrong github board - can you assist her? She's not on the list of contacts

**Comment by conferences-BGS** [comment]
Tested - awaiting final sign off by CEO but closing for now
