### ISSUE TITLE
Finalise hosting setup

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#35]
# Done criteria
- [x] **TRICKSY** finalising contract and cost (including Moodle and support details)
- [x] Make recommendation to BGS
- [x] Russ to send maintenance SLA 
- [x] Russ to send costs for hosting with High Availability (could use AWS calculator)
- [x] ISSUE: Confirm our proposal has been approved by Veda as fit for their purposes
- [x] Plan architecture
- [x] Agree any early milestones

**Comment by angievanhegan** [comment]
@russ-manta updated done criteria for you. @StephMSlack FYI

**Comment by russ-manta** [comment]
@StephMSlack is there any feedback on a proposed way forward with hosting based on our/veda's options?

**Comment by angievanhegan** [comment]
@russ-manta - @StephMSlack was thinking that we need to confirm with Veda that what we're proposing will work for Civi. Sounds like a good plan, what do you think? Thanks

**Comment by angievanhegan** [comment]
Steph confirmed that we're going to need to have more detail with the SLA contract to make it comparable with the Veda proposal. Steph to upload the document.

**Comment by StephMSlack** [comment]
Hi @russ-manta and @angievanhegan, I had put the draft SLA (as prepared by Adapta for Veda Consulting) up on Slack, rather than here. A copy now attached. Steph
[Draft Schedule 3 - Hosting.docx](https://github.com/MantaRayMedia/bgs/files/1474229/Draft.Schedule.3.-.Hosting.docx)

**Comment by russ-manta** [comment]
@StephMSlack @angievanhegan I've updated the hosting document with our changes. Please take a look and we should then share with Veda too.
[BGS-Draft.Schedule.3.-.Hosting-MRM-edit.docx](https://github.com/MantaRayMedia/bgs/files/1576117/BGS-Draft.Schedule.3.-.Hosting-MRM-edit.docx)
