### ISSUE TITLE
Issue importing sponsors and speakers to events in Civi in live

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/bgs#355]
# Done criteria
- [ ] See Veda issue here: https://support.vedaconsulting.co.uk/issues/8783#change-31680

**Comment by russ-manta** [comment]
[import_participants.zip](https://github.com/MantaRayMedia/bgs/files/2353071/import_participants.zip)

Errors when importing, did not create new participants on live. Will need to check with a new event

**Comment by russ-manta** [comment]
[TEST_Speaker_import_civi.zip](https://github.com/MantaRayMedia/bgs/files/2353313/TEST_Speaker_import_civi.zip)

Tried importing this test csv file on live and worked fine - unable to replicate. Need another example from BGS to test out any issues

**Comment by StephMSlack** [comment]
@russ-manta this looks like it may have been resolved. The team are not importing speakers again until November, so I will close this ticket and it can be raised again if it becomes an issue then.
