### ISSUE TITLE
"Get in touch" error [warranty]

### ISSUE THREAD

**Issue by matty-manta** [MantaRayMedia/bgs#363]
Members directory> Signed into directory but trying to contact a member produces this error
Error on andrea.geraint@gmail.com account as when masquerading as Stephen Abela

"Sorry you need to opt in to the members directory to contact fellow members."

**Comment by dilwarhussain** [comment]
@russ-manta For this one I think the custom field for 'opt-in members directory' changed on civi. It was "custom_271" but now I've replaced all to "custom_367" which seems to be the new field ID.

**Comment by conferences-BGS** [comment]
@russ-manta @angievanhegan Resolved
