### ISSUE TITLE
Ensure non members can view resources from an event they attended [warranty]

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#366]
# Done criteria
- [x] Main content section/nuggets is only visible after the event to members, administrators/editors and attendees of the event

┆Attachments: <a href="https:&#x2F;&#x2F;platform.harvestapp.com&#x2F;platform&#x2F;trello&#x2F;attachment&#x2F;5bf80cb7c844f61360b934b5&#x2F;F4iiR2OB">https:&#x2F;&#x2F;platform.harvestapp.com&#x2F;platform&#x2F;trello&#x2F;attachment&#x2F;5bf80cb7c844f61360b934b5&#x2F;F4iiR2OB</a>

**Comment by conferences-BGS** [comment]
All members and any one who attended the event should be able to see pdfs of the powerpoints from events
Eg.
https://www.bgs.org.uk/events/improving-continence-in-older-people-2018 
Information behind login wall
Series of resources to all attendees of the event and members

**Comment by conferences-BGS** [comment]
@russ-manta can you confirm if this is in live as well? Or will I need to test in staging ?

**Comment by russ-manta** [comment]
@conferences-BGS yes sorry, it's in live too

**Comment by conferences-BGS** [comment]
@russ-manta the function appears to work but need to discuss with Recia what she requested - currently this means we can only add to the event page as either 

- content block
video
photo gallery
attachments
FAQ

- form

**Comment by conferences-BGS** [comment]
@angievanhegan Then what Russ has delivered appears not to be this request. 

> All members and any one who attended the event should be able to see pdfs of the powerpoints from events
> Eg.
> https://www.bgs.org.uk/events/improving-continence-in-older-people-2018
> Information behind login wall
> Series of resources to all attendees of the event and members

**Comment by angievanhegan** [comment]
@russ-manta Let's chat about this one.

**Comment by BGS-Editor** [comment]
> @BGS-Editor @conferences-BGS It's my understanding that the requirement was just to have links to resources from the event page, so that the resources sections continues to be a repository for all your resources with access given according to membership/event attendance.

I am discussing this with G at the moment. In view of the structure of the presentation page, I envisage the powerpoints will be loaded as a resource on the main website (members and delegates only), with a link to this page from the 'past-event' page. Will come back to you when G and I have finished discussing.

**Comment by angievanhegan** [comment]
@BGS-Editor I think we both have exactly the same thing in mind Recia.

**Comment by mrm-git** [comment]
➤ Angie Vanhegan commented:

Recia - have you and Geraint finished discussing this yet? Thanks

**Comment by russ-manta** [comment]
@conferences-BGS badge change has now been made but we just need to get access to the new server before pushing this live

**Comment by mrm-git** [comment]
➤ Russ Urwin commented:

This is now live
