### ISSUE TITLE
Update personal details tab - some details not saving [with Veda] [Warranty]

### ISSUE THREAD

**Issue by russ-manta** [MantaRayMedia/bgs#368]
Reported by Disha - some of the details on this tab don't seem to save in Civi:
http://bgs-staging.mrmdev2.co.uk/user/1/edit/Personal_Details_28

It's a Civi profile 'embedded' in Drupal so it may be more of a Civi issue.
This is the Civi profile:
http://bgs-staging.mrmdev2.co.uk/civicrm/admin/uf/group/field?reset=1&action=browse&gid=28

┆Attachments: <a href="https:&#x2F;&#x2F;platform.harvestapp.com&#x2F;platform&#x2F;trello&#x2F;attachment&#x2F;5bf80cb7c844f61360b934b5&#x2F;7hU5LWXL">https:&#x2F;&#x2F;platform.harvestapp.com&#x2F;platform&#x2F;trello&#x2F;attachment&#x2F;5bf80cb7c844f61360b934b5&#x2F;7hU5LWXL</a>

**Comment by russ-manta** [comment]
@conferences-BGS @matty-manta  as reported by Disha, may be one to fix with Veda but needs more inspection

**Comment by conferences-BGS** [comment]
@russ-manta Have you ticketed it with Veda? If not, please do assigned to Daniella with Low Urgency/ Low importance

**Comment by russ-manta** [comment]
Now ticketed with Veda: https://support.vedaconsulting.co.uk/projects/veda-132/issues/new?issue%5Btracker_id%5D=1

**Comment by mrm-git** [comment]
➤ Russ Urwin commented:

issue with Veda now: https://support.vedaconsulting.co.uk/issues/9529
