### ISSUE TITLE
Enable resource series to be tagged with topics[BGS: P2]

### ISSUE THREAD

**Issue by mrm-git** [MantaRayMedia/bgs#369]
# Done criteria
* [x] Add Topics to resource series
* [x] Add a new tab on topics page for resource series.
* [x] Topics need to be visible on the resource series node (after the text)

NB. Add topics field on content type and export topics view to put live

- - -
**parents:**

1. https://trello.com/c/dbhNsUTg

**Comment by russ-manta** [comment]
@conferences-BGS see the example Resource series here: http://bgs-staging.mrmdev2.co.uk/resources/resource-series/careers-and-workforce

and tab here: http://bgs-staging.mrmdev2.co.uk/topics/acute-care

**Comment by conferences-BGS** [comment]
@russ-manta @angievanhegan Approved - please move to live
