### ISSUE TITLE
Create Press Releases[BGS: P2]

### ISSUE THREAD

**Issue by mrm-git** [MantaRayMedia/bgs#370]
Duplicate News CT. See Option 1 in epic. To appear in Policy and Media.

# Done criteria
* [x] Create CT fields (same fields as news)
* [x] Create views - latest/all feeds, homepage feature and curated views, policy and media landing page
* [x] Templates - node, teaser, teaser link (same as news)

- - -
**parents:**

1. https://trello.com/c/TIg2PnWI

┆Attachments: <a href="https:&#x2F;&#x2F;platform.harvestapp.com&#x2F;platform&#x2F;trello&#x2F;attachment&#x2F;5bf80cb7c844f61360b934b5&#x2F;JDcsWCFQ">https:&#x2F;&#x2F;platform.harvestapp.com&#x2F;platform&#x2F;trello&#x2F;attachment&#x2F;5bf80cb7c844f61360b934b5&#x2F;JDcsWCFQ</a>

**Comment by angievanhegan** [comment]
@conferences-BGS These are the fields for the news page, can you confirm it's ok to use all of these for the press releases. You'll also be able to add modules on the right hand side. 

-  Short title (used on cards)
- Full title (used on the page)
- Date
- Date updated
- Card image
- Body text

**Comment by russ-manta** [comment]
@mikeode I think there's an extra erroneous body field on the content type that can be deleted

**Comment by russ-manta** [comment]
@mikeode sorry, looks like the body field is still there - is that because we rolled back the database?  Can you remove it again?
Thanks

**Comment by mrm-git** [comment]
➤ Manta Ray Media commented:

@russurwin the field is now removed.

**Comment by mrm-git** [comment]
➤ Geraint Collingridge commented:

@mantaraymedia1 @angievanhegan Feedback was push to live, using fields and settings like a news content item 

Confirm what label will be attached (press release)

Query - what would need to be done to relist existing news content as press releases (BGS Assume create a new content type and cut and paste. We hope and dream of being able to move from news label to press release label but accept this might not be possible.)

**Comment by mrm-git** [comment]
➤ Angie Vanhegan commented:

@russurwin Please can you answer Geraint's questions, then move this into the 'Ready for live' column. Thanks

**Comment by mrm-git** [comment]
➤ Russ Urwin commented:

@angievanhegan 
Label is press release, see here: http://bgs-staging.mrmdev2.co.uk/policy-and-media

To move to press release content would need to be cut and pasted - sorry it's a different content type.

**Comment by mrm-git** [comment]
➤ Geraint Collingridge commented:

Thanks Russ @board push to live
