### ISSUE TITLE
External Jobs - Landing page [BGS: P2]

### ISSUE THREAD

**Issue by pipe-manta** [MantaRayMedia/bgs#375]
# Done criteria
* [ ] increase emphasis of gold highlight
* [x] Cards show: 
  * [x] Job title
  * [x] Location
  * [x] Organisation
  * [x] Deadline date
  * [x] Salary
* [x] Sort by
  * [x] Deadline
  * [x] Most recent
* [x] Submit a job (button at the top)
* [x] Redirect page after job submitted
* [x] Same log in options as external events (interim page with details for submission on RHS)
* [x] Jobs can only be edited by BGS once submitted
* [x] Content needs an expiry/auto unpublishing date
* [ ] Do we need a search? Nice to have if doable in the time otherwise leave for another time
* [x] Text at top of page (like External events)

- - -
**parents:**

1. https://trello.com/c/7tze4UTs

┆Attachments: <a href="https:&#x2F;&#x2F;platform.harvestapp.com&#x2F;platform&#x2F;trello&#x2F;attachment&#x2F;5bf80cb7c844f61360b934b5&#x2F;wtBmebZz">https:&#x2F;&#x2F;platform.harvestapp.com&#x2F;platform&#x2F;trello&#x2F;attachment&#x2F;5bf80cb7c844f61360b934b5&#x2F;wtBmebZz</a>

**Comment by mikeode** [comment]
@russ I've added the redirect. I've tested against a couple of accounts and it works ok. It's not particularly robust as it has to redirect to a specific content item. Additionally any new roles needing to be excluded from the redirect will have to be added to the custom code.

**Comment by russ-manta** [comment]
@mikeode A couple of things I've noticed so far
1. should we remove the field name 'description' from that field on display?  What do you think?
2. When creating an External job as a user I don't have access to the Description field, I get the message 'The field has been disabled because you do not have sufficient permissions to edit it' - presume we need to change the wysiwyg default input format or permissions?
3. How do I publish an external job as editor (or admin) - I can't see the publish checkbox

**Comment by mrm-git** [comment]
➤ Manta Ray Media commented:

@russurwin the first two should be addressed now. Can you please check and confirm? I'm still investigating the third. The standard permissions don't seem to be controlling this. Do you know where else this may be configured?

**Comment by mrm-git** [comment]
➤ Russ Urwin commented:

@mikeparmanand 1 & 2 look good. If you can unhide the Published checkbox then we're good to go with this one

**Comment by russ-manta** [comment]
@conferences-BGS please review the landing page: http://bgs-staging.mrmdev2.co.uk/jobs/external-jobs  gold items are currently showing first but we still need to add some kind of styling for these.  Also please confirm which filters/order you want in terms of ordering the items on this page - thanks

**Comment by mrm-git** [comment]
➤ Geraint Collingridge commented:

@angievanhegan Comments from this card https://trello.com/c/AWnuetqh/38-external-jobs-node-page-bgs-p2 are relevant here.

BGS have fed back but will repeat

Fields look OK 

Needs attention 
No email received by author (me) or me as reviewer (me) that the job had been submitted for review (are external emails enabled in your staging?)

As reviewer I went to content management  and changed/ updated the status  to "reviewed, payment requested" (would prefer not to do this) as all ads need payment

No payment request email sent to author

Still no link to payment system - stripe. 

Gold border needs expanding to make more prominent and to provide a ‘Featured’ job badge- the aim is for a  stand-out design with these jobs pinned to the top of the jobs page for their duration

**Comment by mrm-git** [comment]
➤ Angie Vanhegan commented:

@russurwin Feedback for you.

**Comment by mrm-git** [comment]
➤ Russ Urwin commented:

@angievanhegan payment requested radio is part of workflow to indicate that someone at BGS has looked at the item and processed as mentioned on the other card and as external events already work.

Also it wasn't clear that an automated email link to the payment form should be sent but if that is the case there has to be something to trigger it and this has to be once BGS have reviewed the content otherwise someone might pay first and then their content be rejected and the payment would have to be refunded. How can an automated email be sent with a payment link without BGS taking some kind of affirmative action to request the payment via checking a box or similar?

I can add another rule for this tomorrow but think we need to keep the 'payment requested' or similar radio button.

Re design I'll speak to the team and see what we can do

**Comment by mrm-git** [comment]
➤ Geraint Collingridge commented:

@angievanhegan if you review something like charity jobs the payment is part of the submission process.  All jobs need to pay to advertise so all need to pay and introducing a review and then send for payment results in an unnecessary delay. Bgs will still review before publishing so accepting payments and refunding if needed would be preferable. Īf process remains same as external jobs then most important for both of these is to send confirmation emails and a link to the user for payment via stripe

**Comment by mrm-git** [comment]
➤ Angie Vanhegan commented:

@russurwin Are you ok with this?

**Comment by mrm-git** [comment]
➤ Russ Urwin commented:

@Geraint @angievanhegan we pushed all the external jobs stuff live before Christmas which I'm sure I messaged about but now can't find the message (did I send it?!).
Anyway the upshot is that emails are now going out to the submitter and to editor@bgs.org.uk once a job is submitted and the submitter is currently directed to this page: https://www.bgs.org.uk/civicrm/contribute/transact?reset=1&id=3 straight away.

Is this the correct page?

Although this stuff is on the live site you need to know the url to find external jobs as it's not visible from any menus or linked from anywhere yet, it's here:
https://www.bgs.org.uk/about/external-vacancies

From here you can click the button to test submitting a job.
Are you happy to complete testing on live?

**Comment by mrm-git** [comment]
➤ Geraint Collingridge commented:

@mantaraymedia1 
Can you change the notification email to me

How are submitters to pay: the request was for both this and external events to push to stripe gateway and the submitter pay instantly

Once directed to send confirmations to me I can test

**Comment by mrm-git** [comment]
➤ Angie Vanhegan commented:

@russurwin see below

**Comment by mrm-git** [comment]
➤ Russ Urwin commented:

@Geraint @angievanhegan email now changed. Which stripe gateway is that, we've never used it - can you send details? 
All previous payments we have set up have gone via a Civi contribution page link.

**Comment by conferences-BGS** [comment]
The contribution page for Civi is https://www.bgs.org.uk/civicrm/contribute/transact?reset=1&id=4 for events

And for jobs is https://www.bgs.org.uk/civicrm/contribute/transact?reset=1&id=3

When last tested this didn’t result in anything occurring

**Comment by conferences-BGS** [comment]
Yes testing the contribution page that you link to it doesn’t take payment just a pledge to pay
Not whats needed: a link to stripe is


[cid:image001.png@01D4A6AB.181C6700]

**Comment by Geraint** [comment]
Could you guys would stop @ mentioning me, please?  I don't have anything to do with your project.

**Comment by mrm-git** [comment]
➤ Russ Urwin commented:

Both these contribution pages should now work ok (I've reconfigured the pages and tested them both in test mode):
Test advertising page is here:
https://www.bgs.org.uk/civicrm/contribute/transact?reset=1&id=3&action=preview  and you can use the card number 4242424242424242 for testing
You can test the live one using a real card if you want and I've changed the Job listing to £1 for that purpose:
https://www.bgs.org.uk/civicrm/contribute/transact?reset=1&id=3

The other payment page should also work in live:
https://www.bgs.org.uk/civicrm/contribute/transact?reset=1&id=4
or test mode:
https://www.bgs.org.uk/civicrm/contribute/transact?reset=1&id=4&action=preview

**Comment by mrm-git** [comment]
➤ Angie Vanhegan commented:

Feedback from Geraint: 

  * invoices to Amy and cc in finance@bgs.org.uk
the issues are
  * Staging site not accessible
  * Jobs - Payment form and form for submission still appear separate and need to be joined (submit form and payment together)

**Comment by mrm-git** [comment]
➤ Geraint Collingridge commented:

Jobs getting spammed with adverts for little blue pills as no payment wall
https://www.bgs.org.uk/node/4865/edit

**Comment by mrm-git** [comment]
➤ Angie Vanhegan commented:

All outstanding actions here: https://trello.com/c/YKBcV60f
