### ISSUE TITLE
External Jobs - Node page [BGS: P2]

### ISSUE THREAD

**Issue by pipe-manta** [MantaRayMedia/bgs#376]
# Done criteria
* [x] Deadline
* [x] Date Posted
* [x] Job type
* [x] Organisation
* [x] Location
* [x] Agency / Trust (who is advertising this)
* [x] RHS
  * [x] Attachments
* [x] Share

**parents:**

1. https://trello.com/c/7tze4UTs

┆Attachments: <a href="https:&#x2F;&#x2F;platform.harvestapp.com&#x2F;platform&#x2F;trello&#x2F;attachment&#x2F;5bf80cb7c844f61360b934b5&#x2F;SQQnEa8T">https:&#x2F;&#x2F;platform.harvestapp.com&#x2F;platform&#x2F;trello&#x2F;attachment&#x2F;5bf80cb7c844f61360b934b5&#x2F;SQQnEa8T</a>

**Comment by russ-manta** [comment]
I've added some comments to the other External jobs card which are also related to this one. Both interconnected

**Comment by conferences-BGS** [comment]
@russ-manta Will review internally but also need to see the 

- submission process
- The communications sent out to the submitter - is this CIvi?
- The payment process - a link sent, but is this civi?

**Comment by russ-manta** [comment]
@conferences-BGS you can test all this. There's a link to submit an External job here: http://bgs-staging.mrmdev2.co.uk/jobs/external-jobs  Once submitted an email is sent to BGS to review and approve and one also sent to the author.  Once payment is received BGS approve and publish the job and then the author is notified automatically by email

**Comment by conferences-BGS** [comment]
@russ-manta added http://bgs-staging.mrmdev2.co.uk/ceo
Fields look OK but need wider input
No email received to author or me as reviewer (are external emails enabled in your staging?)

Went to content and updated to reviewed, payment requested (would prefer not to do this if required)

**Comment by conferences-BGS** [comment]
@russ-manta  Feedback On the external page http://bgs-staging.mrmdev2.co.uk/add-an-external-job the RHS menu still shows content for external events. I assume we can replace this?

Submission guidelines
Reciprocal marketing can include:

Listing a BGS event on your website
Promoting a BGS event in newsletters or on Social Media
Circulating BGS flyers at your meetings
If you cannot undertake reciprocal marketing, the cost of promoting an event is £250 + VAT
If your event is being offered throughout the year, or in a series of different dates during the year, please state the earliest start date in the start date field. The different dates may be clarified in the description.
If your event fees differentiate between different professions, or you are charging discounted early bird rates, please state the lowest fee in the cost field and list the range of costs in the description.
The Intended Audience field has limit of 1200 characters
The Information about your event field has a limit of 1200 characters
* denotes a compulsory field

**Comment by mrm-git** [comment]
➤ Angie Vanhegan commented:

@russurwin Do you need to do anything here?

**Comment by mrm-git** [comment]
➤ Russ Urwin commented:

@angievanhegan the RHS content block can all be edited by BGS they just need to edit the page and edit the section: http://bgs-staging.mrmdev2.co.uk/node/4742/edit

The 'payment requested' radio button is for BGS to know where in the content workflow a specific item otherwise another editor couls easily come along and request payment again. This is the same as external events.

I'll check the emails again to make sure they are working as they should

**Comment by mrm-git** [comment]
➤ Russ Urwin commented:

This is now live with the external jobs landing page hidden from the menu for now: https://www.bgs.org.uk/about/external-vacancies

Emails are now working and the submitter is currently sent an email as soon as the job has been submitted with a link to pay here (BGS are sent a notification email to review at the same time): https://www.bgs.org.uk/civicrm/contribute/transact?reset=1&id=4

Both Gold and Silver jobs are currently available on the form so should we infact be sending a link to this page with another option for Gold on it? https://www.bgs.org.uk/civicrm/contribute/transact?reset=1&id=3

This is the link to submit a job: https://www.bgs.org.uk/add-an-external-job
You'll want to edit the text that appears on this page and the submission guidelines which you can do by editing this page:
https://www.bgs.org.uk/node/4837/edit

Re changing the styling of the gold items further we think they look good as is but perhaps best to discuss any finer points of styling with Steve.

**Comment by mrm-git** [comment]
➤ Amy commented:

Needs further discussion
