### ISSUE TITLE
To move live[BGS: P2] [With Veda]

### ISSUE THREAD

**Issue by pipe-manta** [MantaRayMedia/bgs#377]
# Done criteria
* [x] Add the new Group Related and Field Topic to Resouce Series content type
* [x] Export Topics view
* [x] CSS/JS/Templates
* [x] Rules
* [x] Import block: Button: See all external jobs
* [x] Press release: 
  * [x] Add CT to the views page
  * [x] Top feature home page
  * [x] Search (permissions)
* [ ] External jobs
  * [x] RHS blocks configuration
  * [x] Double check context
  * [x] Search (permissions)
* [ ] @mikeode Recreate BGS External jobs with the changes on [external_jobs view](http://bgs-staging.mrmdev2.co.uk/admin/structure/views/view/external_jobs/edit/job_attachment) view and new [external jobs context](http://bgs-staging.mrmdev2.co.uk/admin/structure/context/list/node_external_job/export)
* [x] BGS Features, push, copy, enable and revert

# Designs & Docs
* [Link goes here](http://)
* [Link goes here](http://)

# BGS review criteria
[Link to review goes here](http://)

* [ ] ?
* [ ] ?
* [ ] ?

**Comment by mrm-git** [comment]
➤ Angie Vanhegan commented:

Awaiting access to live server
