### ISSUE TITLE
Clarify what is members only content

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#39]
- [x] Steph clarify requirement
- [x] Angie captured requirement for inclusion into sprint goals
- [x] Russ knows about this requirement

# Requirements
### Examples of member only content FOR GO LIVE would be:
- BGS Newsletter
- Online grant application forms
- Information page about reduced hotel rates for members and other member benefits- 
- Event archives with video/powerpoint files from the event
- Podcasts/audio files
- SOME: Resources / fact sheets / good practice guides 

### Examples for future date:

- E-learning resources (free or reduced rate fee)
- Newsletter content
- May also need to display minutes of meetings, but further discussion required about whether this information should be member only and whether it would sit on the Nation/Region/SIG page or the members profile page.

**Comment by StephMSlack** [comment]
BGS do wish to create member only content. As per proposal, ability to preview and prompt to sign in to see more is required.
Examples of member only content would be:
o	E-learning resources (free or reduced rate fee)
o	BGS Newsletter **For go live**
o	Online grant application forms **For go live**
o	Standard content pages (e.g. information page about reduced hotel rates for members and other member benefits) **for go **live**
o	Access to event archives with video/powerpoint files from the event. **for go live**
o	Newsletter content
o	Podcasts/audio files **for go live**
o	Resources / fact sheets / good practice guides **for go live**

**Comment by StephMSlack** [comment]
May also need to display minutes of meetings, but further discussion required about whether this information should be member only and whether it would sit on the Nation/Region/SIG page or the members profile page.

**Comment by angievanhegan** [comment]
@StephMSlack Thanks for this. Can you just clarify that you're going to make all resources/fact sheets and good practice guides member only?

**Comment by StephMSlack** [comment]
@angievanhegan re: resources/fact sheets/good practice guides etc. not all will be member only, but they want the ability to make them member only if required.
