### ISSUE TITLE
Style FAQ nugget

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#48]
# Done criteria
- [x] Style nugget
- [x] ISSUE Line appears between each Q
- [x] **ISSUE** Make hover colour #F0F6FD

To check on [text-formats](http://bgs-dev.mrmdev.co.uk/about/text-formats-dont-delete) page

# Designs
Appears on [Our Purpose page design](https://invis.io/4XEFPWI2B)

# BGS review criteria
To check on [text-formats](http://bgs-dev.mrmdev.co.uk/about/text-formats-dont-delete) page
- [x] Matches design

**Comment by angievanhegan** [comment]
@pipe-manta The link to review it isn't working. I looked at the text format page and I can't see the FAQ links on there.

**Comment by StephMSlack** [comment]
@pipe-manta The FAQs in the designs had a coloured background, and it doesn't on the site

**Comment by pipe-manta** [comment]
Hi @StephMSlack That is part of the new hover design, I'm working on that. It will be ready at lunch time.

**Comment by pipe-manta** [comment]
Hi @angievanhegan The new hover colour is done.

**Comment by angievanhegan** [comment]
@pipe-manta lovely! Thanks
