### ISSUE TITLE
Style Box links

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#49]
# Done criteria
- [x] Style nugget - 4 across
- [x] Style nugget - 3 across
- [x] Style nugget - 2 across
- [x] Style nugget - 1 across
- [x] **ISSUE** text remaining at bottom with grey above
- [ ] **ISSUE** text in pink box is very close to the lower margin of the box on the 2, 3 and 4 wide (should we put a character limit on this field?)
- [x] **ISSUE** make the hover colour for these white

You can see the boxes on the About page http://bgs-dev.mrmdev.co.uk/about

# Designs
Appears on [About us landing page design]https://invis.io/U3EAE9BW9)

# BGS review criteria
You can see the boxes on the About page http://bgs-dev.mrmdev.co.uk/about
- [x] Matches design

**Comment by StephMSlack** [comment]
@ican-icant The boxlinks on the designs had the text remaining at the bottom of the box when no image was added (text then a grey box above). This hasn't been replicated in the build.

Also, the team box links with portrait images - the images look too big in comparison with the other images on the site.

<img width="1440" alt="screen shot 2017-11-22 at 16 52 35" src="https://user-images.githubusercontent.com/32127102/33139664-dee7493c-cfa5-11e7-827f-293c8140478c.png">
<img width="1433" alt="screen shot 2017-11-22 at 16 52 10" src="https://user-images.githubusercontent.com/32127102/33139665-defd3f76-cfa5-11e7-84b5-bbd4b7339a4c.png">
<img width="1440" alt="screen shot 2017-11-22 at 16 57 34" src="https://user-images.githubusercontent.com/32127102/33139839-4ed84200-cfa6-11e7-8694-e31f83b7f048.png">

**Comment by pipe-manta** [comment]
Hi @StephMSlack, I'm going to move this card to "In progress" to add the grey space above the text.

About the colour of the boxes, at the moment with nuggets you can choose different palettes with different combinations of colours. Only the Default has been currently designed, which has the light background and white boxes. I have updated the palette on "Who we are" section and now it looks fine.

I'm still working on the team nuggets have used portrait images like in design. I can enable additional cropping options to use on the team nuggets, and keep the portrait image only for people nodes if you prefer? Or can make these always use landscape as in the other box links, however in our experience we've found that clients usually struggle to crop portrait photos in anything other than portrait dimensions.

Let me know how you would like me to proceed or if you have any more questions.

All the best,
Pipe

**Comment by pipe-manta** [comment]
Hi @StephMSlack and @ican-icant , the grey background looks fine, but I'm still waiting the confirmation to proceed with the changes on the team nugget.

All the best,
Pipe

**Comment by angievanhegan** [comment]
@pipe-manta Is it possible for all the people images to be exactly the same size as they appear in the design? (https://invis.io/FWEFPVKRA) regardless of of they're 2, 3 or 4 wide? Ideally the 3 person team would just show 3 people then a blank for the 4th person.

**Comment by angievanhegan** [comment]
@StephMSlack We'll look at the images sizes for people/teams in the relevant issue (#64 and #52).

**Comment by angievanhegan** [comment]
@pipe-manta The four wide ones aren't looking that much like the design in Invision. Is it just a case of editing the content? 

Also, the text on the pink background is coming very close to the bottom of the box. I added an issue above.  Thanks

**Comment by StephMSlack** [comment]
@pipe-manta - the portrait for people in the box links when 6 across looks fine, but when it drops to 2/3/4 across the images become too large and overwhelm the rest of the page. Is there a way to keep the images in portrait format without this happening?
Also when you get to styling the slider option for the box links, could the arrows encouraging the user to scroll sit over the images on the right on the left of the page?

**Comment by angievanhegan** [comment]
@pipe-manta Steph is happy with the size of the images on these box links on this about us. This can go for sign off once you're ready. Thanks

**Comment by pipe-manta** [comment]
@angievanhegan Done on white

**Comment by angievanhegan** [comment]
Thanks @pipe-manta - I really like them white!!

**Comment by StephMSlack** [comment]
@angievanhegan @pipe-manta happy with the box size in landscape and the white hover
