### ISSUE TITLE
Style social links nugget

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#51]
# Done criteria
- [x] Style nugget
- [x] **ISSUE** Nugget follows the users as they scroll on the page (it only moves over the white space in the left hand margin and will now move to cover any box links, promos or the footer)
- [x] **ISSUE** Share icon should be the envelope and not an @ sign (see design( icon is in var/icons

To check on [Sample news page](http://bgs-dev.mrmdev.co.uk/%3Cfront%3E/news-page) 

# Designs
Appears on [Our Purpose page design](https://invis.io/YZEOPK1BT)

# BGS review criteria
To check on [Sample news page](http://bgs-dev.mrmdev.co.uk/%3Cfront%3E/news-page) 
- [x] Matches design

**Comment by angievanhegan** [comment]
@ican-icant @cat-manta do we really want these to follow people? Are they important enough?

**Comment by angievanhegan** [comment]
Hi @pipe-manta can you assign these to the person who needs to review them when you put them into this column? Ta :o)

**Comment by pipe-manta** [comment]
Sorry @angievanhegan, I have forgotten assign this card :P

**Comment by angievanhegan** [comment]
@cat-manta @ican-icant @StephMSlack do you think we really want the social media icons to follow the users as they scroll? I don't feel like social media is a top priority for these users...

**Comment by StephMSlack** [comment]
Hi @angievanhegan, @cat-manta  - yes I think we do want the social media icons to follow the users. BGS is looking to keep growing these comms channels and I think they are likely to get a fair bit of use around the blog or new campaigns/guides we produce.

**Comment by angievanhegan** [comment]
@ican-icant Can you look at this issue please and tell us what to do. Thanks

**Comment by ican-icant** [comment]
@StephMSlack Having social share icons fixed on the page means the page is more likely to be shared. An icon that follows users down the page doesn't necessarily facilate what you're after - the stats on this site are poor http://www.malariavaccine.org/ 

I think it would work best keeping the share icons where they are. 

FYI @angievanhegan

**Comment by StephMSlack** [comment]
Hi @pipe-manta @ican-icant @angievanhegan, I'm sorry, I'm not sure I understand the issue - what is the difference between the http://www.malariavaccine.org/ site where the icons stay at the top of the page and what is being proposed for the BGS site with icons sitting at the top left?  I have spoken to our comms manager and we both feel that it is important that the user can share content from where ever they are on the page. Especially for things like blog posts and our longer guides/reports which may be quite long, so users will need to scroll back up to the top of the page to share an article. 
We wouldn't want the version from the malaria site where you just see the sharing icon - not all users will know what that means, so we would  need to have all the SM options available to view.
Having the icons is not so essential for static pages such as who we are and what we do. They are more important for articles, resources, guides etc.

**Comment by StephMSlack** [comment]
@pipe-manta could the share icon for email be the envelope please, not the @ symbol? and the G+ symbol should be removed

**Comment by angievanhegan** [comment]
@StephMSlack Please can you confirm you're happy with the criteria for the behaviour of the SM links at the top of this issue? Thanks
