### ISSUE TITLE
Style person page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#52]
# Manta Ray done criteria
- [x] Style page to match design
- [x] **ISSUE** check size of social media icons (see Stephs comments)

To check on [Person](http://bgs-dev.mrmdev.co.uk/mr-dilwar-hussain) node page

# Designs
Appears on [Person page design](https://invis.io/KUEAEFQWN)

# BGS review criteria
To check on [Person](http://bgs-dev.mrmdev.co.uk/mr-dilwar-hussain) node page
- [x] Matches design

**Comment by StephMSlack** [comment]
@angievanhegan the Social media icons look too small. The connect box to the RHS seems too wide in comparison to content on left when compared to design - it looks like it should be one grid  further to the right. On site the connect box extends past social media icons in header and past newsletter sign up in footer, in designs the box aligns with newsletter sign up in footer and partway along the SM icons)

**Comment by angievanhegan** [comment]
@ican-icant Can you look at @StephMSlack feedback and check this please? thank you

**Comment by angievanhegan** [comment]
@ican-icant can you confirm that you've checked these issues too? Thanks very much.

**Comment by StephMSlack** [comment]
Fine
