### ISSUE TITLE
Style content block nugget

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#53]
# Done criteria
- [x] Style nugget
- [x] Ensure images can be added with caption
- [x] **ISSUE** confirm that text size of summary text is the same size in Drupal as it is in the design
- [x] **ISSUE** make the references text 1 pt bigger

To check on [text](http://bgs-dev.mrmdev.co.uk/about/text-formats-dont-delete) page

# Designs
Appears on [Our purpose page design](https://invis.io/4XEFPWI2B)

# BGS review criteria
To check on [text](http://bgs-dev.mrmdev.co.uk/about/text-formats-dont-delete) page
- [x] Matches design

**Comment by ican-icant** [comment]
@pipe-manta please check the text sizes in summary text bar against the design. The font appears smaller on the site.

**Comment by angievanhegan** [comment]
Hi @pipe-manta Is the content block not the normal content area (on here: http://bgs-dev.mrmdev.co.uk/about/text-formats-dont-delete) with the headings and images etc?

**Comment by pipe-manta** [comment]
Hi @angievanhegan Yes, I have used the content block nugget to made an example with all the headings and quote styles

**Comment by StephMSlack** [comment]
Hi @pipe-manta and @angievanhegan - the line which separates content feels like it should be wider (across the screen) and a heavier point size when compared to the designs.
The FAQs in the designs had a coloured background, and it doesn't on the site 
Have the font sizes for the summary text been changed? they are the same size on the test page
The reference/footer text is too small 
![screen shot 2017-11-29 at 10 40 05](https://user-images.githubusercontent.com/32127102/33371198-cd08a110-d4f1-11e7-80a8-a5b0c3861265.png)

**Comment by angievanhegan** [comment]
@StephMSlack 

- the dividing line in a separate issue (#80)
- the FAQ background colour is part of the hover styling (#60 ready for you to sign off)
- the font size for summary and footer I will send back for @ican-icant to confirm

**Comment by angievanhegan** [comment]
@ican-icant can you confirmed you checked the two issues and they're correct? Thanks

**Comment by StephMSlack** [comment]
@ican-icant @angievanhegan Should the text on this page go all the way to the edge of the white box? It does on the our purpose page in the designs, but that sample page had attachment/related links boxes on the right. 

The page in development doesn't have these boxes, but the text seems to stop 3/4 of the way across and leave some dead white space before changing to the other background colour.

![screen shot 2017-11-30 at 14 50 33](https://user-images.githubusercontent.com/32127102/33436803-f48f3a0e-d5dd-11e7-8d1a-5fcdc4e86b88.png)

**Comment by angievanhegan** [comment]
@russ-manta can you explain this please? Is this how this should work? Thanks

**Comment by angievanhegan** [comment]
@StephMSlack this has been sorted!

**Comment by StephMSlack** [comment]
Fine
