### ISSUE TITLE
Style video nugget

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#54]
# Done criteria
- [x] Style nugget
- [x] **ISSUE** please make video size one grid size smaller so that they are the same width as the images
- [x] **ISSUE** Can you put the video player on a background?

Appears on [Images and videos page](http://bgs-dev.mrmdev.co.uk/examples/images-and-videos)
# Designs
Appears on [Our Purpose page design](https://invis.io/3PEAE33G4)

# BGS review criteria
[Link to review goes here](http://)
- [x] Matches design

**Comment by pipe-manta** [comment]
@angievanhegan We are embedding videos from Vimeo and YouTube with his own player and colours

**Comment by angievanhegan** [comment]
@pipe-manta Please can you add an example video (and a link to it at the top to the page it appears on) so that we can show @StephMSlack? Thanks very much.

**Comment by angievanhegan** [comment]
@pipe-manta please can you show me how I can log in and amend this so that we can display the video alongside text (in the way that Steph will use it when she's creating real content) so that she can be sure this is going to work ok for her. Thanks

**Comment by pipe-manta** [comment]
@angievanhegan I have created more examples of the video on different positions with text. To add this videos is the same as other nuggets, just choose Video and then complete the text fields, paste the link to YouTube or Vimeo and choose the video position. Let me know if you have any question and we can share screens.

**Comment by StephMSlack** [comment]
@pipe-manta @angievanhegan I hope you don't mind, I switched the videos to align more with the kind of videos we might have on-site. I think it is safe to say that we are unlikely to use the full size centre aligned video option - it gets too big!

**Comment by StephMSlack** [comment]
@pipe-manta @angievanhegan I also tried adding an FAQ straight after inserting a video. I was thinking that we may need to add a transcript for a video in case someone cannot use sound. I used the FAQ nugget (which may not be the best option), as I just wanted something that would open/close so you would not see the transcript unless it was needed. 

The line for the FAQ showed directly beneath the video descriptive text rather than at the top of the FAQ, so it looked a little out of alignment 

I put it on the governance page http://bgs-dev.mrmdev.co.uk/about/governance

**Comment by angievanhegan** [comment]
@ican-icant The heavy line above the FAQ nugget is causing problems for Steph. Do you think we should take it out? Thanks

**Comment by pipe-manta** [comment]
@StephMSlack yes, you can use the FAQ. The issue with the line is fixed.

**Comment by StephMSlack** [comment]
thanks @pipe-manta

**Comment by StephMSlack** [comment]
@angievanhegan just showing the sample page to Recia - worried that the videos might be too big on the page so looking for some alternate feedback

**Comment by StephMSlack** [comment]
Hi @angievanhegan @pipe-manta - both Recia and I are thinking that the video boxes feel too big. I think this may be because while we may have videos from conferences, they are likely to be a mix of heads talking and powerpoint slides (not the most visually amazing!). Could we try 1 grid section narrower? 

Also, we hope to be in a situation in the future where we would display a number of videos on one page. Would we use this nugget for that as well? This group is about to produce a series of Research oriented videos for both organisations and I would like to be able to show these smoothly.
http://aeme.org.uk/mini-gems/

**Comment by angievanhegan** [comment]
@StephMSlack Can we tackle the requirement for displaying a larger set of videos later on? I'll create an issue for it so that we can look at it properly. 

@ican-icant Are you ok for us to go ahead and make the videos smaller or do you want to get involved? Thanks

**Comment by ican-icant** [comment]
@angievanhegan agree we need to make full screen videos smaller

**Comment by angievanhegan** [comment]
@pipe-manta over to you - please see issue at the top

**Comment by angievanhegan** [comment]
@pipe-manta Please can you make the video a bit smaller still? Thanks

**Comment by pipe-manta** [comment]
@angievanhegan Yes, it was BIG, now is using the 70% on normal and over.

**Comment by angievanhegan** [comment]
@StephMSlack this is ready for you to sign off now.

**Comment by StephMSlack** [comment]
Hi @pipe-manta @angievanhegan  the videos we wanted to be smaller were the Left/right ones. They currently take up 50% of the width of the page. Could these please be reduced please?

**Comment by angievanhegan** [comment]
@StephMSlack why did you put this one into the sprint backlog again? What did I miss? Ta

**Comment by StephMSlack** [comment]
Hi @angievanhegan I'd like the videos to be smaller (not as wide) - ideally 1 grid point - so the same width as the images.

**Comment by angievanhegan** [comment]
@StephMSlack Got it, I thought they'd already been made smaller! Oops.

**Comment by angievanhegan** [comment]
@pipe-manta That has made the images smaller too!

**Comment by angievanhegan** [comment]
@StephMSlack At the moment, both the video and images are at 40%. The images were originally 50%. You can have them different if you like. Let us know what you want to try.

**Comment by StephMSlack** [comment]
@angievanhegan is the play button on the video supposed to be the YouTube grey & red? Could it be one of the BGS colours (as styled by Cat?)

**Comment by angievanhegan** [comment]
@pipe-manta can you confirm that if we're embedding the videos then we don't get chance to style the play button? @StephMSlack that's my understanding. Sorry.

**Comment by pipe-manta** [comment]
@angievanhegan That is correct, we are using the embedding players

**Comment by angievanhegan** [comment]
Thanks @pipe-manta. Sorry @StephMSlack - it was a bit of a mix up. It's a shame, but I reckon the benefits of using YouTube probably outweigh the benefits of having a styled play button. Are you ok with that?
