### ISSUE TITLE
Iframe nugget

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#55]
# Done criteria
- [x] test by adding google map and style if necessary

http://bgs-dev.mrmdev.co.uk/examples/contact-us

# BGS review criteria
http://bgs-dev.mrmdev.co.uk/examples/contact-us

- [x] Can create Contact us page with Google map in it

**Comment by angievanhegan** [comment]
@russ-manta I can't make the google map iframe work in here. Can you try please? Thanks

**Comment by angievanhegan** [comment]
@StephMSlack This is ready for you to sign off.

**Comment by StephMSlack** [comment]
@angievanhegan I've tried adding a map to the site and I keep getting an error. http://bgs-dev.mrmdev.co.uk/sandbox/stephs-test-page

**Comment by StephMSlack** [comment]
@angievanhegan figured it out!
