### ISSUE TITLE
Design hover styles

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#60]
# Done criteria/BGS review criteria
- [ ] [Hover style](https://invis.io/4EDQ458R5#/263586181_Our_Purpose_W-Content):
  - [ ] share icon
  - [ ] link text/attachment

**Icons on header** (Steph would like to try another colour on the header - she's not sure about pink on purple) - see issue #81

**Comment by cat-manta** [comment]
@StephMSlack @angievanhegan I haven't done the header hover styles, but have done the rest of the hovers. I have put the link in the top comment.

**Comment by StephMSlack** [comment]
Hi @cat-manta - not sure about the pink hover over the purple promo

**Comment by angievanhegan** [comment]
Sorry @StephMSlack that wasn't a hover style to check!  We should probably have taken it out of the design (it's part of #67). Are you ok to sign off the ones listed at the top? Just let me know if it's not clear what's what. Thanks

**Comment by angievanhegan** [comment]
FAQ hover moved to #48
