### ISSUE TITLE
Design and style related content nugget

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#61]
# Manta Ray done criteria
- [x] Use 'short title' for title field
- [x] Shows maximum 3 lines of text
- [x] Shows publication date
- [x] Shows document type
- [x] Maximum of 3 related links
- [x] **ISSUE** Where a related link uses a 'page' content type, please don't display the label and/or date.  If possible make the page title (link text) use this space (so there doesn't appear to be a gap)
- [x] **ISSUE** Please make sure that the date shows in full e.g. December and not Dec

Note - we need to make sure that: 
a) words dont get cut off part way through
b) we have some visual indicator on the site so that people know there is more information / text

[Right hand column](http://bgs-dev.mrmdev.co.uk/examples/right-hand-column)

# Designs & Docs
Related content](https://invis.io/4EDQ458R5#/266149708_Our_Purpose)

# BGS review criteria
[Right hand column](http://bgs-dev.mrmdev.co.uk/examples/right-hand-column)
- [ ] Looks and works as per design

**Comment by cat-manta** [comment]
@StephMSlack @angievanhegan These have been updated, as well as the attachments. I have also changed a few things on Our Purpose, e.g. adding more blue to the design.

**Comment by angievanhegan** [comment]
Feedback from Steph - Boxes on RHS

Is there a limit to how many options/links that we could add within the box? Eg could we have 3 links for related content and 6 attachments listed. If not - should we set a limit to maintain the integrity of the design?
Can the boxes:

contain more than 2-3 lines of text per link?
have images within them (eg is the attachment is a printed document, we would have the document cover art that we could add here)
in the related content box, could we specify what type of document it is (blog, news, resource etc)

Are these boxes set to the top right of the page? And what is the impact visually of increasing their length if we add lots of text to them?

**Comment by angievanhegan** [comment]
@StephMSlack Can I recommend:

- you have no more than 3 related links (any more and it's just going to become noise)
- you keep the number of lines to a maximum of 3 (same reason as above)
- we don't add images to the related content links (same reason as above - less is more) they could always be added in the downloads section if they're very important - I just think it's better not to mix up the two boxes too much. 

Yes, the boxes are set to the top right of the page. And we are already showing the document type. 

@ican-icant feel free to weigh in!

**Comment by StephMSlack** [comment]
@angievanhegan As we wont be able to tell in the CMS when the title is likely to run over 3 lines, can we make sure that 
a) words dont get cut off part way through
b) we have some visual indicator on the site so that people know there is more information / text

**Comment by StephMSlack** [comment]
@angievanhegan 
happy with all other points (3 related links, no images in related content)

**Comment by angievanhegan** [comment]
@StephMSlack I'm assuming we'll use the 'short title' we talked about with Recia so it might be good to make sure that the short title fits here.  Let's build it and see! Over to you @pipe-manta!

**Comment by russ-manta** [comment]
@angievanhegan can you remind me what the short title is again?

**Comment by angievanhegan** [comment]
@russ-manta If full title is the long and descriptive title of an article or a resource (etc) then the short title will be the one that gets used on cards and any summary page. Is that ok?

**Comment by angievanhegan** [comment]
@ican-icant @StephMSlack I'm not sure that the document type is adding much here? Also, where we're using a standard page it's not very helpful to have the label 'page'. We could:

1. Remove the content type for 'page' if that's the type used
2. Remove all the content type lables
3. Something else?

What do you think?

**Comment by StephMSlack** [comment]
@angievanhegan Option 1 please - dont display the content type for page. But I do want it to display for article, blog, resource etc

**Comment by StephMSlack** [comment]
@angievanhegan also the date is showing inconsistently - one is 24 Dec 2017 other is 12-15 October 2017. Can we use the full name of the month as default?

**Comment by angievanhegan** [comment]
@StephMSlack this is ready for you to review now. Thanks

**Comment by StephMSlack** [comment]
@angievanhegan see comment on #89 re reducing text size
