### ISSUE TITLE
Style footer

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#63]
# Done criteria
- [x] Style footer
- [x] **ISSUE** RHS alignment of the footer menu with the top menu ( join/log out buttons)
- [x] **ISSUE** Social menu in the footer was the same as the design
- [x] **ISSUE** LHS alignment between the logo, breadcrumbs, footer information and footer menu
- [x] **ISSUE** The amount of space around the elements on the additional section has been removed.
- [x] **ISSUE** newsletter button and place to put email address does not appear

- [ ] **BLOCKED**  We are waiting for the mailchimp details to embed the subscription form.

# Designs & Docs
Appear correctly on [Our purpose page](https://invis.io/4XEFPWI2B)

# BGS review criteria
To check on [Demo](http://bgs-dev.mrmdev.co.uk/%3Cfront%3E/lorem-ipsum) news page
- [ ] Appears as per design

**Comment by angievanhegan** [comment]
@russ-manta Please can you estimate this? Thanks

**Comment by StephMSlack** [comment]
@angievanhegan See comment on #58 re: alignment of footer text

**Comment by angievanhegan** [comment]
@pipe-manta I moved over the comments from issue #58 as they related to the footer. I think they are all done. I just added a new one! Thanks

**Comment by angievanhegan** [comment]
@pipe-manta why is this is blocked/tricksy? If you can added something like this at the top that'd be great 

- [ ] **BLOCKED** then add a description of why it's blocked.

**Comment by angievanhegan** [comment]
@StephMSlack Can you give us the mailchimp details to embed in the subscription form please? Thanks

**Comment by StephMSlack** [comment]
@angievanhegan - Matty asked me to respond to this one in Slack 
The newsletters will be managed through CiviCRM and either via Mailchimp or Mandrill (tbc). We have a members only newsletter, then different e-bulletins so any e-newsletter sign up will need to go to a communications management page which will be managed through Civi.

**Comment by angievanhegan** [comment]
@StephMSlack ok - I'll create another issue to get this connected up later on. I'll assume the rest is ok and move this one to done. Thanks
