### ISSUE TITLE
Style team nugget

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#64]
# Done criteria
- [x] Style nugget
- [x] Show the roles people have
- [x] **ISSUE** names being cut off at the bottom using Chrome (see image below)
- [x] **ISSUE** add checkbox to display the team role on the image
- [x] **ISSUE** ensure that the field under their name is their job title (not their role on the board)
- [x] **BLOCKER** when adding 3 across, the images appear much too large. 
- [x] **ISSUE** white space appearing under the image for some images

To check on [Teams page](http://bgs-dev.mrmdev.co.uk/examples/teams-page)

# Designs & Docs
- [Governance page](https://invis.io/FWEFPVKRA)

# BGS review criteria

To check on [Teams page](http://bgs-dev.mrmdev.co.uk/examples/teams-page)

- [x] Appears as per design

**Comment by angievanhegan** [comment]
@russ-manta Please can you estimate this?

**Comment by angievanhegan** [comment]
@pipe-manta Is it possible for all the people images to be exactly the same size as they appear in the design? (https://invis.io/FWEFPVKRA) regardless of of they're 2, 3 or 4 wide? Ideally the 3 person team would just show 3 people then a blank for the 4th person.

**Comment by angievanhegan** [comment]
@pipe-manta Please can you put in an example of a team of 2, 3 or 4 people so that Steph can see that too? Thanks.

**Comment by angievanhegan** [comment]
<img width="417" alt="screen shot 2017-11-28 at 08 50 30" src="https://user-images.githubusercontent.com/3796718/33323039-3ab3018a-d419-11e7-9cbd-dca8533f45ae.png">

**Comment by angievanhegan** [comment]
@ican-icant advises using 4 in a row layout but only inserting 3 pics. Steph is checking with Recia. This will most likely work ok in the about section but we may need to revisit for the 'BGS groups' pages where teams are often of 3.

**Comment by StephMSlack** [comment]
@angievanhegan @pipe-manta for some reason, both Recia and I are seeing a small white space underneath some images before the hot pink line. It shows on different box links - Screen shot 1 is from Recia, 2 is from my screen. Happy with either view, but just want to make sure it will be consistent. 

![screenshot1](https://user-images.githubusercontent.com/32127102/33604597-77629466-d9ae-11e7-8e12-cb3bf9e49d26.jpg)
![screen shot 2017-12-05 at 10 38 45 2](https://user-images.githubusercontent.com/32127102/33604603-7ea5efc0-d9ae-11e7-95b5-0549483cdacf.png)

**Comment by angievanhegan** [comment]
@russ-manta See Steph's images where a space is being added. I've added an issue into the done criteria. When I was building the page, sometimes it asked me to do the card crop and sometimes it insisted on the other crop (person portrait?) Might that be the source of the problem? Thanks

**Comment by angievanhegan** [comment]
@StephMSlack this looks fixed to me, but you and Recia should check too. Thanks

**Comment by StephMSlack** [comment]
thanks guys
