### ISSUE TITLE
Apply hover styles (in Drupal)

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#65]
# Done criteria/BGS review criteria
- [ ] [Hover style](https://projects.invisionapp.com/share/4EDQ458R5#/screens/263586181_Our_Purpose_W-Content)
  - [x] share icon
  - [x] link text
  - [x] attachment text (all right hand side) should be the same as the link text (see notes below)

Appears on:
- http://bgs-dev.mrmdev.co.uk/examples/text-styles
- http://bgs-dev.mrmdev.co.uk/examples/right-hand-column

**Comment by angievanhegan** [comment]
@russ-manta Please can you estimate this? Thanks

**Comment by angievanhegan** [comment]
@pipe-manta I you've done this already?

**Comment by russ-manta** [comment]
@angievanhegan pipe is not sure the design is decided yet. Can you confirm?

**Comment by angievanhegan** [comment]
@pipe-manta Yes, the two listed above are signed off. Thanks

**Comment by angievanhegan** [comment]
@pipe-manta looking at this on the site, I know this is what we said we wanted on Thursday, but I realised that we've now got the link colours in the main text and the right hand side changing in exactly the opposite way:

- Content area: Pink link -  dark purple on hover
- Right hand side: Dark purple links - pink on hover

I think we should choose one, or it's a bit confusing for the user. I think we should use the content area combination: Pink links which go dark purple on hover. 

Thanks (and sorry to change this again!)

**Comment by angievanhegan** [comment]
@StephMSlack This is ready to sign off. We've just made sure that the links are all the same colour so that it's consistent for the user. We can revisit this in Jan  if we do a colour (de-pinking) review. Thanks

**Comment by StephMSlack** [comment]
Hi @angievanhegan  I appreciate we need the consistency between all the hover styles, but turning the attachment text pink (so we have a purple hover) is drawing the reader away from the content on the page. Sorry, but I think we need to change it back. 

Also links to my comment on #89 re reducing the size of the text in the Right columns

**Comment by StephMSlack** [comment]
@angievanhegan - have followed this up with a discussion with colin who is not as worried about the pink. Can we revisit this when we have reduced the text size in the right hand column? Hopefully it wont pull attention as much and we can keep the hover consistent.

**Comment by angievanhegan** [comment]
@StephMSlack Yes, we'll revisit in Jan when there's more content in :o)
