### ISSUE TITLE
Design and style header and footer for tablet

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#66]
# Manta Ray done criteria
- [x] Header styled for tablet
- [x] Footer styled for tablet

Link to check: http://bgs-dev.mrmdev.co.uk/examples
(although any page on the site will do!)

# Designs & Docs
https://invis.io/4EDQ458R5#/265157140_Our_Purpose_Tablet_V0-2
(version with the BGS strapline and no social media icons in the header)

# BGS review criteria
Appears as per design
- [x] Header styled for tablet
- [x] Footer styled for tablet

Link to check: http://bgs-dev.mrmdev.co.uk/examples
(although any page on the site will do!)

**Comment by cat-manta** [comment]
@StephMSlack @angievanhegan Here are the links for the tablet footer and header, with two versions of the header (with and without the strapline and social media icons).

https://invis.io/4EDQ458R5#/265000035_Our_Purpose_Tablet
https://invis.io/4EDQ458R5#/265157140_Our_Purpose_Tablet_V0-2

**Comment by angievanhegan** [comment]
@ican-icant Please can you sign off these designs, then we can put them over into steph's column for her to sign off. Thanks

**Comment by ican-icant** [comment]
@StephMSlack let us know what version you prefer. Cheers

**Comment by StephMSlack** [comment]
@cat-manta @ican-icant please use the version with the BGS strapline and no social media icons in the header. V0.2
Also see query re: colour of social media icons in footer

**Comment by angievanhegan** [comment]
- @pipe-manta Steph has selected her preferred version (this is the only design link which appears at the top)
- @cat-manta Please can you update the files in Invision to show which one Steph has approved
- @StephMSlack Sorry, which issue has your comments about the colour of the social media icons in the footer? (bear in mind that Cat is introducing more blue on the site and the purple, pink and blue are working nicely together I think)

Thanks everyone!
