### ISSUE TITLE
Design promos

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#67]
# Manta Ray and BGS done criteria
- [x] **Age and Age promo** (specifically for Resources landing page) 
Text: Read our international journal publishing refereed original articles and commissioned reviews on geriatric medicine and gerontology
- [x] **Become a member promo** (specifically for Events section) 
Text: Join a multidisciplinary professional organisation improving healthcare for older people; Membership is free for medical students and foundation year doctors
- [x] **Event promo** (for Events and Careers and Education section)
BGS Spring 2018 11th - 13th April 2018 NCC, Nottingham
3 day educational conference for those providing healthcare of older people.
 

# Designs 
-  Draft designs: https://invis.io/BSF98SH9Q

**Comment by angievanhegan** [comment]
This is the main clinical resource so it's very important it can be featured on the resources landing page.

**Comment by angievanhegan** [comment]
@StephMSlack I'd like for us to create 3 sample promos so that we can develop a style for them. These three seem to me the three that we need. I think we can do a better job if we have some text. Would you be able to add some at top of this issue please? I think it only needs to be a call to action. 

I've added a link to the work Cat has done so far. 

Thanks

**Comment by StephMSlack** [comment]
@angievanhegan @cat-manta 

I have asked the team for some text, but here are some initial options. (not my strong point!)
Membership
BGS membership has been a crucial influence in my career. Professor David Oliver
Join the BGS today

Age & ageing 
Read our international journal publishing refereed original articles and commissioned reviews on geriatric medicine and gerontology

**Comment by angievanhegan** [comment]
@StephMSlack Thanks for these. Can you give some text for the e-learning promo too please? Thanks

**Comment by StephMSlack** [comment]
@cat-manta Updated Membership text:
  Membership 
Join a multidisciplinary professional organisation improving healthcare for older people; Membership is free for medical students and foundation year doctors

Chasing on e-learning text for you

**Comment by angievanhegan** [comment]
@StephMSlack You'll be able to put anything you like in a right hand banner: text, links, images, lists a 'card' for another page (see examples here http://bgs-dev.mrmdev.co.uk/examples/right-hand-column)

**Comment by angievanhegan** [comment]
@cat-manta Steph's provided sample text for the promos so you can go ahead and work on the design now. Thanks.

**Comment by angievanhegan** [comment]
@StephMSlack these are ready for you to review. Thanks

**Comment by StephMSlack** [comment]
@cat-manta @angievanhegan overall happy with these, except they would like to swap out one of the pictures with an alternate image. I'll be able to get one to you next week when I am back in the office. Otherwise, everyone is happy with the promo

**Comment by angievanhegan** [comment]
Great! Thanks

**Comment by angievanhegan** [comment]
@cat-manta This can move to signed off in Invision
