### ISSUE TITLE
Design and style table formatting

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#68]
NOTE: This is issue is just for the TABLE design - please ignore the rest for now!

# Done criteria - Manta Ray and BGS
- [x] Header and rows style

# Designs & Drupal links
- Can be seen on [Event node](https://invis.io/4EDQ458R5#/272769970_Event-Node)
- Drupal link: http://bgs-dev.mrmdev.co.uk/dilwar-test-page

<img width="863" alt="screen shot 2018-02-20 at 07 50 59" src="https://user-images.githubusercontent.com/3796718/36427448-d6c8d87a-1612-11e8-88b2-8656ec82cded.png">

**Comment by angievanhegan** [comment]
@russ-manta @pipe-manta This one is ready for build

**Comment by StephMSlack** [comment]
Hi @angievanhegan I had Recia look at this. She wanted to confirm that we would be able to build tables with the style of content below - greater number of columns, a larger amount of text in the columns:
http://www.bgs.org.uk/decisionaid/campaigns/dignity2006/dignitydecisionaid
http://www.bgs.org.uk/environmentaudit/campaigns/dignity2006/dignityenvironmentalaudit

She also wanted to check if we would be capable of including a table with this format - if we have a table where one of the columns has pictures; and the second column has text. E.g. will be able to vertically-align the text to the top of the second column’s cells. I don’t think we can discount having to do this sort of thing.

My question - would all tables on the site have this styling or would we be able to turn the styling on/off depending on the need of the page

**Comment by angievanhegan** [comment]
@StephMSlack 

1. Yes, you can add more columns and text (and text can be aligned to the top)
2. We wouldn't normally recommend using tables like this anymore (for issues of responsiveness). Can you send an example of the content so we can see if we can suggest another way of doing this?
3. The table style is optional, but we'd recommend using it for consistency. We can set it so it's styled by default but the style can be removed if you like?

**Comment by ican-icant** [comment]
@dilwarhussain table looks great but caption title needs to be left aligned

**Comment by angievanhegan** [comment]
@dilwarhussain Is the table styling optional by the way? If it's something that can be applied, please can you show me how, I can't work it out. Thanks.

**Comment by dilwarhussain** [comment]
Hey @angievanhegan The table styles are applied everywhere at the moment, but I can create a class to strip the styles. Are the styles in the image below okay for the stripped down table?
![image](https://user-images.githubusercontent.com/29142647/36429298-3cab357a-164a-11e8-9be5-12ac3045c239.png)

**Comment by angievanhegan** [comment]
@dilwarhussain that stripped back style looks great to me. Thanks.

**Comment by dilwarhussain** [comment]
@angievanhegan I've added the styles and class, see test page for two tables. How to apply the class will be covered in the training but if you need a quick demo how to apply I can show you over a zoom call. Thanks!

**Comment by StephMSlack** [comment]
Thanks @dilwarhussain yes, around today. I could do a call now or after 2:30?

**Comment by StephMSlack** [comment]
@angievanhegan all good to go
