### ISSUE TITLE
Ensure we have all nuggets for archive content in About us section and plan for IA

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#74]
# Done criteria
- [x] Person page
- [x] Sharing icons on the left – for sharing new articles
- [x] Related content 
- [x] Standard content page (using headers, quotes, images video etc)
- [ ] Tables
- [x] Attachments
- [ ] Content type (most will be articles)
- [ ] Topics
- [x] FAQ
- [ ] Image gallery

**Comment by StephMSlack** [comment]
@angievanhegan - still to be confirmed by Recia, but this is the initial list for the archive:
Person page (for biographies, without the connect nugget on the RHS) http://bgs-dev.mrmdev.co.uk/dr-eileen-burns
Sharing icons on the left – for sharing new articles
Related content – for pushing people to other archive content or other parts of the site
Standard content page (using headers, quotes, images video etc)
Tables
Attachments (unlikely to be needed, but just in case)
Content type (most will be articles)
Topics
FAQ (accordion to open/close content)
Image gallery (for historical images or pics of newsletter covers with links to PDF copies)

**Comment by StephMSlack** [comment]
@angievanhegan Recia has checked this list and signed it off

**Comment by angievanhegan** [comment]
@StephMSlack Thanks for this. I've put it on our agenda for things to talk about.

**Comment by angievanhegan** [comment]
@StephMSlack I wasn't expecting we'd use the topics tags in this section, or the article content type. If you think it's something we'll need, can you tell me more? Thanks
