### ISSUE TITLE
Title alignment depending of the page

### ISSUE THREAD

**Issue by pipe-manta** [MantaRayMedia/bgs#75]
# Done criteria
- [x] Centre for Landing
- [x] Left for other pages

# Designs & Docs
- [Link goes here](http://)

# BGS review criteria
[Link to review goes here](http://)
- [x] tiles on landing pages align centre: http://bgs-dev.mrmdev.co.uk/examples
- [x] titles on content pages align left:  http://bgs-dev.mrmdev.co.uk/examples/text-styles

**Comment by angievanhegan** [comment]
@pipe-manta Please can you add an estimate to this issue? Thanks
