### ISSUE TITLE
Design resources page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#76]
# Done criteria
- [x] Create design as per wireframes on RT board
- [x] **BLOCKER** need to resolve sticky heading navigation issue

# Designs
- [Wireframes on RT board](https://realtimeboard.com/app/board/o9J_k0NkHnc=/?moveToWidget=3074457345944839528)
- [Design](https://invis.io/DQEPLPAY4)

**Comment by angievanhegan** [comment]
Feedback from @StephMSlack on design so far: 

- content top of the page looks good (doc type and dates etc)
- there's a lot going on when scanning across the top part of this page (different background colours, greys especially)
- likes the blue colours for the heading nav, but preferred the tab style used in the black and white version
- 'feedback on this resource' should have much less emphasis. It's not something they're trying to generate, they just want it to be available if anyone does want to give feedback. It needs to be clear it relates to this particular resource


From Angie:

- I don't think we need the horizontal line to separate the resources
- Can you make the title of the download a real title instead of a filename please?

**Comment by StephMSlack** [comment]
Hi @angievanhegan @cat-manta Positive feedback regarding the resources designs. Query about whether the download image could be slightly smaller and if that image would also be a link to the file?
Colin would like to change the name sections to something else (he didnt feel it was self explanatory enough), he suggested something like content, navigate to or article content. I am sure we will be able to name this ourselves, but just in case we cannot...
Other than those small things, everyone is happy with the layout, styling, features etc.
Thanks!

**Comment by angievanhegan** [comment]
@StephMSlack Excellent! Absolutely, you can pick the heading for the headings jump links. Can I suggest that we go ahead with the larger cover, then see how it all looks when it's built in Drupal? As you know, it's a quick thing to change and proportions are always going to look slightly different when you see the design in your browser window. Thanks

PS - yes, the image would be a link to the file.
