### ISSUE TITLE
Build resources page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#77]
# Done criteria
- [x] ~~**ISSUE 11** Additional docs lines not aligning~~
- [x] ~~BLOCKER - topics need tidying first~~
- [x] ~**ISSUE 10** can we reduce the space between the end of the comment box and then 'you may be interested in/in this series' boxes? there is a lot of white space which makes the page really long~
- [ ] ~**ISSUE 9** The text you may also be interested in is appearing when there is no programatic feed below~
- [x] ~~**ISSUE 8** When anonymous user visit a resource without content on the RHS, there is an empty space created by the hidden evaluation form. See [example](http://bgs-dev.mrmdev.co.uk/resources/boxni-the-dog) We need move that form to the content/additional area to display the content with the full width and change the css + .js respectively.~~
- [x] ~~**ISSUE 7** Programatically selected links to appear at the bottom under the heading 'you may also be interested in' are not appearing. See [example](http://bgs-dev.mrmdev.co.uk/resources/boxni-the-dog) There is another resource with the topic of diabetes (this should show first in the list) then there are other resources which are the same type (good practice guide' which should show as well~~
- [x] ~~**ISSUE 6** Manually set related links only appear at the bottom (under the heading 'you may also be interested in' and never on the right hand side~~
- [x] **ISSUE 5** You may also be interested in (related content) should only apply to other resources
- [x] ~**ISSUE 4** Related resources don't appear on the right hand side, they appear at the bottom under the heading ' you might also be interested in' ([see design](https://invis.io/DQEPLPAY4))~~
- [x] ~~**ISSUE 3**:  Related content should be chosen programatically based on topic, then  document type. The editor should be able to 'turn off' the programatic option if they need to select the related resources manually. This will be done by choosing different nuggets. 1. A related content nugget that is automatic based on topic & document type, 2. A nugget which enables them to choose custom related content ( think we have something similar on ALNAP) **ESTIMATED at 1/2 day £280 + VAT**~~
- [x] ~~**ISSUE 2**: Editors need to be able to add inline images to the body copy (Await feedback from client before progress on this issue)~~
- [x] ~~**ISSUE 1**: Resources don't have an image for the card content, please can you remove this field from the content type~~
- [x] ~~Title (to appear on the card)~~
- [x] ~~Long title to appear on the page~~
- [x] ~~Document type (with popup like the ['i' on this site](https://wellcome.ac.uk/funding/hub-award))~~
- [x] ~~Published date~~
- [x] ~~Last updated date~~
- [x] ~~Summary (300 words max) - this will need to be a separate field so that it can be displayed for people who are not logged in~~
- [x] ~~Headings/jump links (only in content block)~~
- [x] ~~Section divide (for use within wysiwyg)~~
- [x] ~~Section highlight style~~
- [x] ~~References (with or without jump links)~~
- [x] ~~Other resources in this series (which also hides related content)~~
- [x]~~ Feedback on this resource (emails URL, comment and optional email address)~~
- [x] ~~Download~~
  - [x] add field for PDF and a cover image field which works in the same way as the ALNAP main report file and cover image fields 
  - [x] if the resource is in a series, an additional link is displayed within the box (below the link text) with a link to 'download all the resources in this series'. There will be be one PDF doc of all the resources in the series which appears in this position on all resources in the series
- [x] ~~Author (links to member page if they are a member and they've agreed to be in the directory) see #92 for full requirements~~
- [x] ~~Tags (topics) (link to topic page?)~~
- [x] ~~Members only link (links to login page)~~
- [x] ~~Clinical/Research resource tick box (they can select both options on one resource - it's not either/or)~~

**View for non-logged in users**
- [x] Title
- [x] Resource type
- [x] Published date
- [x] Last update date
- [x] Summary (see not above)
- [x] Author
- [x] Tags

# Designs & Docs
- [Wireframes on RT board](https://realtimeboard.com/app/board/o9J_k0NkHnc=/?moveToWidget=3074457345944839528)
- [Content model](https://www.lucidchart.com/documents/edit/6745084e-6199-4704-98de-8cc6d5391298/0)

**Comment by angievanhegan** [comment]
@russ-manta Please can you estimate this?

**Comment by angievanhegan** [comment]
@russ-manta I have added all the things that need to appear on the page in the done criteria. I'm guessing this is too much for the 'build' task though and that the full list should be in the styling issues.

**Comment by russ-manta** [comment]
@angievanhegan I've just been speaking with @meldera about this. He's starting but we have a few questions (maybe I have forgotten some stuff!).
1. Document type popup - can you confirm what should be in the popup?
2. Summary should this be a separate field to the main content block and/or is this different from the card summary?
3. Jump links in content block - are these anchor links or something different?
4. References jump links - could these just be sub/superscript anchor links in the main content to references at the bottom of the page?

**Comment by angievanhegan** [comment]
@russ-manta 

- Document type popup - it just needs to be one or two sentences of plain text. 
- Summary - this may need to be a new field? It's a (up to) 300 word summary of the document.
- Jump links in content block - these are probably anchor links. We realised we're going to have to revisit the design of the page though as these really don't work here in the middle of the page. 
- References jump links - yes, could just be sub/superscript anchor links in the main content to references at the bottom of the page If that takes a while to do, then they don't need to have links. 

Would you like me to add these as issues under the done criteria?

**Comment by meldera** [comment]
@angievanhegan Regarding "Document type popup"  -  what is being meant by a "popup"?

**Comment by angievanhegan** [comment]
@meldera Like the box you see if you click the  'i' on this page
https://wellcome.ac.uk/funding/hub-award

**Comment by angievanhegan** [comment]
@meldera I just want to check you know that we don't have a signed off design for this, we just want to enable the client to add their content in the short term? Thanks

**Comment by angievanhegan** [comment]
@russ-manta Please can you sent the names of the fields in Drupal for resources so that @StephMSlack can add them to the spreadsheet of resources she is preparing for migration. Thanks

**Comment by russ-manta** [comment]
@angievanhegan  can you confirm what the download field is?  Is it just a file field (single or multi value?) there is nothing in the content model

**Comment by meldera** [comment]
[ ] "You may also be interested in (related content) + see all link (based on topic and document type) *TBC if this is done using references or just using related tags"
  -  we already have both options available in remora. how would either of these be different?

[ ] "Angie to confirm where Topic tags link to"
  -  already specified in #104 and built accordingly

**Comment by meldera** [comment]
[ ] "Clinical/Research resource tick box (they can select both options on one resource - it's not either/or)"
- what should this field be called?

**Comment by angievanhegan** [comment]
@StephMSlack What should we call the field where the editor chooses if the resource is clinical or research? Thanks

**Comment by angievanhegan** [comment]
@meldera The clinical/research resources have already been given an interim name - we're just waiting for a final one from @StephMSlack .

@russ-manta Can you answer this question for @meldera please?

[ ] "You may also be interested in (related content) + see all link (based on topic and document type) *TBC if this is done using references or just using related tags"

we already have both options available in remora. how would either of these be different?

**Comment by meldera** [comment]
"if the resource is in a series, an additional link is displayed within the box (below the link text) with a link to 'download all the resources in this series'. There will be be one PDF doc of all the resources in the series which appears in this position on all resources in the series"

- how is this going to work?

**Comment by angievanhegan** [comment]
@StephMSlack We need you to confirm if you want to select the related resources manually, or if they can be pre-selected based on a criteria. Thanks

**Comment by angievanhegan** [comment]
@meldera Resources never have an image - please can you make sure they can't be entered onto the content item by removing the fields. Thanks

**Comment by angievanhegan** [comment]
@russ-manta Can you answer Steph's question?

**Comment by angievanhegan** [comment]
@StephMSlack Russ and I have talked about this and the sensible option here is to have it programatically selected (by topic) but if you want, you can turn this functionality off for a particular resources and enter them manually. A hybrid of both at the same time on one resource is a bit out of scope!

**Comment by StephMSlack** [comment]
@angievanhegan this makes sense. I'm checking with Recia that she is happy with this and will confirm

**Comment by StephMSlack** [comment]
@angievanhegan - Yes, this is fine. Programatically selected by topic with the option to turn off for a particular resource will be fine. Recia can "live with this" :)

**Comment by angievanhegan** [comment]
@StephMSlack Neither did I! Good spot. 

@russ-manta Please see Steph's comments. I hadn't realised that images needed to be added to the body copy in a resource and Steph had (not unreasonably) assumed it could be. Does this mean the text needs to be added in the 'main content' section of the page? And will that mean we need to recode the in page navigation links? Thanks

**Comment by russ-manta** [comment]
@StephMSlack re inline images in the WYSIWYG we strongly feel this is not a way to go and it is best to use content blocks and then an image  followed by another content block.
The reason being that: 'styling becomes very tricky when clients have to manually float things and apply classes. Inline images can very easily break the layout of a page. Applying classes in a wysiwyg is not a nice process and uploading images in the wysiwyg itself is a bit clunky'

**Comment by angievanhegan** [comment]
@meldera Issue 2 (see list at the top) can be worked on) issue 3 still needs a reply from STeph.

**Comment by meldera** [comment]
https://github.com/MantaRayMedia/bgs/issues/77#issuecomment-357303090

 - "we already have both options available in remora. how would either of these be different?"

**Comment by angievanhegan** [comment]
@meldera Please can you @ the person you're asking the question to and assign the issue to them? Thanks

@russ-manta Presumably this question is for you.

**Comment by StephMSlack** [comment]
@russ-manta - Happy to add them whichever way, but we will need to have images/tables spaced within the resources text. Many clinical and research papers have diagrams that will need to be placed next to the associated text. Currently all the body text for the resources pages is sitting in the overview section, so not sure how adding a new content block will impact the in-page sticky nav.

Sample pages on our current site below
http://www.bgs.org.uk/care-and-support-planning/cga-toolkit-category/cga-personal-care-plan-full
http://www.bgs.org.uk/socioeconomic/cga-toolkit-category/how-cga/cga-assessment/cga-assessment-social/cga-social-assessment

**Comment by russ-manta** [comment]
@StephMSlack Thanks, these layouts are all fine. I notice in this page http://www.bgs.org.uk/care-and-support-planning/cga-toolkit-category/cga-personal-care-plan-full there are some image maps with hovers.  We would probably need to recreate those as SVGs for you and insert them ourselves but for any standard images and tables etc there will be no problem with you being able to do what you need

**Comment by StephMSlack** [comment]
thanks @russ-manta. When I add an image in the content block it defaults to the bottom of the page. Could you/one of your team walk me through how I could insert it partway down the page and still have the sticky nav working? 
EG I'd like to put an image within the reports and drivers section of this page - http://bgs-dev.mrmdev.co.uk/peri-operative-care-for-older-patients-undergoing-surgery

**Comment by russ-manta** [comment]
@StephMSlack sticky nav also works within the content blocks so you can just use those when you need to and intersperse images as needed.  I've added some more content to your article here to show you : http://bgs-dev.mrmdev.co.uk/peri-operative-care-for-older-patients-undergoing-surgery

**Comment by russ-manta** [comment]
@cutlern clarification of issue #3 above: 'first filter is to show content that also has that topic tag, then second filter of document type - so if they are looking at a good practice guide then they would see other good practices guides with the same topic, then other other types of resources after that. Does that make sense?' so in essence it's kind of ordering by document type

**Comment by angievanhegan** [comment]
@russ-manta Can you review this please ?Thanks

**Comment by angievanhegan** [comment]
@pipe-manta Can you look at issue 4 please? Thanks

**Comment by pipe-manta** [comment]
@angievanhegan ISSUE 4 done

**Comment by angievanhegan** [comment]
@pipe-manta I'm not sure ISSUE 3 is quite right. For example: [Princesa the pooch](http://bgs-dev.mrmdev.co.uk/princesa-the-pooch) suggests [NICE quality page](http://bgs-dev.mrmdev.co.uk/nice-quality-standard-on-transient-loss-of-consciousness) and I can't see they have a topic or a document type in common.

**Comment by angievanhegan** [comment]
@StephMSlack Steve has confirmed that building this to enable you to have programatic AND manual selection of related resource is out of scope. You can either choose which one you'd rather have, or we can give you a quote for having it to do both. Thanks

**Comment by StephMSlack** [comment]
@angievanhegan @ican-icant - Could you give me a quote to have both? thanks

**Comment by russ-manta** [comment]
@angievanhegan 1/2 day for this

**Comment by angievanhegan** [comment]
@StephMSlack This 'blocker' functionality has been estimated at 1/2 day which is £280 + VAT. Would you like us to go ahead with it? Thanks

**Comment by angievanhegan** [comment]
Steph confirmed that we can go ahead with this - bGS would like to be able to set related links programatically, or manually.

**Comment by pipe-manta** [comment]
Hi @angievanhegan There is an example on this page http://bgs-dev.mrmdev.co.uk/resources/boxni-the-dog with both options of the Related resources

**Comment by angievanhegan** [comment]
@pipe-manta @dilwarhussain I don't think issue 4 is working as it should, probably because we didn't specify it very clearly. I've added 6 and 7 to try to explain. Call me if it's not clear

**Comment by pipe-manta** [comment]
@angievanhegan @russ-manta You can heck the related resources view on this pages: 

Programatically selected http://bgs-dev.mrmdev.co.uk/resources/boxni-the-dog

Manually selectec http://bgs-dev.mrmdev.co.uk/resources/princesa-the-pooch

**Comment by angievanhegan** [comment]
![screen shot 2018-04-17 at 09 36 12](https://user-images.githubusercontent.com/3796718/38876776-cc986082-4222-11e8-89be-865b5df3241c.png)

**Comment by pipe-manta** [comment]
@angievanhegan Issue 6,7 and 8 are done

**Comment by angievanhegan** [comment]
@dilwarhussain Steph's confirmed that we can just have them programatically showing topics. We can forget about showing the same content type. :o)

**Comment by pipe-manta** [comment]
@angievanhegan Perfect, it's done

**Comment by pipe-manta** [comment]
Hi @angievanhegan , yes, the number 8 it's done

**Comment by StephMSlack** [comment]
@angievanhegan @pipe-manta 
Where do we add the information text?
![screen shot 2018-04-19 at 09 50 43](https://user-images.githubusercontent.com/32127102/38981378-2919de54-43b7-11e8-94a3-f2dc02585d68.png)

can we reduce the space between the end of the comment box and then 'you may be interested in/in this series' boxes? there is a lot of white space which makes the page really long

the text you may also be interested in is appearing when there is no programatic feed below
![screen shot 2018-04-19 at 09 56 44](https://user-images.githubusercontent.com/32127102/38981917-6fa87bae-43b8-11e8-8e2e-9c218ed7c662.png)

**Comment by pipe-manta** [comment]
Hi @StephMSlack You can add the description on each term of Resource type vocabulary.

**Comment by StephMSlack** [comment]
thanks @pipe-manta

**Comment by angievanhegan** [comment]
@StephMSlack can I move this to done? Thanks

**Comment by StephMSlack** [comment]
@angievanhegan there were other comments 
can we reduce the space between the end of the comment box and then 'you may be interested in/in this series' boxes? there is a lot of white space which makes the page really long

the text you may also be interested in is appearing when there is no programatic feed below

**Comment by angievanhegan** [comment]
@dilwarhussain please see issue 9 and 10. Thanks

**Comment by StephMSlack** [comment]
@angievanhegan I'll have to test the programatic feed and spacing once the topics have been cleaned up and added to the resources.

**Comment by StephMSlack** [comment]
@dilwarhussain @angievanhegan I've just added some attachments in the body content of a resource. The lines are not meeting (screen shot below).

Also I thought the PDFs were supposed to take the first page of the attachment as the cover image automatically. Is this still the case?

![screen shot 2018-04-25 at 15 41 49](https://user-images.githubusercontent.com/32127102/39253342-8c955cd2-489f-11e8-9826-72e7f9606886.png)

**Comment by angievanhegan** [comment]
@dilwarhussain There's problems with the lines now

**Comment by dilwarhussain** [comment]
@StephMSlack Can you send me a link to the resource please?

**Comment by StephMSlack** [comment]
@dilwarhussain I updated the look of that page so its not there anymore (sorry, forgot I used it as a sample!) Tried to add some attachments to recreate the issue but currently have dial-up style upload speeds. Will send a sample as soon as I can

**Comment by dilwarhussain** [comment]
@StephMSlack I've tried to recreate on the test resource here: http://bgs-dev.mrmdev.co.uk/resources/boxni-the-dog
Thought the issue may be to do with the long filenames so I copied them from your screenshot above but I could not recreate, it's looking fine on my browser here.
<img width="1039" alt="screen shot 2018-05-03 at 16 09 37" src="https://user-images.githubusercontent.com/29142647/39585328-6fa7b0ae-4eec-11e8-99a1-2efea51215e2.png">

**Comment by StephMSlack** [comment]
thanks @dilwarhussain this is also displaying correctly on my browser. No idea what happened with the other version then...

@angievanhegan @dilwarhussain Do the pdfs uploaded in the sidebar nugget automatically grab the cover of the PDF if one is not uploaded separately? See http://bgs-dev.mrmdev.co.uk/resources/effective-healthcare-for-older-people-living-in-care-homes

**Comment by dilwarhussain** [comment]
@StephMSlack No, this is using the standard attachment nugget where you can attach all types of files, you can manually add a cover using the cover field for these. The only field that uses the auto cover is on resources in the overview tab just above the card content.

**Comment by StephMSlack** [comment]
@dilwarhussain thanks! I'm putting the download content in the wrong place then....

@angievanhegan I just need to add topics to resources to check the programatic feed at the bottom of the page and then this is good to go

**Comment by StephMSlack** [comment]
@dilwarhussain I've started adding topics to the CGA resource pages (CGA in community settings) but the programatic feed is not showing up at this point? Is there something else I need to do?

**Comment by pipe-manta** [comment]
@StephMSlack Sorry, we were applying some changes. Now the programmatic feed is showing again automatically.

**Comment by StephMSlack** [comment]
@dilwarhussain question about the programatic feed using topics. Does it focus on the first topic in that resource? eg some resources might have 3 topics listed, so how/which order does the programatic feed choose which resources to feature on another page?

**Comment by dilwarhussain** [comment]
@StephMSlack The 4 resources in the programatic feed are ordered by 'last updated', so the 4 latest resources will show.

**Comment by StephMSlack** [comment]
thanks @dilwarhussain 

@angievanhegan I think this is finally good to go!
