### ISSUE TITLE
Design resources landing/search/results page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#78]
# Done criteria for Manta Ray and BGS
- [x] A version with the search options open https://invis.io/4EDQ458R5#/275012709_Resources-Search-Open_Space
- [x] A version with the search options closed https://invis.io/4EDQ458R5#/275020851_Resources-Space
- [x] Has a reset button for the search
- [x] Show more search results
- [x] Has the promo below the results
- [x] ISSUE: More space between the search results

# Designs & Docs
- Wireframes:  https://realtimeboard.com/app/board/o9J_k0NkHnc=/?moveToWidget=3074457345944839528

**Comment by angievanhegan** [comment]
@cat-manta Please can you add a link at the top of this issue to a version with the search options open? Then you can move it over to BGS review and assign it to Steph. Thanks

**Comment by cat-manta** [comment]
@angievanhegan @StephMSlack I have made some changes to the search options box, and have swapped the promo and results on the closed search options page, which Steve and I think is much clearer. I have kept it in the original order on the open search options page for comparison.

**Comment by angievanhegan** [comment]
@cat-manta you two are a great team! 👍

**Comment by angievanhegan** [comment]
@cat-manta Steph end I prefer the tick boxes on the right, but you can @ican-icant can decide.

**Comment by cat-manta** [comment]
@angievanhegan 
@ican-icant prefers on the right so I have updated this, although I have just noticed the wireframes are different to the design, so do I need to update the design to match?

**Comment by StephMSlack** [comment]
@cat-manta @angievanhegan Thanks for these. I have asked for comments from the team. From me:
Can we increase the default number of search results displayed?
Prefer the Promo below the results
we may need some explanatory text on this page and a way for people to know what the difference between a case study and a policy digest are (should be self explanatory, but maybe not).
Will feed back other comments as soon as I have them

**Comment by angievanhegan** [comment]
@StephMSlack I've added these as issue above for @cat-manta. Should we wait for all the feedback before we make these changes?

Also, can I suggest we try building the page without the additional explanations about the types then add them if you find they're needed? Thanks

**Comment by StephMSlack** [comment]
@angievanhegan @cat-manta Just looking at these pages again - I think we may need to review the use of colour as we discussed in December. This resource page has become very pink again. Whilst the hovers may be blue, most people are not going to be hovering over each link.

<img width="1422" alt="screen shot 2018-01-17 at 22 26 31" src="https://user-images.githubusercontent.com/32127102/35047757-d90a7244-fbd5-11e7-939c-fac52129a756.png">
<img width="1440" alt="screen shot 2018-01-17 at 22 27 28" src="https://user-images.githubusercontent.com/32127102/35047762-df9d1ac6-fbd5-11e7-813f-5bf38f2e0daa.png">
<img width="1440" alt="screen shot 2018-01-17 at 22 27 15" src="https://user-images.githubusercontent.com/32127102/35047764-e0e64632-fbd5-11e7-8670-75529583c7a9.png">

**Comment by angievanhegan** [comment]
@cat-manta Can we make the search options text and background blue? @StephMSlack We still have a global review of highlight colours planned. I still think it'll be better if we do this when everything has been built so that we can make sure we are using colours consistently across the site. Thanks

**Comment by angievanhegan** [comment]
@StephMSlack this is ready for you to review. Ta

**Comment by angievanhegan** [comment]
@cat-manta @ican-icant I just looked at this resources search/landing page again https://invis.io/NAF7LMUMY. Do you think the results should be more spaced out, vertically? I wonder if they looked a bit packed in and might be hard to scan?

**Comment by angievanhegan** [comment]
@StephMSlack if you can review and sign this one off asap that'd be great. I really want to be able to  move ahead with building and styling this page. Thanks

**Comment by StephMSlack** [comment]
@angievanhegan @cat-manta - My web group is happy with this page. 
If we could look at increasing the space between the tiles, making the start/end date styling consistent with the event search style that would be great
If we could also look into the possibility of the card hover showing the intro text for the resource that would be helpful from a user knowledge point of view.
thanks
Steph

**Comment by angievanhegan** [comment]
@cat-manta These can move to signed off in Invision
