### ISSUE TITLE
Build/style resources landing/search/results page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#79]
Note: Does not include:
- Promo for Age and Ageing #95 

# Done criteria
- [x] **ISSUE 18**: All box links should be the same height. 
  - [x] They will display a maximum of three labels (members only, in a series, resource type)
  - [x] There should be room for four lines of title - the character limit should be set in Drupal
  - [x] A character limit should be set for the card summary so that it does not flow off the box link
  - [x] These same dimensions for the box links should appear: after any filter has been done, on a series landing page, on the resource page for other resources in this series, on a resource page for related links
- [x] **ISSUE 17**: Search options background is blue - see design
- [x] **ISSUE 16**: Search options needs a plus/minus sign
- [x] **ISSUE 15**: Search box should be wider - see design
- [x] **ISSUE 14**: Make sure spacing between search results is the same as the [updated design](https://invis.io/SZFJ0WUJDMV). Margin bottom. 
- [x] **ISSUE 13**: Resource images are only for the cover (for the download) and should never appear on the landing page (I've asked @meldera to remove this field from Drupal in #77)
- [x] **ISSUE 12**: 'In a series' label not showing
- [x] **ISSUE 11** Checkboxes not aligning
- [x] **ISSUE 10** select buttons for clinical and research resources are out of alignment
- [x] **ISSUE 9** Replace Checkboxes, copy the code from EAHealth
- [x] **ISSUE 8**: Hover over card displays resources summary on a white background (the same behaviour as the card content on landing pages)
- [x] **ISSUE 7** If you select clinical/research resource the the summary displays on the card, rather than on hover as it should. 
- [x] **ISSUE 6** after search or selecting select boxes the resource card changes and displays the summary text on the card - this is NOT necessary. It should stay the same.
- [x] **ISSUE 5** Grid and list icons are the wrong way around
- [x] **ISSUE 4** the graphics being used for the grid and list views need to be swapped
- [x] **ISSUE 3** Search button is too big / out of alignment
- [x] **ISSUE 2** The copy 'Members only content. Please log in.' is out of alignment
- [x] **ISSUE 1** Resource rollover issue: This resource has a rollover text and I think this pushed the tag down - see the image
- [x] Search box appears as per design and searches on the following fields:
  - [x] Title
  - [x] Long title
  - [x] Authors (see #92)
  - [x] Short intro
  - [x] All text in content blocks in Main content section
  - [x] Document Type
  - [x] Topic
- [x] Search appears as per design (closed by default)
  - [x] **Drop down for resource series**
  - [x] Type
  - [x] Topic (doesn't need to say 'tags' in brackets
  - [x] Author
  - [x] Start date
  - [x] End date
- [x] Check boxes for clinical and research resources
- [x] Search works and results appear
- [x] Results filter includes: Latest, most popular, relevante
- [x] Grid and list views work and display as per design

![image.png](https://images.zenhubusercontent.com/598c61aff8b79f8376e2a502/8fbf4fb4-65af-44ab-9cb6-3ddf40006b57)

# Designs & Drupal link
- [Wireframes in RT board](https://realtimeboard.com/app/board/o9J_k0NkHnc=/?moveToWidget=3074457345944839528)
- [Design in invision](https://invis.io/5YFFKACD6UB)
- Drupal link: http://bgs-dev.mrmdev.co.uk/resources

**Comment by angievanhegan** [comment]
@russ-manta please could you estimate this? Thanks

**Comment by angievanhegan** [comment]
@pipe-manta Can you put a link the Drupal page at the top? Thanks

**Comment by pipe-manta** [comment]
@angievanhegan Done!

**Comment by angievanhegan** [comment]
@pipe-manta I must be looking at the wrong thing, this isn't looking anything like the design!
![screen shot 2018-01-19 at 17 42 55](https://user-images.githubusercontent.com/3796718/35175159-6823ebac-fd40-11e7-81df-fea60138bbf3.png)

**Comment by angievanhegan** [comment]
@pipe-manta I added a new requirement at the bottom of the list.

**Comment by angievanhegan** [comment]
@pipe-manta The design for this page has now been signed off. Please note that more space has been added between the cards. Thanks

**Comment by angievanhegan** [comment]
@pipe-manta Looking good! See the done criteria at the top though, there's still a couple of things missing - hopefully they're all small. Also, I'm not sure the search field is working. Thanks

**Comment by pipe-manta** [comment]
Hi @angievanhegan the drop down in the search for research series don't appear on the wireframes or on the design, do we need to add it?

**Comment by angievanhegan** [comment]
@pipe-manta yes, we need to add the drop down please.

**Comment by angievanhegan** [comment]
@StephMSlack This is ready for you to sign off in Drupal. I think it's working really nicely now. :o)

**Comment by angievanhegan** [comment]
@pipe-manta Sorry, Steve spotted a couple of things. I've added two new issues

**Comment by ican-icant** [comment]
@dilwarhussain          this is looking good now

**Comment by ican-icant** [comment]
@pipe-manta @dilwarhussain the text rollover for the resource card needs to have limited character limit (might be close to 300) and then go to ... the summaries are too long and we don't want to limit them as they are displayed on the node.

**Comment by ican-icant** [comment]
![Screen Shot 2018-02-12 at 10.39.53.png](https://images.zenhubusercontent.com/598c61aff8b79f8376e2a502/364f617b-a6df-4cbb-a97f-513d7dfebfc0)

@pipe-manta @dilwarhussain

**Comment by pipe-manta** [comment]
@meldera The issue with the RHS is still happening, look @ican-icant 's screenshot from today

**Comment by ican-icant** [comment]
@meldera          also after I filter this happens to some of the resources - ![image.png](https://images.zenhubusercontent.com/598c61aff8b79f8376e2a502/1f3d1459-be40-4824-878d-9b6b645a2617)

**Comment by ican-icant** [comment]
Re: ISSUE18 @angievanhegan @StephMSlack 

TITLES:
We can fix the height of the resources box, but at the moment we are fixing the height for each row to cater for long titles, making it more flexible. We can also give you a short and long title field, so if the title is long you can add a short title for the card and display the long title on the node only.


SUMMARY:
If we limit the number of characters for the summary field we will need to have the number of characters available for the smallest sized card (when the screen resizes). Are you OK with that? If you check this out it's not many. There will be a separate field for this summary field tho.

How should we proceed?

**Comment by StephMSlack** [comment]
@angievanhegan @ican-icant 
Titles:
While more flexible, it looked odd having some short and some long cards, so please fix the height of the resource box. 
It is fine to give us a short/long title field if this will make the cards display better.

Summary
I have been using the card content summary field (which currently has a limit of 300 characters) for the card info - I assume that is right? We had discussed in the last sprint meeting possibly having the summary change to ... at the end should any of the text run over. Does this not work (technically or visually)? If not, maybe we reduce the number of characters for the card summary further?

**Comment by angievanhegan** [comment]
@StephMSlack @ican-icant @dilwarhussain The plan we proposed ought to work. The cards are just displaying a short title and a short summary to help people decide if they want to read more. I think four lines of title, plus the date and space for 3 labels should be a good fixed height for large and small screens. Can we go with that and then only look at modifying it if the content *really* can't fit into that space?

@dilwarhussain Please can you go ahead with issue 18. It's be brilliant if you can get if fixed for the demo at 4. Thanks!

**Comment by angievanhegan** [comment]
@StephMSlack Are you happy to sign this off so far? I'm going to create a new issue for the 'related links' at the bottom of the resource page (I'm not sure what it's pulling in) and the the height of the list view on the landing page.

**Comment by StephMSlack** [comment]
@angievanhegan Some odd things on the landing page:
Different numbers of resources appearing when logged in v's logged out
![screen shot 2018-03-08 at 15 46 26](https://user-images.githubusercontent.com/32127102/37160347-ea138c9a-22e7-11e8-8d72-8aff889770c4.png)
When moving to a new page, the search is automatically opening, even though the user hasnt used the search function (both card and list view)
When sorting by latest I'm getting things from 2012 - can we check which field is being used for this sort?
![screen shot 2018-03-08 at 15 50 08](https://user-images.githubusercontent.com/32127102/37160586-79f35566-22e8-11e8-804e-128eb8a62bb4.png)
