### ISSUE TITLE
Create dividing line

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#80]
# Done criteria
- [x] Able to insert line using WYSIWYG

See [example here](http://bgs-dev.mrmdev.co.uk/about/text-formats-dont-delete)

<img width="713" alt="screen shot 2017-11-23 at 13 00 43" src="https://user-images.githubusercontent.com/3796718/33185103-6a59ced8-d04e-11e7-9d5d-aad95a2980f3.png">

# Designs & Docs
- [Line appears on Our Purpose page](https://invis.io/4XEFPWI2B)

# BGS review criteria
[Link to review goes here](http://)
- [x] able to use line

**Comment by angievanhegan** [comment]
@pipe-manta I created a new issue for creating this purple line. I didn't know what to call it! You may want to revise the estimate. Thanks

**Comment by pipe-manta** [comment]
Hi @angievanhegan , we already have that line between each nugget on the main section. The best way to separate texts is using multiple nuggets like "content block" instead the line on the WYSIWYG.

There is an example on this page, http://bgs-dev.mrmdev.co.uk/about/text-formats-dont-delete

**Comment by angievanhegan** [comment]
@pipe-manta It'll get annoying for them though if every time they want to add a line they have to add a content nugget. Is there any way that we can add this line as a style? Thanks

**Comment by angievanhegan** [comment]
Hi @pipe-manta if this if for you then I'm assuming it should be in the in progress column?

**Comment by angievanhegan** [comment]
@StephMSlack Just to clarify, you've got two things here:

1.  the FAQ nugget contains quite a heavy dividing line above it. This is to denote it as a new section.

2. We've created a much softer line which you can use if you like as an optional section divide (which is what this issue is). Perhaps if you have a very long section of text and it needs breaking up. I've seen these as symbols or much shorter lines (I can show you examples if you like). I suspect that these may not get much use! It'd be strange for this to be a heavy line as it'd interrupt the flow of the text a bit too much. If you do find that when you're creating pages this is something you use a lot, we can revisit it and style it in a way you prefer. 

Is this ok?

**Comment by angievanhegan** [comment]
@pipe-manta can you explain how Steph would add this please ?

**Comment by pipe-manta** [comment]
@StephMSlack You can find the option "Insert Horizontal Line" on the WYSIWYG, just need to add a new paragraph and then click on that button.

![image.png](https://images.zenhubusercontent.com/59ef62dca468affe6df7f840/ee9e7544-39c6-48f5-a13e-74bb531d8f21)

Let me know if you have any question.
