### ISSUE TITLE
Review page layout/margins for smaller screen sizes? 

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#84]
# Done criteria for MRM and BGS
- [x] **ISSUE** Update the logo/straplink with the [new size in the design](https://invis.io/YZEOPK1BT) 

[check here on the site](http://bgs-dev.mrmdev.co.uk/)

**TRICKSY** The difference between the left/right hand side page margins on the design in invision and on Drupal (when viewed on a laptop screen) is quite considerable. See images below. Should  we try increasing these margins to make them more similar? 

NB this might also help with the images appearing to be much larger on the team page and about us box links. It may also help with #52 and #53 where what Steph is seeing in Drupal looks different to what she sees in invision. 

<img width="346" alt="screen shot 2017-11-29 at 13 33 02" src="https://user-images.githubusercontent.com/3796718/33392947-8ee98b1e-d50b-11e7-88c1-ccc3561d3745.png">

<img width="272" alt="screen shot 2017-11-29 at 13 34 04" src="https://user-images.githubusercontent.com/3796718/33392948-8f06e830-d50b-11e7-896b-7772167d0b3e.png">

**Comment by angievanhegan** [comment]
Steph and I felt that what makes a difference is the relative size between the content and the masthead at smaller screen sizes (which the majority of NHS users might see). Can we try increasing the size of the strapline slightly to address this balance. Thanks.

**Comment by cat-manta** [comment]
@angievanhegan @StephMSlack I have increased the size of the strapline in all designs

**Comment by angievanhegan** [comment]
How's this Steph? (you can also see it here: https://invis.io/DQEPLPAY4)

![screen shot 2018-01-05 at 12 24 43](https://user-images.githubusercontent.com/3796718/34620447-825a55ac-f213-11e7-8f15-023b65988d4c.png)

**Comment by StephMSlack** [comment]
@angievanhegan this is OK
