### ISSUE TITLE
Right hand nuggets

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#89]
# Done criteria - Manta Ray and BGS
- [x] Content block (with and without image)
- [x] Box link
- [x] Attachment nugget
- [x] Related content nugget
- [x] **ISSUE** reduce title/link text to 22px within the right hand nuggets

(NOTE - this issue doesn't related to attachments #47 and related content #61)

# Designs and Drupal links
- Drupal:  http://bgs-dev.mrmdev.co.uk/examples/right-hand-column
- Design: https://invis.io/YZEOPK1BT

**Comment by StephMSlack** [comment]
@angievanhegan @pipe-manta Please could we make the text smaller for the nuggets, once they are one the live site they feel too large. 
Also on the designs the colour for the titles is purple, but on the live site it is pink.

**Comment by angievanhegan** [comment]
@StephMSlack Do you mean the link text is a different colour? The title for each box is the same as the design. 

When we spoke to you last week about removing some pink, Cat did some extra work to remove pink and this is one of the thing that we thought we could change. However, if you change the link text as per the design, then it's a) not very obvious that it's a link and b) it's the exactly opposite color scheme to the links in the main body - which I thought was very confusing.  We've made them all pink for now so that at the least they're consistent. If we're doing a (highlight) colour review in Jan when you have more content in (as per our discussion) then we can of course revisit this.  

This is all in issue #65 for you ref.

Are you happy to stick with this pink link colour for now?

**Comment by cat-manta** [comment]
@angievanhegan Some of the RHS titles were bigger than others (this was on purpose for the attachment titles), so I have reduced this to be the same as the others, which is 22px. Is this enough, or do they all need to be made smaller?

**Comment by StephMSlack** [comment]
@angievanhegan 22px is fine for all
