### ISSUE TITLE
Confirm requirements for devolved content management AND migration from external sites

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#9]
Links to #26 #27 #28 #29 #30 

# Done criteria
- [x] Tick the sites which are **KEEN** so we can focus on them - Steph to confirm
  - [ ] BGS Cardiovascular SIG
  - [x] Movement Disorder SIG
  - [ ] Scotland BGS
  - [x] West Midland BGS
  - [x] Mersey
- [x] Agree approach (focus on keen ones!)
- [x] Confirm if all the content currently on bgs.org.uk is managed by Recia
- [x] Confirmed likely content types for devolved editing:
  - event
  - resource/ good practice guide/ fact sheet
  - group (group page/SIG page etc)
  - archive
  - research centre
- [x] Make sure Russ know this is the plan

# BGS review
- [x] Agree this strategy of focussing on keen ones

**Comment by StephMSlack** [comment]
Can editorial workflows be added at a later date?

**Comment by angievanhegan** [comment]
@StephMSlack Russ has said that he'd prefer to know this sooner rather than later as it will affect how he'll build the site. 

@russ-manta Can we work on the assumption that we'll have devolved content management at some point, or do you need more detail?

Thanks

**Comment by StephMSlack** [comment]
Devolved Content:
BGS do wish to provide specific external users access to the CMS.
External users:
- can create and edit content
- would not have publishing rights
- can have access to the entire website when adding/editing content (they do not need to be restricted to accessing only certain areas of the website)

**Comment by angievanhegan** [comment]
@StephMSlack Fantastic that you've been able to clarify this much. And it feels like a step in the right direction too. It would seem to me that in order to avoid the well known pit fall of having an organic site structure, it's well worth ensuring that devolved content users can only create specific types of content (i.e. where there is a 'pot' of content and they're just creating another example, like an event, news item, team member) rather than giving them the ability to create whatever they like. Are you ok with that? Assuming you are, can we specify them? Thanks

**Comment by StephMSlack** [comment]
@angievanhegan yes, that is fine. Will check with Recia types of content, but would expect:
- event
- resource/ good practice guide/ fact sheet
- group (group page/SIG page etc)
- archive
- research centre

**Comment by StephMSlack** [comment]
Nothing else to add from Recia at this point re: specific types of content that can be created by an devolved content user.
