### ISSUE TITLE
Page title not centred

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#90]
- [ ] **ISSUE**: Work out if this page heading should be centred or not

http://bgs-dev.mrmdev.co.uk/examples/teams-page

It's entirely likely that I've done something here to mess this up!

**Comment by meldera** [comment]
this is not a top-level page

**Comment by angievanhegan** [comment]
@meldera only pages appearing in the top nav have centred headings?

**Comment by meldera** [comment]
according to this, yes

https://github.com/MantaRayMedia/bgs/issues/75

**Comment by angievanhegan** [comment]
Let's worry about this when we have real content rather than test pages.
