### ISSUE TITLE
Author links on resource page

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#92]
# Done criteria
Note: Might be best to do this just with multi link field rather than entity references to Authors to provide all the flexibility they need
Could use taxonomy term with link field and entity reference field

- [ ] **If author has a person page**
  - [x] Display author's name
  - [x] Enable the editor to amend the text (so that name can be replaced with details on title and/org)  
  - [ ] Text links to person page (if the user and the author are members, the author has opted to be in the member directory and the user is logged in). If the author didn't opt to be in the members directory, then no link should be displayed
- [x] **For an author with no content on Drupal/Civi**
  - [x] Add text with optional link (to external site) 
- [x] **When the author is an organisation**
  - [x] Add text with an optional link (to an external site)

# Designs & Drupal links
- Design: https://invis.io/DQEPLPAY4
- Drupal link: http://bgs-dev.mrmdev.co.uk/resource

**Comment by angievanhegan** [comment]
@StephMSlack Please can you check these requirements when you have a second. Thanks.

**Comment by StephMSlack** [comment]
Hi @angievanhegan these look good.

**Comment by meldera** [comment]
We're looking at a multi-field paragraph for each author with current requirements. Which is definitely an overkill for this purpose...

**Comment by meldera** [comment]
Author vocabulary + term fields (link & entity reference)

**Comment by russ-manta** [comment]
@angievanhegan question to be discussed.. do we need an entity ref to the taxomony term for internal authors to work out if the author has opted into the directory  and we can therefore link to them?

**Comment by angievanhegan** [comment]
When we do the members directory sprint goal we can work out how the links to members should behave
