### ISSUE TITLE
Add favicon

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#94]
# Done criteria
- [x] Favicon designed
- [x] Upload new favicon using the code below (it has a colour correction)

# Designs & Drupal link
- Favicon location:
Files/PROJECTS/British Geriatric Society [585]/Branding/Favicon/favicons

- Favicon code:
```
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#642f6c">
<meta name="theme-color" content="#642f6c">
```

**Comment by angievanhegan** [comment]
@cat-manta I'm sneaking this one in because it will make me happy!

**Comment by StephMSlack** [comment]
@angievanhegan - could you send me a copy of the favicon image?

**Comment by angievanhegan** [comment]
@cat-manta Please can you send @StephMSlack A copy of the favicon image? Thanks

**Comment by cat-manta** [comment]
@StephMSlack Is a .png okay?
![favicon](https://user-images.githubusercontent.com/29398815/35442262-87ed358e-029e-11e8-93a9-4a01109bad38.png)

**Comment by StephMSlack** [comment]
Thanks @cat-manta.
Also apologies - now that I am back in the UK on the BGS systems I can see that we have one already. I am guessing I hadn't sent this to you. Sorry! BGS favicon attached for your information. If you want the .eps version please let me know.
![bgs master favicon purple](https://user-images.githubusercontent.com/32127102/35564312-a4211a48-05b1-11e8-8777-61b9fdf85d4c.jpg)

**Comment by StephMSlack** [comment]
@cat-manta I did notice that as well, but I cannot open the eps file on my system. Yes, please use the BGS purple and our Comms manager is now going back to the designer to find out why they are subtly different!

**Comment by cat-manta** [comment]
@StephMSlack Great I'll pass this onto the devs

@pipe-manta Could you update the favicon please? I have updated the info in the description at the top
