### ISSUE TITLE
Age and Ageing promo with SSO

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#95]
# Done criteria
- [x] Steph to provide a list of pages where the rh promo and full width promo will appear
- [x] **ISSUE 2** Get and add urls of SSO/login pages from journal provider (requested 20 Feb)
- [x] **ISSUE 1**: @StephMSlack  to get a technical contact at Age and Ageing
- [x] Age and Ageing promo works as single sign on for Age and Ageing journal (this is the only promo that behaves like this
- [x] Promo appears on Resources landing page below search options
- [x] Users are taken to the Age and Ageing log in screen if they don't have the SSO
- [x] ~Allow Age and Ageing promo to display on /user page only using design here: https://projects.invisionapp.com/share/WSFH05EPFA6#/screens - should only show for members with certain memberships in Civi (category A members - all , Category B members - Enhanced Benefits ' Category C All overseas members)~

Pages where promo/SSO appears:
- My Account page (sidebar nugget)
- A&A page (sidebar nugget) http://bgs-dev.mrmdev.co.uk/about/what-we-do/age-and-ageing
- Resources landing page (promo)
- Homepage (Promo)
- Member directory pages (promo)

Age and ageing require that users visit their site (for SSO purposes) from a single URL and that this URL is a members only URL. To achieve this we will need to create a specific members only page and perhaps redirect here first from the promo on the resources page before redirecting again onto the Age and Ageing site.

Contact at Journal: **Dwyer Scullion**, Senior Digital Producer, Digital Operations, Global Academic Division,  Oxford University Press, Great Clarendon Street, Oxford, OX2 6DP
+44 (0)1865 354882
dwyer.scullion@oup.com

They have asked that I keep Paul Kidd Paul.KIDD@oup.com, one of the OUP staff in the loop, so I shall email them to let you know you will be in contact.

# Designs & Drupal page
- [Right hand promo on design](https://invis.io/WSFH05EPFA6)

**Comment by angievanhegan** [comment]
@StephMSlack Please can you give us the details for a technical contact at Age and Ageing so that Russ can talk to them about making the SSO work? Thanks

**Comment by StephMSlack** [comment]
@angievanhegan @russ-manta Here you go.
The SSO contact is:
Dwyer Scullion
Senior Digital Producer, Digital Operations
Global Academic Division | Oxford University Press
Great Clarendon Street | Oxford | OX2 6DP
+44 (0)1865 354882
 dwyer.scullion@oup.com

They have asked that I keep Paul Kidd Paul.KIDD@oup.com, one of the OUP staff in the loop, so I shall email them to let you know you will be in contact.

**Comment by angievanhegan** [comment]
@russ-manta What's the next step for this?

**Comment by russ-manta** [comment]
SSO information here: 
[EXTERNAL Member access.docx](https://github.com/MantaRayMedia/bgs/files/1652001/EXTERNAL.Member.access.docx)

**Comment by angievanhegan** [comment]
@russ-manta Here's the file to the age and ageing promo. 
![promo-purple](https://user-images.githubusercontent.com/3796718/35447511-e330bde4-0285-11e8-93ec-4fcafadd22a4.jpg)

**Comment by meldera** [comment]
block added: http://bgs-dev.mrmdev.co.uk/admin/structure/block/manage/block/4/configure
needs target urls...

**Comment by russ-manta** [comment]
@meldera this is the url for the promo for logged in users: https://academic.oup.com/ageing

**Comment by russ-manta** [comment]
@meldera can you take another look?  It still seems to log me in the the remote journal even when logged out and I click the promo

**Comment by StephMSlack** [comment]
@angievanhegan I'm not sure how I can test this one. Do I need a specific account? Also, the SSO is linked to BGS membership levels, which is linked to CiviCRM. Thoughts on best next steps?

**Comment by angievanhegan** [comment]
@russ-manta I'm assuming we need to park this until we've got the members section built until we can properly test it.

**Comment by StephMSlack** [comment]
Pages where promo/SSO appears:
My Account page (sidebar nugget)
A&A page (sidebar nugget) http://bgs-dev.mrmdev.co.uk/about/what-we-do/age-and-ageing 
Resources landing page (promo)
Homepage (Promo)

**Comment by StephMSlack** [comment]
@angievanhegan @russ-manta just looking at the member directory pages - is it possible to have the A&A SSO promo sitting at the bottom of each of the directory pages?

**Comment by russ-manta** [comment]
@meldera as discussed - see the one remaining task at the top of this issue

**Comment by russ-manta** [comment]
@StephMSlack @angievanhegan we've done some more testing on this and unfortunately we can't link directly from more than one page on the bgs site to the journal and use SSO.  Only one URL is allowed and we are unable to trick the journal site into accepting a redirect from another url.  So the options are either just have the SSO promo link on the resources page or perhaps have some kind of intermediate page which is used for the SSO login 'jump point' and any Age and ageing promos from pages on the site go to this intermediate page first and then click a link to go to the age and ageing site.  @steph any thoughts?

**Comment by StephMSlack** [comment]
@russ-manta   I assume this means we cannot put the SSO on the members my account page as each URL is different (helpful!). 
I am leaning towards the jump point option - though I will need to update the text on the promo that signs people in to OUP.

**Comment by angievanhegan** [comment]
@russ-manta Steph says can it link from the My account page?

**Comment by russ-manta** [comment]
@steph do you want it to link for just the my account page then and not resources?

**Comment by russ-manta** [comment]
@StephMSlack  do you want it to link for just the my account page then and not resources?****

**Comment by StephMSlack** [comment]
Hi @russ-manta the users will all need to be signed in to view the journal, so having it in their MyAccount page makes sense. I'll create an A&A promo prompting them to sign into their account to access the journal. 

Only certain BGS member types get the journal: 
category A members - all
Category B members - Enhanced Benefits
Category C All overseas members

**Comment by angievanhegan** [comment]
@russ-manta Right hand promo appears here: 
https://invis.io/WSFH05EPFA6

**Comment by StephMSlack** [comment]
@russ-manta there is also a field in Civi under the users profession - Journal = with journal or without journal that you may be able to use for the SSO

![screen shot 2018-06-28 at 14 54 11](https://user-images.githubusercontent.com/32127102/42038567-2c65e91e-7ae3-11e8-9e88-add005bc4666.png)

**Comment by angievanhegan** [comment]
@pipe-manta Where can I see the right hand promo? I thought it was going on the My Account page? Thanks

**Comment by pipe-manta** [comment]
Sorry @angievanhegan it's my fault, I didn't move that to the staging site. Now is ready to review.

**Comment by angievanhegan** [comment]
@StephMSlack This is ready for you to review

**Comment by StephMSlack** [comment]
@pipe-manta @angievanhegan I signed into my BGS account with an active, category a membership with the journal. I clicked the A&A SSO, got redirected to the OUP website, but I was denied access to the A&A content

Journal message
![screen shot 2018-07-17 at 09 53 36](https://user-images.githubusercontent.com/32127102/42807026-a6d394d0-89a7-11e8-86a1-3a23edd0edb0.png)

Civi record
![Uploading Screen Shot 2018-07-17 at 09.56.43.png…]()

my account page
![screen shot 2018-07-17 at 09 57 17](https://user-images.githubusercontent.com/32127102/42807097-d65d95c0-89a7-11e8-80b5-26420458c548.png)

**Comment by russ-manta** [comment]
@StephMSlack I've just asked for the new url to be allowed for SSO and we'll need to do this again when the site goes live

**Comment by StephMSlack** [comment]
@russ-manta @angievanhegan the URL has been updated and is now working. This can be closed

**Comment by StephMSlack** [comment]
@angievanhegan @russ-manta apologies - I hadnt tested the student membership. @russ-manta which field are you using to decide who sees the journal or not? Not all members see the journal. So a student member who has a current membership without journal should not see the SSO. 

An example on drupal
![screen shot 2018-07-18 at 09 57 52](https://user-images.githubusercontent.com/32127102/42870958-1641a78e-8a71-11e8-83af-32e6dfc7c550.png)

That user account in Civi
![screen shot 2018-07-18 at 09 57 52](https://user-images.githubusercontent.com/32127102/42870997-3399eeae-8a71-11e8-9891-7eb45f809c89.png)
![screen shot 2018-07-18 at 09 58 52](https://user-images.githubusercontent.com/32127102/42871003-376deddc-8a71-11e8-80c6-570649f336b6.png)

**Comment by russ-manta** [comment]
@StephMSlack students have been removed. I think the confusion arose from the comment above saying 'Category A all'

**Comment by StephMSlack** [comment]
thanks so much @russ-manta

**Comment by conferences-BGS** [comment]
@russ-manta @dilwarhussain Can I confirm that the SSO criteria includes Staff memberships?
Cat A - Consultant
Cat A - SpR
Cat A - CMT
Cat B - GPs, Nurses and AHPS (with journal) - enhanced benefits
Cat C - Overseas
Staff
