### ISSUE TITLE
Build/style Feedback for resources

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#96]
The CAPTCHA or RECAPTCHA has been added as  go live task. We will style it when it's been added. 

# Done criteria
- [x] ISSUE: Shading and plus/minus sign don't appear for the feedback heading (FAQ style)
- [x] ISSUE: The checkbox for adding the feedback section should go within the main column of editing options in Drupal rather than on the right hand side (ideally it would be below resource type)
- [x] ISSUE: @cat-manta to provide a design for the feedback section to include text on the wireframe and the recapture field. 
- [x] ISSUE: Send an email which includes the url of the page it was send from, the feedback and the email address (if there is one) - we don't need to store this information in Drupal.
- [x] ISSUE: Feedback box is always open and does not expand / close
- [x] Editor can choose for this to appear or not
- [x] Appears on the page as closed by default
- [x] Email address field is optional
- [x] Contains a recaptcha box 
- [x] Displays a message when it's sent 'Thank you for your feedback' without reloading a new page
- [x] Only appears on resource content type

# Designs & Drupal page
- Design: https://invis.io/DQEPLPAY4
- Drupal: http://bgs-dev.mrmdev.co.uk/resource

**Comment by meldera** [comment]
captcha + honeypot or recaptcha?

**Comment by meldera** [comment]
recaptcha it is

**Comment by angievanhegan** [comment]
@meldera please can you add a link in the top box to a page in Drupal where I can see this to test it? Thanks

**Comment by angievanhegan** [comment]
@cat-manta I thought there was a design for the feedback section, but maybe I imaged it. Can you update the design with one please? Thanks

**Comment by cat-manta** [comment]
@angievanhegan There was a design but it was decided to keep it closed, I have updated the design with it open. @meldera I'm not sure if you've started this yet but I have also changed the colour of the feedback title background.

**Comment by angievanhegan** [comment]
@cat-manta Thanks. Looks good. It also needs to have text to tell people that their comments won't be published on the site. And include the captcha stuff. Thanks

**Comment by cat-manta** [comment]
@angievanhegan I have updated the design with those extra bits.

**Comment by angievanhegan** [comment]
@cat-manta This all looks great. I'll remove the 'design' label. Thanks

**Comment by angievanhegan** [comment]
@russ-manta This design has been fully completed now - it can be assigned to a Dev. I'm not sure if @pipe-manta is doing this one or not? Thanks

**Comment by angievanhegan** [comment]
@russ-manta Ready to be assigned to a dev

**Comment by meldera** [comment]
@angievanhegan yes, recaptcha should be used. this is a go-live task, as bgs need to sign up to use that.

**Comment by meldera** [comment]
/admin/config/people/captcha/recaptcha

**Comment by angievanhegan** [comment]
@meldera thanks for the explanation - I'll create a go live task.

**Comment by angievanhegan** [comment]
@StephMSlack this is ready for sign off. I've added a task to include CAPTCHA as a go live task (#144) we'll style it when we add it.

**Comment by StephMSlack** [comment]
@angievanhegan email is still showing as mandatory when providing feedback
![screen shot 2018-03-08 at 15 58 53](https://user-images.githubusercontent.com/32127102/37161136-cc54b308-22e9-11e8-8b3e-781d3ff932e8.png)

**Comment by angievanhegan** [comment]
@StephMSlack Email is no longer mandatory. This can be signed off. Thanks

**Comment by StephMSlack** [comment]
@angievanhegan design and user input is fine. 

@dilwarhussain @angievanhegan 
I assume this form is the one called 'feedback on this resource". When I look at the form in the CMS it doesn't seem to be capturing any submissions. Also, I think the email is set to go to Dilwar, so I cannot check if the emails are sending.

**Comment by angievanhegan** [comment]
@StephMSlack In the requirements we said that the details just need to be sent by email to a specified email address. This will be done and tested when we're moving the site over to production.

**Comment by StephMSlack** [comment]
@angievanhegan OK, I just assumed it would also automatically populate the form. This is fine

**Comment by angievanhegan** [comment]
@StephMSlack Sure. I've updated the issue.
