### ISSUE TITLE
Set publish and expiry dates for resources

### ISSUE THREAD

**Issue by angievanhegan** [MantaRayMedia/bgs#98]
# Done criteria
- [x] Enable the editor/admin to set a publish date for a resource
- [x] Enable the editor/admin to set an expiry date for a resource

CRON job needs setting up (on live site)
Need to decide how often it runs

**Comment by russ-manta** [comment]
@meldera I think there's a module for this?

**Comment by meldera** [comment]
https://www.drupal.org/project/scheduler can schedule automated publishing/unpublishing of nodes

**Comment by angievanhegan** [comment]
@meldera I set the publish and expiry dates (using UK and Mexican time) but it didn't work.

**Comment by russ-manta** [comment]
@angievanhegan which content was this for - it's probably becuae there is no regular scheduled job at the moment

**Comment by russ-manta** [comment]
@cutlern can you look at this one too please?

**Comment by angievanhegan** [comment]
@StephMSlack It looks like this one is ready for you to check too.

**Comment by StephMSlack** [comment]
@angievanhegan Checking this today/tomorrow

You mentioned at the top the Cron job - this is definitely not running on the live site at the moment, and ideally should be

**Comment by StephMSlack** [comment]
@angievanhegan this is working as well.
